### ISSUE TITLE
Socket socket=IO.socket(url) crashes application

### ISSUE THREAD

**Issue by cyberhck** [socketio/socket.io-client-java#108]
```
String url="http://192.168.42.63:3000";
try{
    URI uri=new URI(url);
    Socket socket=IO.socket(uri);
}catch (Exception e){
    Log.d("exception",e.toString());
}
```

This part of my code crashes my application, I've no luck solving that. I even went through source but no luck, please fix as soon as possible.

However,
the following code doesn't crash application but it throws an exception instead, but isn't able to connect to server

```
String url="192.168.42.63:3000";
try{
    URI uri=new URI(url);
    Socket socket=IO.socket(uri);
}catch (Exception e){
    Log.d("exception",e.toString());
}
```

This code results in the following exception.
java.net.URISyntaxException: Illegal character in scheme at index 0: 192.168.42.63:3000
I've downloaded socket.io-client-0.4.1.jar from Maven Central.

**Comment by nkzawa** [comment]
Hmm, I think that should never happen... Can you post dump of logs?

**Comment by cyberhck** [comment]
Surprisingly I don't have anything in Logcat
Do I need to run those tasks in a Async task or runnable? I tried those but no luck

**Comment by rkhapare** [comment]
You need the json jar http://search.maven.org/remotecontent?filepath=org/json/json/20141113/json-20141113.jar

**Comment by nkzawa** [comment]
@rkhapare thx for your help :)
@cyberhck You don't need AsyncTask or others.

**Comment by cyberhck** [comment]
I tried using jar, and then using / not using assync task. no luck. Instead I went for custom rest like API, (I was trying to do a simplex communication)

**Comment by shuoli84** [comment]
@nkzawa @cyberhck Any update? Mind to close this issue or provide more info?

**Comment by cyberhck** [comment]
Sorry was out for few days so wasn't on github, I don't know if anyone else has faced the same issue, I removed socket.io client and started using custom web sockets temporarily should check with @nkzawa
