### ISSUE TITLE
socket is not disconnecting when network is off.

### ISSUE THREAD

**Issue by kumarkalluri** [socketio/socket.io-client-java#109]
In android,  When ever network is disconnected, The event which is socket 'onDisconnect' is not firing. 

once network is connected, The previous events are fired one by one to server

And also, When ever app kills, socket onDisconnect is not firing.

**Comment by nkzawa** [comment]
Socket.IO checks network conditions by heartbeat (ping/pong), and it might take a while to detect the disconnection (it depends on your setting: see `pingTimeout` https://github.com/Automattic/engine.io#methods-1).

**Comment by shuoli84** [comment]
If you are using websocket transport, the underlying socket broken will trigger Disconnect immediately.

**Comment by OAbdan** [comment]
facing the same issue(on some devices) although i'm only using the websocket transport i think i should define my own connectivity receiver and connect/disconnet the socket by myself

**Comment by marcdoan** [comment]
Any updates on this? We're experiencing the same issue with Android phones on the Sprint network. These phones lose network connectivity when the user is on a call, but the disconnect event doesn't seem to be firing on the phone. It does, however, fire on our Node servers...

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
