### ISSUE TITLE
DexGuard optimization issue

### ISSUE THREAD

**Issue by netanele** [socketio/socket.io-client-java#112]
Hi,

We have found that while using this library in our project and running DexGuard optimizations on it; the library functionality breaks down. 
After some research we have found that configuring the DexGuard optimizations configuration to 
"**-optimizations optimize.conservatively**" fixes the problem.

It's important to note that this does not happen while using full optimizations with ProGuard

**Comment by nkzawa** [comment]
Thanks for your report. Unfortunately, I have never used DexGuard before.
How can I fix this? I feel this is an issue of DexGuard rather than this library.

**Comment by netanele** [comment]
The DexGuard optimization is different than the ProGuard optimization, it does more and changes more code. Take a look a this DexGuard flag "-optimizations optimize.conservatively" in the docs: 
> "Allows input code with ordinary instructions intentionally throwing NullPointerException, ArrayIndexOutOfBoundsException, or ClassCastException, without any other useful purposes. By default, ProGuard may just discard such seemingly useless instructions, resulting in better optimization of most common code."

I guess some research should be done in your code to see where it fails.

Hope it helps...

**Comment by mrgame64** [comment]
Both DexGuard and ProGuard inform its users to be careful with optimization, as it may potentially break functionality. In most cases switching to conservative optimization like @netanele did, is the solution to the problem.

The events described by @netanele are within the expected results of DexGuard's work, so I'd recommend to dismiss this as an unrelated issue.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
