### ISSUE TITLE
It takes client very long time to get connected when using 3G network

### ISSUE THREAD

**Issue by phwowcs** [socketio/socket.io-client-java#122]
Hi,
I am using this library on Android app. The library works fine with Wifi connection(download, upload speed = 12 Mbit/s, 12 Mbit/s ). But when using 3G network(download, upload speed = 4 Mbit/s, 1.5 Mbit/s) client takes very long time( >1 minute) to get connected to socketio server. After client connected, communication between client and server is normal.
Another thing is if I use socketio client in Chrome browser on Android, the speed is very good(also with 3G network).
Are there any help? Thanks!

**Comment by nkzawa** [comment]
Sorry, I have no idea about this issue.

**Comment by phwowcs** [comment]
Hi @nkzawa ,

Thanks for your soon reply!  My issue is the time for socket.io client(an Android app) to connect to socket.io server is very long when the phone uses 3G network(it takes client many minutes to get connected). It is not good for realtime service.

**Comment by shuoli84** [comment]
@phwowcs  have you checked the server side? How long will it take to build the underlying socket?

**Comment by shuoli84** [comment]
@phwowcs @nkzawa I think this is the same issue as 0.5.1 fixed. Could you please check the new version?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
