### ISSUE TITLE
Reopen connection

### ISSUE THREAD

**Issue by MuhammadKamal** [socketio/socket.io-client-java#149]
There's two issues i have:
1-After the app goes to the background for a while when I reopen it doesn't respond to any of the events and sometimes when i try to connect to the server when i click on button  there's no response at all.
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        connectToTheServer();
}
private void connectToTheServer(){
socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.e("connected", "true");
                   //sometimes this message doesn't appear at all when opening the app
                }
            });
}

2-The other issue is:
When I disconnect from the socket then reconnect to it let's say 3 times I receive response from the event 3 times  from any event registered and so on.

**Comment by nkzawa** [comment]
If your app is in idle state for a while, socket.io connection will be lost since it can't respond to heartbeat check.
So you have to disconnect/reconnect according to Activity lifecycle.

see source of https://github.com/nkzawa/socket.io-android-chat how you achieve that.

> When I disconnect from the socket then reconnect to it let's say 3 times I receive response from the event 3 times from any event registered and so on.

Maybe you are listening events when socket establishes connection every time, so that listeners are registered again and again?

**Comment by MuhammadKamal** [comment]
Thx for your quick response but if I want the socket to be connected at all times even if the app in the background using service is that okay?

**Comment by nkzawa** [comment]
I believe you need to use background service to keep connections.
Related: https://github.com/nkzawa/socket.io-client.java/issues/145

**Comment by MuhammadKamal** [comment]
Ok good i'll try to use service the only Remaining issue for me now is that sometimes when the device is kept running let's say for an hour the events doesn't receive any response  it just disconnect without triggering the event disconnect and I have to restart the app to Re Register the events.

**Comment by nkzawa** [comment]
@MuhammadKamal Can you post any logs to reproduce the issue?

**Comment by MuhammadKamal** [comment]
My problem is solved  using service but the remaining one is that if the connection keeps opened for an hour it just doesn't respond to events all you need to do is keep using the sockets for an hour or two or leave it without use i don't know specific case but it doesn't respond after that period.

**Comment by MuhammadKamal** [comment]
@nkzawa 
I've reached the case that makes the events doesn't respond and the socket doesn't connect if i keep connect and disconnect for let's say 10 times then the socket doesn't connect anymore.

public void connectToTheServer(){
         IO.Options options = new IO.Options();
            options.forceNew = true;
            options.reconnection = true;
            socket = IO.socket("http://", options);
            socket.io().timeout(-1);

            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.e("connected", "true");
                }
            });
socket.connect();
}
private void disconnect(){
        socket = IO.socket("http://");
        socket.disconnect();
        socket.close();//I tried to comment this line in my code same result
}

**Comment by joshimohit** [comment]
@nkzawa : just a quick question here : whats difference between socket.disconnect and socket.close()? how does it impact socket.connect() method called after calling disconnect/close method ?

**Comment by MuhammadKamal** [comment]
Sry man disconnect it just calls 
socket.close();
i'm going to edit

**Comment by joshimohit** [comment]
@MuhammadKamal  but whats the difference between these two functions ?

**Comment by nkzawa** [comment]
@joshimohit they are completely the same.

https://github.com/nkzawa/socket.io-client.java/blob/master/src/main/java/com/github/nkzawa/socketio/client/Socket.java#L424

**Comment by MuhammadKamal** [comment]
That's inside the function disconnect() in socket class:
public Socket disconnect() {
        return this.close();
    }
so socket.close as i know it disconnects from socket.

**Comment by MuhammadKamal** [comment]
@nkzawa 
What is the use of socket.off("eventName");?

**Comment by nkzawa** [comment]
@MuhammadKamal that removes all listeners for "eventName".

**Comment by maxwell10206** [comment]
nkzawa I am also having connection issues with socket.io 0.5.2. I am using a background service to connect to my socket.io server. I connect the socket onCreate() and disconnect it onDestroy(). It doesn't happen often but it frequently will lose connection probably due to the service being idle like you said. I can fix the problem by turning on and off data or airplane mode to make the service reestablish connection instantly. Is there a way to stop these random periods of disconnection? It creates a bad user experience when I sometimes open up the app and it doesn't reconnect for 10+ seconds.

**Comment by MuhammadKamal** [comment]
@nkzawa 
Unfortunately the company decided to move to PubNub i was hoping to complete my App using this awesome library but the business rules i know it's none of your business how much we lost from this little issue but you are doing great.
Thanks.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
