### ISSUE TITLE
How to implement socket.io 1.0 in android 

### ISSUE THREAD

**Issue by prabhu-syn** [socketio/socket.io-client-java#16]
I need socket io 1.0.x client in android. but here i can see only java implementation, please any one help me.

**Comment by b95505017** [comment]
I try to replace java-websocket with OkHttp's websocket. It seems works well on my socket.io project.
https://github.com/nkzawa/engine.io-client.java/pull/14
It seems that some tests have error, please give me some advices.
Thanks.

**Comment by shyamjptpm** [comment]
i want to connect socket by query options.i have multiple field.but connection got error and the message is "SERVER ERROR" below is my code.
IO.Options opts = new IO.Options();
        opts.forceNew = isNew;
        opts.reconnection = isRecon;
        String query = "";
try {
            String role = data.getString(Constants.USER_ROLE);
            if(role!=null && !role.equals(""))
                query +="&"+Constants.USER_ROLE+"="+role;
            if(!data.isNull(Constants.REGION_ID)) {
                String regid = data.getString(Constants.REGION_ID);
                if (regid != null && !regid.equals(""))
                    query += "&" + Constants.REGION_ID + "=" + regid;
            }
            if(!data.isNull(Constants.LOGED_PASSWORD)) {
                String pass = data.getString(Constants.LOGED_PASSWORD);
                if (pass != null && !pass.equals(""))
                    query += "&" + Constants.LOGED_PASSWORD + "=" + pass;
            }
            if(!data.isNull(Socketio.NEW_USERS_NAME)) {
                String nameValue = data.getString(Socketio.NEW_USERS_NAME);
                if (!nameValue.isEmpty())
                    query += "&" + Socketio.NEW_USERS_NAME + "=" + nameValue;
            }
            if(!data.isNull(Constants.DEVICE_TOCKEN_KEY)) {
                String deviceToken = data.getString(Constants.DEVICE_TOCKEN_KEY);
                if (!deviceToken.isEmpty())
                    query += "&" + Constants.DEVICE_TOCKEN_KEY + "=" + deviceToken;
            }
            if(!data.isNull(Socketio.USER_ID)) {
                String userID = data.getString(Socketio.USER_ID);
                if (!userID.isEmpty())
                    query += "&" + Socketio.USER_ID + "=" + userID;
            }
            if(!data.isNull(Constants.LOCATION)) {
                String userLocation = data.getString(Constants.LOCATION);
                if (!userLocation.isEmpty())
                    query += "&" + Constants.LOCATION + "=" + userLocation;
            }
            query +="&"+Constants.VERSION+"="+Constants.VERSION_NAME;
            query +="&"+Constants.PROVIDER+"="+Constants.PROVIDER_VALUE;
            opts.query = query;
}catch (Exception e){
            e.printStackTrace();
        }
socket = IO.socket(Constants.SERVER_URL,options);
socket.on(Socketio.USER_ID, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Object obj = args[0];
                }
            }).on(Socket.EVENT_CONNECT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    Object obj = args[0];
                    socket.disconnect();
                }

            }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    Object obj = args[0];
                }

            }).on(Socket.EVENT_CONNECT_ERROR, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    Object obj = args[0];
                }

            }).on(Socket.EVENT_CONNECT_TIMEOUT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    Object obj = args[0];
                }

            });
            if(!isConnected()) {

                    isConnecting = true;
                    isDisconnect = false;
                    //socket.connect(iocallback);

                    socket.connect();

            }

Anybody please help me in query options case

**Comment by shanaulhaque** [comment]
Where i can find jar for socket.io?

**Comment by ImdadulDev** [comment]
private fun  connectUsingConnection(){

        try {
            val socket = IO.socket("https://nodeserver.brainiuminfotech.com:3011/")
            socket.connect()
            socket.emit("connection", "{userid: " + Constants.USER_ID + ", chatToken:" + Constants.CHAT_TOKEN + "}")
         
            socket.connect()
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }


But I am not getting data in server site. server site getting pulling. Is there any error in my code?
