### ISSUE TITLE
xhr post error on slow connection (3G mobile network).

### ISSUE THREAD

**Issue by MohamedHatemAbdu** [socketio/socket.io-client-java#161]
While i am testing my real chat application on 3G mobile network (Slow internet connection),
Socket.io  repeatedly disconnects then reconnects. i have logged the disconnection reason. 
it says "xhr post error" which raise "transport error" then disconnect.

May i know what is the meaning of "xhr post error" and why this error appears in slow connection? and how to solve the problem?.

I am using socket.io-client.java version 0.4.2
Thnx.

@nkzawa

**Comment by nkzawa** [comment]
I'm not sure the actual reason for the issue, but "xhr post error" is the basic message for a polling request error.
Can you post dump of logs and more details if possible?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
