### ISSUE TITLE
Adding dependency into Android Studio

### ISSUE THREAD

**Issue by sweetim** [socketio/socket.io-client-java#17]
I have problem when I try to add the this dependencies into Android Studio gradle

**compile 'com.github.nkzawa:socket.io-client:0.1.2'**

But when I try to build, it display error in the message gradle build

**Warning:Dependency org.json:json:20090211 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages**

Anyone knows how to get this solved???

**Comment by CoderSpinoza** [comment]
Seems like just warnings but how can I remove these warnings?
