### ISSUE TITLE
Socket Connection error

### ISSUE THREAD

**Issue by joshimohit** [socketio/socket.io-client-java#170]
1. On calling socket.connect(), we were continuously receiving Socket.EVENT_CONNECT_ERROR (Internet was ON).
2. We tried disconnect and connect method again and again. but Socket.CONNECTED was not received.
3. However after rebooting the android device, the error donot occur again. 

This is very rare issue. Any suggestions ?

**Comment by nkzawa** [comment]
We need more informations to reproduce the issue.

**Comment by joshimohit** [comment]
Issue is rare but it comes in low network bandwidth case (on 2G). When bandwidth is too low that internet comes and goes again and again, this can be reproduced. Lets say after 100-200 SOCKET_CONNECT_ERROR messages in Low Network Mode, if we get good internet strength, SOCKET_CONNECTED event is not received.

**Comment by shuoli84** [comment]
@joshimohit Which version are you using?

**Comment by joshimohit** [comment]
@shuoli84 Version 0.5.1 .

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
