### ISSUE TITLE
The ready state for manager OPENING not cleared in error

### ISSUE THREAD

**Issue by shuoli84** [socketio/socket.io-client-java#176]
Per one prev bug, now when Manager's readystate is opening, it will skip the reconnect logic. But when an error happened during reconnecting, the ready state not reset, then it will skip further try. 

Related with #172

**Comment by shuoli84** [comment]
```
07-02 13:50:45.966  17697-17697/com.debug E/spotlight﹕ Called update for stock 8828
07-02 13:50:45.976  17697-17823/com.debug E/spotlight﹕ Got error f56a8e35-7204-48fd-99a2-d414e31e4da5 com.github.nkzawa.engineio.client.EngineIOException: websocket error
07-02 13:50:46.106  17697-17823/com.debug E/spotlight﹕ Got error f56a8e35-7204-48fd-99a2-d414e31e4da5 com.github.nkzawa.engineio.client.EngineIOException: websocket error
07-02 13:50:46.116  17697-17823/com.debug E/spotlight﹕ Disconnected null
```

The first EngineIOException is the one which triggers reconnect.
The second one is the one which should reset Manager's state.

**Comment by shuoli84** [comment]
It is not a bug. There should be no blocking code in the Emitter.Listener, which will block the EventThread's thread. Then the tasks in nextTicks won't be executed. It'd better documented somewhere.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
