### ISSUE TITLE
listener does not work first, but work after reconnecting

### ISSUE THREAD

**Issue by sys-samk** [socketio/socket.io-client-java#183]
Hello
I use your great library.
I have a problem.
we have an emit from server with this name : "new-alaki-pack"
after connect to server and emit from that, client can not get this emit but after restart server and reconnect again client can get this emit.
we are Confused.
can you help me?

**Comment by nkzawa** [comment]
Can you post your code here, which we can reproduce the issue? Please make it simple as much as possible.

**Comment by nkzawa** [comment]
Closed due to inactivity. Feel free to reopen.
