### ISSUE TITLE
Switching from org.json to JSON.simple

### ISSUE THREAD

**Issue by mrgame64** [socketio/socket.io-client-java#184]
For greater compatibility and reduced size of the final binary, I'd advise to switch to the more popular and better maintained JSON.simple Java library.

If it's not a problem, I could fork the repo, implement those changes myself and later make a pull request.

**Comment by joshimohit** [comment]
@mrgame64 Android have default support for org.json and not json.simple. Major user of this lib are of Android Apps only.

**Comment by nkzawa** [comment]
I'm not familiar with JSON.simple but it looks org.json is more popular at least.

json-simple

https://github.com/fangyidong/json-simple
http://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple

org.json

https://github.com/douglascrockford/JSON-java
http://mvnrepository.com/artifact/org.json/json

**Comment by eneim** [comment]
In my opinion, there are a lot more json libraries out there with better performance than org.json. Why don't you just give use raw data (Strings, Streams ...) so we can freely process the response?

**Comment by nkzawa** [comment]
@eneim :+1:

That may be cool if users can use any JSON libraries though an adapter.

**Comment by puntogil** [comment]
hi 
json.org is not free
see https://wiki.debian.org/qa.debian.org/jsonevil
yes, sure, Android uses json, but this is a drop-in replacement, under Apache 2.0 license 
https://android.googlesource.com/platform/libcore/+/master/json
For Fedora [1] each project which use the original json library become NOT Free
regards

**Comment by mrgame64** [comment]
The definitions of "good" and "evil" are highly debatable... why would someone insert such a clause?

**Comment by fahimk** [comment]
@nkzawa What's the reason for not using gson or another json mapper that provides a POJO instead of dictionary lookup?

**Comment by nkzawa** [comment]
@fahimk It's widely used, small but enough feature sets for this library. One of the most important reasons was org.json can have any kinds of values like `byte[]` in JSONObject. gson couldn't do that.

**Comment by fahimk** [comment]
@nkzawa ok that makes sense. How would you recommend converting to a POJO other than converting back to a String first?

**Comment by nkzawa** [comment]
@fahimk I don't know other way :(

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
