### ISSUE TITLE
possibility to send cookies

### ISSUE THREAD

**Issue by darkovski88** [socketio/socket.io-client-java#187]
Hello,
is it possible to send cookies over to the server using this library?

Thanks

**Comment by nkzawa** [comment]
You can access to request headers like the following:
 
```java
socket.io().on(Manager.EVENT_TRANSPORT, new new Emitter.listener() {
  @Override
  public void call(Object... args) {
    Transport transport = (Transport)args[0];
    transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
      @Override
      public void call(Object... args) {
        @SuppressWarnings("unchecked")
        Map<String, String> headers = (Map<String, String>)args[0];
        // send cookies to server.
        headers.put("Cookie", "foo=1;");
      }
    });
  }
});
```

Please see README of engine.io-client for the details (https://github.com/nkzawa/engine.io-client.java).

**Comment by darkovski88** [comment]
@nkzawa is this sending the headers while connecting to the server? Because I need this option? Thanks for the response

**Comment by nkzawa** [comment]
In the above example, it will send the headers with each cycle when requests happen, not only while connecting to the server.

**Comment by darkovski88** [comment]
@nkzawa Hey, I've just tried your code and seems that part of it is not called. Do you have any idea why?

<code>
 public void attemptLogin() {
        Log.d(TAG, "logging in");

        try {
            mSocket = IO.socket("https://someurl.com");

            mSocket.on(com.github.nkzawa.socketio.client.Socket.EVENT_CONNECT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    Log.d(TAG, "call " + args.toString() + " connected " + mSocket.connected());
                    try {
                        JSONArray jsonArray = new JSONArray("['Vodafone', 'roberto.grassi.mi@hotmail.it', 'gerard7-8', 'darko.petkovski4@gmail.com']");
                        mSocket.emit(EMIT_OPERATOR_LOGIN, jsonArray);

                    } catch (JSONException e) {
                        e.printStackTrace();
                    }
//                    mSocket.disconnect();
                }

            }).on(EMIT_OPERATOR_LOGIN, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.d(TAG, "on operator login " + args[0].toString());
                }
            }).on("login succeeded", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.d(TAG, "on login succeeded " + args[0].toString());
                }
            }).on("login failed", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.d(TAG, "on login failed " + args[0].toString());
                }
            }).on("redirect", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.d(TAG, "on redirect " + args[0].toString());
                }
            }).on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Transport transport = (Transport) args[0];
                    transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                        @Override
                        public void call(Object... args) {
                            @SuppressWarnings("unchecked")
                            Map<String, String> headers = (Map<String, String>) args[0];
                            // send cookies to server.
                            Log.d(TAG, "sending cookie");
                            headers.put("Cookie", "foo=1;");
                        }
                    });
                }
            });
          
        } catch (URISyntaxException e) {
            Log.d(TAG, "error is happening " + e.getMessage());
            e.printStackTrace();
        }
    }
</code>

**Comment by nkzawa** [comment]
you have to listen the event on `mSocket.io().on` instead of `mSocket.on`.

**Comment by abou7mied** [comment]
@nkzawa Thanks for your attention, but I see the above example should be:
```java
socket.io().on(Manager.EVENT_TRANSPORT, new Emitter.listener() {
	@Override
	public void call(Object... args) {
		Transport transport = (Transport)args[0];
		transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
			@Override
			public void call(Object... args) {
				@SuppressWarnings("unchecked")
				Map<String, List<String>> headers = (TreeMap<String, List<String>>) args[0];
				headers.put( "Cookie", new LinkedList<String> Arrays.asList("foo=1"));
			}
		});
	}
});
```
And worked for me perfectly!
