### ISSUE TITLE
usage with netty-socket-io

### ISSUE THREAD

**Issue by arisAlexis** [socketio/socket.io-client-java#190]
has anyone used it with the java server https://github.com/mrniko/netty-socketio ? 

I can connect from the js client but not from this one (I am trying to unit test). Is there any problem running both under the same jvm?

**Comment by nkzawa** [comment]
Any error logs?

**Comment by arisAlexis** [comment]
I just dont see any connection anywhere its like nothing is happening. Has anyone tried to run them together?

**Comment by ryandietrich** [comment]
I am using this client library against a server based on netty-socketio right now.
Are you able to verify your server is working with a different client?
Are you sure you're hitting the correct registered namespace?

**Comment by nkzawa** [comment]
Closed due to inactivity. Thanks for your report, @ryandietrich !
