### ISSUE TITLE
com.github.nkzawa.engineio.client.EngineIOException: xhr post error

### ISSUE THREAD

**Issue by ZhangPeibin** [socketio/socket.io-client-java#193]
When I connect to sever .It will connect/disconnect repeatly.and I get this error message :com.github.nkzawa.engineio.client.EngineIOException: xhr post error
I found that It may be caused due to different phone Rom。
Plz fix this ! Thank you!

**Comment by nkzawa** [comment]
How can we reproduce the issue?

**Comment by oliverhausler** [comment]
I am also seeing this, and only on one of my phones. What data do you need to debug this?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
