### ISSUE TITLE
Problems to receive 

### ISSUE THREAD

**Issue by RafaelKozar** [socketio/socket.io-client-java#196]
Hello, I do not know why you did not get anything in the function call, someone explain to me?
android side

```
 mSocket.connect();
 mSocket.emit("enviar", "teste");
 mSocket.on("comando", new Emitter.Listener(){
            @Override
            public void call(Object... args) {
                Log.i(TAG, "CHEGOU");
                mSocket.emit("enviar", "teste");
            }
        });
```

server side 

```
io.sockets.on('connection', function (socket) {  
    socket.emit('comando', "frente");  

     socket.on("enviar", function(){
        console.log("irrarra");
     });
```

**Comment by RafaelKozar** [comment]
The first     mSocket.emit ("send", "test"); to the server works well but within the public    void call (Object ... args) { the     mSocket.emit ("send", "test"); does not work

**Comment by nkzawa** [comment]
What if you call `mSocket.connect();` after adding the event listener?

**Comment by RafaelKozar** [comment]
I tried to follow the example of readme.md.
Like:

    // Receiving an object
    socket.on("foo", new Emitter.Listener() {
      @Override
      public void call(Object... args) {
        JSONObject obj = (JSONObject)args[0];
      }
    });

**Comment by racifuina** [comment]
I'm kinda having the same issue right now. But I think "comando" is a reserved Event. Because if you change the event name it will work, at least it did for me, I switched from "comando" to "enviarComando" and it worked fine.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
