### ISSUE TITLE
Initialize socket.io in AndroidStudio

### ISSUE THREAD

**Issue by rafaoli** [socketio/socket.io-client-java#198]
already compiled in gradle...
 compile 'com.github.nkzawa:socket.io-client:0.6.0'

how initialize socket.io ?

**not works...**
socket = IO.socket("http://localhost");

**Comment by nkzawa** [comment]
Any errors or logs ? We can't help you without information.

**Comment by roninhack** [comment]
u can try like this :
public Socket mSocket;
    {
        try {
            IO.Options opts = new IO.Options();
            mSocket = IO.socket("http://192.168.1.2:3000");
        } catch (URISyntaxException e) { }
    }

**Comment by arjun81815** [comment]
You need to specify port address.
try {
mSocket = IO.socket("http://127.0.0.1:8080");
} catch (URISyntaxException e) { }

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
