### ISSUE TITLE
socket.disconnect doesn't close underlying connetions [0.5.1]

### ISSUE THREAD

**Issue by fatihsokmen** [socketio/socket.io-client-java#200]
calling disconnect doesn't close socket.io client connections.

steps:
1 - on server side, I calling following command to list how many open file by nodes (before client connection)
> lsof -i -n -P | grep nodejs | wc -l
> 1

2 - connecting socket.io server from client
> lsof -i -n -P | grep nodejs | wc -l
> 5

3 - Calling disconnect on client sdks
> lsof -i -n -P | grep nodejs | wc -l
> 4

4 - Reconnect server
> lsof -i -n -P | grep nodejs | wc -l
> 6

5 - Calling disconnect on client sdks
> lsof -i -n -P | grep nodejs | wc -l
> 4

6 - Reconnect server
> lsof -i -n -P | grep nodejs | wc -l
> 6

5 - Calling disconnect on client sdks
> lsof -i -n -P | grep nodejs | wc -l
> 5

6 - Reconnect server
> lsof -i -n -P | grep nodejs | wc -l
> 6

5 - Calling disconnect on client sdks
> lsof -i -n -P | grep nodejs | wc -l
> 5

Iterating reconnect-disconnect again, I get 6 and 5 accordingly. Connections leave open till process is terminated manually.

Any idea ?

**Comment by nkzawa** [comment]
Can you post server logs? I'd like to know whether server detects these events.

**Comment by fatihsokmen** [comment]
I sent server log to your e-mail address.
Thanks in advanced.

**Comment by fatihsokmen** [comment]
In the log I can see that server detects disconnect events.

  socket.io-parser decoded 1 as {"type":1,"nsp":"/"} +5s
  socket.io:socket got packet {"type":1,"nsp":"/"} +6s
  socket.io:socket got *disconnect* packet +0ms
  socket.io:socket *closing socket* - reason client namespace disconnect +0ms
  socket.io:socket leave room NyGHy9Zh +2ms

**Comment by fatihsokmen** [comment]
I am suspecting that okhttp in engine.io caches connections and doesn't close underlying connections.

**Comment by nkzawa** [comment]
Thank you for your logs. It looks a server problem for me since server could detect disconnections.
Maybe related to https://github.com/socketio/engine.io/pull/336 .

**Comment by fatihsokmen** [comment]
Here is case where I can manage to have only one connection for a client and it is released after **socket.disconnect** without any problem (desired case)

            IO.Options opts = new IO.Options();
            opts.secure = true;
            opts.transports = new String[] {"websocket"};

This showed me that web socket transport performed as expected.

Please keep this issue open for a while to let anyone comment on this.

Thanks.
