### ISSUE TITLE
setSSLSocketFactory 

### ISSUE THREAD

**Issue by Lir10** [socketio/socket.io-client-java#201]
great lib !!
is it possible to change the defauld ssl socket factory? 
Im using the class NoSSLv3SocketFactory.java which is a custom ssl socket class that extends SSLSocketFactory .

for example like this : 

``` javascript
SSLSocketFactory NoSSLv3Factory = new NoSSLv3SocketFactory(sslContext.getSocketFactory()); 
IO.setDefaultSSLContext(sslContext);
IO.setSSLSocketFactory(NoSSLv3Factory);
```

**Comment by nkzawa** [comment]
Unfortunately, there is no way to set `SocketFactory` for now. You have to set `SSLContext` and a `SocketFactory` instance will be retrieved from the `SSLContext` instance.

**Comment by mynavy** [comment]
Thanks i will try that !

**Comment by dougdiego** [comment]
@mynavy Did you figure out a way to set your own SSLSocketFactory?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
