### ISSUE TITLE
Send ack message to socket.io server and timeout

### ISSUE THREAD

**Issue by pzgz** [socketio/socket.io-client-java#204]
Let's say, we have an android client, which will send an ACK message to server, and then it will expect server send back the ACK message. How should we handle the timeout for expecting the ACK from server?

**Comment by nkzawa** [comment]
There is no timeout for ACK on socket.io. You need to implement it if required.

**Comment by luzianscherrer** [comment]
@pzgz Did you implement it? Would you share your implementation if so?

**Comment by wedneyyuri** [comment]
Would be good to see something similar: https://www.npmjs.com/package/timeout-callback

**Comment by efkan** [comment]
@nkzawa  if `Ack` can be replaced with [`Callable`](https://developer.android.com/reference/java/util/concurrent/Callable.html) it would be great!
Then native Java libraries be used. 

Maybe a simple timeout method below can be implemented:

```
ExecutorService executor = Executors.newCachedThreadPool();
Callable<String> socketCallback = new Callable<String>() {
   public String call(Object... args) {
      // Do stuff over here which may take long
      // Then return a simple String if operations completed
      return "Completed just in time!"
   }
};

Future<String> future = executor.submit(task);
try {
   socket.emit("SomeEvent", socketCallback);
   String result = future.get(5, TimeUnit.SECONDS); 
} catch (TimeoutException ex) {
   // handle the timeout
} finally {
   future.cancel(true);
}
```
Code has been taken from [stackoverflow](https://stackoverflow.com/a/1164333/3765109)

I'm on second day I've been trying to implement timout to socket `callback`. 
I think I have no chance to manage it.
