### ISSUE TITLE
QUESTION: How to join a room?

### ISSUE THREAD

**Issue by john-li-zenith** [socketio/socket.io-client-java#207]
I havent used this to test via android, but by browsing through the introduction and api, i dont see any place that mentions how to join a room in a namespace.

**Comment by wedneyyuri** [comment]
That feature is on the server. 

```
io.on('connection', function(socket){
  socket.join('some room');
});
```

**Comment by john-li-zenith** [comment]
@wedneyyuri  If i understand it correctly, this is for javascript in web browser. I am wondering how an android client could join a room by using socket.io client java.

**Comment by nuclearace** [comment]
No, rooms are a server feature.

**Comment by nuclearace** [comment]
See https://github.com/socketio/socket.io-client-java/issues/202

**Comment by nkzawa** [comment]
@wedneyyuri @nuclearace thanks :smile:
