### ISSUE TITLE
socket transports does't upgrade to websocket problem

### ISSUE THREAD

**Issue by hamberluo** [socketio/socket.io-client-java#210]
i use genymotion android 4.1

```
            IO.Options opts = new IO.Options();
            opts.transports = new String[]{Polling.NAME, WebSocket.NAME};
            mSocket = IO.socket(CHAT_SERVER_URL, opts);
```

results: http://xxx.com/socket.io/?EIO=3&transport=polling
does't automatically upgrade to websocket

```
            IO.Options opts = new IO.Options();
            opts.transports = new String[]{WebSocket.NAME};
            mSocket = IO.socket(CHAT_SERVER_URL, opts);
```

results: http://xxx.com/socket.io/?EIO=3&transport=websocket

but some devices don't support websocket.

**Comment by nkzawa** [comment]
How I can reproduce the issue?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
