### ISSUE TITLE
updating to 0.6.1 causing 'websocket error' -- SocketTimeoutException

### ISSUE THREAD

**Issue by danpe** [socketio/socket.io-client-java#212]
Hey,

Since I updated to socket.io-client-java 0.6.1 I keep getting
 `'websocket error' -- SocketTimeoutException` 
every few (10-15) seconds after a successful connection.

```
W/System.err﹕ java.net.SocketTimeoutException
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.Okio$2.read(Okio.java:139)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.RealBufferedSource.request(RealBufferedSource.java:71)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.RealBufferedSource.require(RealBufferedSource.java:64)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:108)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:95)
09-08 23:39:36.427  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:171)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-08 23:39:36.434  14770-17678/com.myapp.staging W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
```

Than reconnecting also successful but after few seconds error again.
I'm in a loop of connections and disonnections..

Here is my server settings:
```javascript
// Start the server
var app     = express();
var server = app.listen(port);

var io = require('socket.io')(server, {
  'log level': 2,
  'polling duration': 10,
  'close timeout': 12,
  'heartbeat timeout': 30,
  'heartbeat interval': 5,
  'cookie': false
});
```

I'm having like a singelton socket in my Android App, here is function that creates it:
```Java
private Socket createSocket() {
        IO.Options opts = new IO.Options();
        opts.timeout = 10000;
        opts.forceNew = true;
        opts.reconnection = true;
        opts.multiplex = true;
        opts.reconnectionAttempts = Integer.MAX_VALUE;

        try {
            mSocket = IO.socket(mServerUrl, opts);
            registerEvents();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }

        isConnected = false;

        return mSocket;
}
```
Any ideas?

**Comment by nkzawa** [comment]
I have no idea, but it looks your server settings are for socket.io 0.9. What version of the lib did you use before?

**Comment by danpe** [comment]
Yeah I used 0.9, which settings aren't good ? what should I change ?
I actually migrated to 1.x on his first days

**Comment by nkzawa** [comment]
I think these settings would not affect anything, they would be just ignored. I just thought you might migrate from 0.9 to 1.x recently.
What version of Java client did you use before 0.6.1?

**Comment by danpe** [comment]
Yeah I just found out they changed it here https://github.com/socketio/engine.io#methods-1
I used **0.5.1**

Also I succeeded to print the stack trace, added to the issue

**Comment by huynhphan89** [comment]
I resolved this problem by using okhttp 2.4.0.
okhttp 2.5.0 may be changed something.

**Comment by danpe** [comment]
You really had the same issue?
And okhttp is included in the engine.io, how can you use a different version ?

**Comment by huynhphan89** [comment]
This is my exception

com.github.nkzawa.engineio.client.EngineIOException: websocket error
	at com.github.nkzawa.engineio.client.Transport.onError(Transport.java:65)
	at com.github.nkzawa.engineio.client.transports.WebSocket.access$500(WebSocket.java:26)
	at com.github.nkzawa.engineio.client.transports.WebSocket$1$5.run(WebSocket.java:130)
	at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:108)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:95)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:171)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)

Add this line to dependencies section in your gradle file to use a specific version.
compile 'com.squareup.okhttp:okhttp:2.4.0'

**Comment by danpe** [comment]
I think I found our issue...
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-250
Look at the first line:
```
Timeouts now default to 10 seconds. Previously we defaulted to never timing out, and that was a lousy policy. If establishing a connection, reading the next byte from a connection, or writing the next byte to a connection takes more than 10 seconds to complete, you’ll need to adjust the timeouts manually.
```

We need to change the timeout of okhttp for the socket.io connection, just need to find out how to do that.

**Comment by oliverhausler** [comment]
I am seeing breaking connections and irregular communication with socket.io 0.6.0, also in connection with okhttp 2.4.0. With socket.io 0.5.2 the problem is gone.

**Comment by kjkrum** [comment]
[`OkHttpClient#setReadTimeout(0)`](http://square.github.io/okhttp/javadoc/com/squareup/okhttp/OkHttpClient.html#setReadTimeout-long-java.util.concurrent.TimeUnit-)

**Comment by nkzawa** [comment]
0.6.2 is out

**Comment by oliverhausler** [comment]
Which version of okhttp should be installed when using 0.6.2?

**Comment by nkzawa** [comment]
The current latest v2.5.0.

**Comment by oliverhausler** [comment]
When will 0.6.2 be available on maven/jcenter?

**Comment by mklimek** [comment]
+1
