### ISSUE TITLE
Buffer option

### ISSUE THREAD

**Issue by xcpep** [socketio/socket.io-client-java#214]
Hello,

Would it be possible to have a new option implemented to enable/disable buffering of packets if the connection is not active?

**Comment by nkzawa** [comment]
I think it would be difficult since we have no good way to accurately detect if connection is active or not.

**Comment by nkzawa** [comment]
You just need to stop current buffering implementation? Sorry that I didn't correctly understand your issue.

**Comment by nkzawa** [comment]
Closed due to inactivity.
