### ISSUE TITLE
Using socket.io client cause picasso not downloading images

### ISSUE THREAD

**Issue by qkhanh02** [socketio/socket.io-client-java#216]
When I use the lastest socketio client, the picasso library can not load images.
It works fine for this version : com.github.nkzawa:socket.io-client:0.3.0

**Comment by nkzawa** [comment]
I guess that is because both socket.io-client and picasso has okhttp as a dependency and each version is different.

**Comment by qkhanh02** [comment]
What could I do to fix this ?

**Comment by nkzawa** [comment]
You can use old version of socket.io-client.  I feel this is rather the problem of picasso since it depends on old version of okhttp.

**Comment by nkzawa** [comment]
Closing. Feel free to reopen if you have any problems.
