### ISSUE TITLE
SocketIO stream support

### ISSUE THREAD

**Issue by saeednt** [socketio/socket.io-client-java#217]
Are you considering to add Audio stream support for this library?
If yes when is it going to be available?
If not how can I start the process of adding it? Could you please point me to the right direction?

**Comment by nkzawa** [comment]
Unfortunately I have no thought to support streaming, but I think you can easily implement it yourself.
You just have to split audio data to chunks and send them one by one as `byte[]`.

**Comment by saeednt** [comment]
Thank you for your response. I'll try to fork and implement it in a very soon future.

**Comment by ThnksCJ** [comment]
is there a way to implement this yet?
