### ISSUE TITLE
Send file from Android Device to NodeJs Server

### ISSUE THREAD

**Issue by Rishabh43211** [socketio/socket.io-client-java#218]
I am not able to figure out how to send (or emit) a File (e.g., an Image) from an Android Device to a NodeJs Server. Any help would be appreciable. Thanks for your time.

**Comment by nkzawa** [comment]
You can just send `byte[]` which is read from a file.

**Comment by Rishabh43211** [comment]
Hi Sir! Thanks for your valuable reply. 

I did the same (sending a byte[]), but somehow the Developer at Node server was not able to "log" my event (as if it was not emmited) for byte[] case only. However sending in any other form like String, he was able to print and send back Acknowledgements. It worked fine on iOS side (using something like UIImageJPEGRepresentation).  

I have implemented your Library in almost every Project since last 5 months. And its really AWESOME.

Can you please redirect me to any helpful link? I have Googled  almost everything I know (including conversion to Base64).

**Comment by nkzawa** [comment]
Can you post your code? You might have to split a file to chunks and send them little by little if the file is very big.

**Comment by Rishabh43211** [comment]
Hi Again!
Thanx for being so supportive. Finally I was able to send the file
by converting it into Base64 String and decoding it on backend.
Thanx a lot.

**Comment by nkzawa** [comment]
:+1: but still weird because you usually don't have to convert data into base64.
