### ISSUE TITLE
How can i pass my socket object to another activity in android?

### ISSUE THREAD

**Issue by xro7** [socketio/socket.io-client-java#219]
I tried to use intent but i doesnt work. Also i tried to create a SocketHandler class with static methods but i dont think this is the best thing to do. Any ideas?

**Comment by ReneHollander** [comment]
You can use a custom Application class to store that. It is shared across all Activities. Maybe this tutorial helps you: http://www.intertech.com/Blog/androids-application-class/

**Comment by xro7** [comment]
Nice thank you!

**Comment by nkzawa** [comment]
@ReneHollander thanks!

**Comment by deepbhavsar** [comment]
@ReneHollander We need to make socket singleton in application class then we can not emit with different listeners as it will static. We can't emit from activity multiple if we will do then we will receive response in last open activity. share any solution for this case. Thank you
