### ISSUE TITLE
auto reconnecting fails when socket.connect() is called 2nd time in a background service

### ISSUE THREAD

**Issue by abhi922** [socketio/socket.io-client-java#223]
Hi,

I have a service running in the background that manages my socket connection.
The service works perfectly fine after the initial **socket.connect()**  method is called.

By **working fine** i mean that if i disconnect my **WI-FI** and then connect it again, the socket automatically **reconnects** to my server.

But when the socket in idle for a long time, it disconnects from the server. I understand that it's expected behavior. But when i again unlock my phone and start using my app, there is a lot of lag between the socket automatically reconnecting to the server.

In the meantime, a user performs some action to emit some data to my server using the socket, but this will fail as the socket is still disconnected. 

Now what I do here is that I first check if the socket is disconnected, if yes then I execute a **socket.connect()** statement.

My socket connects and everything works fine. But the next time a turn off my **WI-FI** and then turn it on, the automatic reconnecting never happens.

I looked at the code and found that you are using a flag **this.reconnecting** to prevent unwanted reconnecting requests, but it doesn't get cleared in the **destroy()** method on line **538** in **Manager** class.

What happens is that after I call **socket.connect()** 2nd time, this **destroy()** method is called as part of the **cleanup()** process. But the **reconnecting** flag is still **true** and hence when the **reconnect()** method is called, **line 486** in **Manager** class **returns**.

Is this a **bug** or I should not call **socket.connect()** after the initial call to set everything up?

**Comment by nkzawa** [comment]
Thanks for your report. I think this is a bug and we have to insert `this.reconnecting = false;` to https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Manager.java#L465 .

**Comment by abhi922** [comment]
No problem and thank you for such a prompt response.

But I am just curious, why not add this line in **onclose()** function in the same class somewhere between **line 473** and **line 483**?

**Comment by nkzawa** [comment]
Because I suspect this would be the same issue with https://github.com/socketio/socket.io-client/pull/853 . In that case, I think `manager.close()` have to be called first (manually or automaticlly, whichever).

**Comment by nkzawa** [comment]
Should be fixed on 0.6.2. Feel free to reopen if it doesn't solve the issue.

**Comment by abhi922** [comment]
Hi @nkzawa,

I tested the new version. I am still facing the same issue.

I tried to debug the complete program. The thing is that `.onclose()` method (**Line 474** in `Manager` class) is called whenever a disconnection happens but `.close()` method where you put `this.reconnecting = false;` is never called.

**Comment by nkzawa** [comment]
I guess you have to call `close()` method for stopping reconnection first. Even if `onclose()` was called, reconnection doesn't stop.

**Comment by abhi922** [comment]
So you are saying that before calling `.connect()` for the 2nd time, I should call `.close()` first?

I understand that reconnection doesn't stop but when `.reconnect()` method is called, `reconnecting` flag is still true because `.close()` wasn't called and hence the execution `returns` from the first line on that function.

**Comment by nkzawa** [comment]
That's what I meant. But my explanation was wrong, when `onclose()` was called reconnection will start, and `onclose()` would not be called again until once reconnection succeeded(as far as I remember).

**Comment by abhi922** [comment]
Okay. Got it. I tested it by calling `.close()` first and then `.connect()`.
It works perfectly fine.
Thank you.
