### ISSUE TITLE
0.6.2 unavailable on maven

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client-java#224]
Version 0.6.2 is not available on maven or jcenter.

**Comment by nkzawa** [comment]
It's available in Maven, I believe it's synced to jcenter too.

http://search.maven.org/#artifactdetails%7Cio.socket%7Csocket.io-client%7C0.6.2%7Cjar

**Comment by oliverhausler** [comment]
Now it is available, thanks.

**Comment by oliverhausler** [comment]
Now I see the problem that I had. I had your old nkzawa namespace in my gradle, and it didn't accept it because you changed the namespace. Maybe you want to add a warning to the documentation that the namespace has changed.

**Comment by nkzawa** [comment]
Added a warning of the package name. Thanks!
