### ISSUE TITLE
Proguard Obfuscation Problem

### ISSUE THREAD

**Issue by roninhack** [socketio/socket.io-client-java#225]
When i activated proguard , socket.io working regular expect emit function. It seems emit functions not working with proguard,dexguard or allatori, i tired keepclass (or all variants keepclass with members etc..) , results is same emit not working.

tried for proguard  ;
 -keep class com.github.nkzawa.*
-keepclasseswithmembers,allowshrinking class com.github.nkzawa.\* { _; }
-keep class socket.io-client._
-keepclasseswithmembers,allowshrinking class socket.io-client.\* { _; }
-keep class io.socket._
-keepclasseswithmembers,allowshrinking class io.socket.\* { *; }

also tried allatori (accordingly in allatori ) , result still same. I will wait your helps. 

Have a nice days.

**Comment by BurakDizlek** [comment]
did you solve this problem? I'm still trying to figure out a solution, but socket connection is not working while proguard is active.I'm waiting for your answer.

Thank you..

**Comment by crvshdroid** [comment]
Did you solved that problem ? Facing that too.

**Comment by BurakDizlek** [comment]
I defined my model class in the proguard file.

> -keep class com.example.model.** { *; }

If you are using SSL, this may be the reason.
It's work fine like that : 
` 
val socket = IO.socket(socketUrl, SocketOptionsSSL.getOptions())
socketConnect()

 private fun socketConnect() {
        val obj = JSONObject()
        obj.put("type", "client")
        obj.put("userId", "XXXX")
        socket.emit("roomConnect", obj)
        socket.on("tableupdate", onSocketTableStateChange())
        socket.connect()
    }
    private fun onSocketTableStateChange(): Emitter.Listener {
        return object : Emitter.Listener {
            override fun call(vararg args: Any?) {
                try {
                    val socketData = Gson().fromJson(args[0].toString(), SocketDataClass::class.java)
                } catch (e: Exception) {
                }
            }
        }
    }`

**SocketOptionsSSL**
`public class SocketOptionsSSL {


    public static IO.Options getOptions() {


        HostnameVerifier hostnameVerifier = new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                return true;
            }
        };
        TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            @Override
            public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) {

            }

            @Override
            public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {

            }

            @Override
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return new java.security.cert.X509Certificate[0];
            }
        }};

        X509TrustManager trustManager = (X509TrustManager) trustAllCerts[0];

        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .hostnameVerifier(hostnameVerifier)
                .build();
        try {
            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, trustAllCerts, null);
            SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
            okHttpClient = null;
            okHttpClient = new OkHttpClient.Builder()
                    .hostnameVerifier(hostnameVerifier)
                    .sslSocketFactory(sslSocketFactory, trustManager)
                    .build();
        } catch (Exception e) {
            Logger.INSTANCE.d("SocketSSL", "Options çekilirken hata oluştu.");

        }

        IO.Options opts = new IO.Options();
        opts.callFactory = okHttpClient;
        opts.webSocketFactory = okHttpClient;

        return opts;
    }
}`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by ebrahimkarimi** [comment]
same [here](https://stackoverflow.com/q/77272835/7337499)
