### ISSUE TITLE
Socket is automatically disconnected and reconnect repeatedly

### ISSUE THREAD

**Issue by ixsans** [socketio/socket.io-client-java#227]
I've just try an android sample project of implementation of socket.io in this github https://github.com/socketio/socket.io-client-java 

The first i tried, it run normally. The android socket connected with my server and communicate with my nodejs script without any problem. But, when I added signpost library from okhttp to my build.grade,

```
compile 'se.akerfeldt:okhttp-signpost:1.0.0'
```

I found a problem. The app connected with the server at the first time, but after some minutes, the socket automatically disconnect and reconnect repeatedly. 

![screenshot_2015-10-16_11-22-34](https://cloud.githubusercontent.com/assets/7322066/10533778/3a41570c-73f8-11e5-9a41-a679bd7301d9.png)

Any Solution?

**Comment by nkzawa** [comment]
I have no idea. `okhttp-signpost` changes the default behavior of okhttp or something?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
