### ISSUE TITLE
Still frequent disconnects on 0.6.2

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client-java#228]
Even with version 0.6.2 I am still seeing frequent socket disconnects (SDK 17, the same runs fine on an SDK 19 device). I am not sure what causes this, but I suspect a problem with okhttp 2.5.0, as I am also seeing calls to REST endpoints fail on the same device.

I can't say more at this point and will add more information when there is more evidence.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
