### ISSUE TITLE
socket.io and android not connecting a second time

### ISSUE THREAD

**Issue by ben-hudson** [socketio/socket.io-client-java#23]
I'm using socket.io and android. I install the app and it will connect to my server perfectly on the first launch. However, when I exit the app and open it again it will not reconnect to the server.

I notice I get the debug line
`new io instance for http://tyr-einsteinium.rhcloud.com:80/`
 only when the app is run for the first time after install.

Am I not disconnecting from the socket properly? Is there some sort of clean up I need to do when I exit to ensure that I can reconnect to the server when I launch the app again?

**Comment by KimmiDhingra1991** [comment]
I was also facing the same problem.
You should disconnect the Socket in "ondestroy" method
Example:
onCreate(Bundle savedInstanceState){
Socket.on("foo");
}

onDestroy(){
Socket.off("foo");
}
