### ISSUE TITLE
socket.io timeout problem Android

### ISSUE THREAD

**Issue by MaxHastings** [socketio/socket.io-client-java#230]
So it seems that whenever the Android phone goes to sleep long enough for the server its connected to timeout the client, that this problem occurs. The client wakes up and continues trying to reconnect to the server who is now ignoring the client since it already forcibly timed it out (I believe this is where the problem could be fixed if the server told the client hey I killed you already instead of letting the client continue being stupid). The client keeps trying for 60 seconds until finally giving up and establishing a new connection. The only solution that nkzawa and others have said is to acquire a wakeLock and wifiLock, which I think is a bad idea since my app runs in a background service 24/7 on the users phone. Acquiring a wakeLock would prevent the phone from sleeping causing bad battery drainage. Is there any other way to solve this issue?

**Comment by nkzawa** [comment]
wakeLock is a solution when you want to keep connection even if a device went sleeping. 
Otherwise I think you can just close and reestablish connection when it required (like `Intent.ACTION_SCREEN_OFF` and `Intent.ACTION_SCREEN_ON`).

**Comment by maxwell10206** [comment]
I feel disconnecting and connecting to my server isn't a proper solution either. Other apps are able to maintain what seems to be a constant connection without aquring a wakeLock 24/7 since my phone still goes to sleep.

Is there a way to do wakeLock at intervals to check with the server to see if new messages are waiting (chat app). I think apps like Facebook, Snapchat, and Kik do this.

**Comment by nkzawa** [comment]
How about http://developer.android.com/training/scheduling/alarms.html .
Anyway, I think the problem should be what kind of intervals you make connection open/close.

**Comment by fatihsokmen** [comment]
@maxwell10206 When device is not connected, best way to reach device is push notification.
Setting an alarm is not a good practice to wake up device periodically.

**Comment by maxwell10206** [comment]
@fatihsokmen Are you referring to GCM push notifications? Could you explain what you mean?

**Comment by fatihsokmen** [comment]
@maxwell10206 Yes GCM, most of app uses alarms to wake up and sync some data (but not so frequent), but this can not be applied for a real time chat app. Let's talk about an alarm period of 5 or 10 seconds . This will never let device go on sleep. You may try this on your own device, It will quickly drain host device battery. 
Finally it is your design choice but not a good practice. Take a look at this. http://developer.android.com/training/scheduling/wakelock.html#screen

**Comment by maxwell10206** [comment]
GCM would replace socket.io, which I don't want. I have already built my entire app using the socket.io library. I don't plan to implement the alarm idea but I was forced to have my client reconnect to the server every time the phone screen turns on.

**Comment by fatihsokmen** [comment]
@maxwell10206 Sorry if I mislead you. I don't mean replacing socket.io with GCM. They are not rival but complementary. Good luck.

**Comment by miladr0** [comment]
@maxwell1020 Did you solve this problem? I have same your problem

**Comment by maxwell10206** [comment]
@miladr0 Yeah. On my next project I ended up using Google Firebase for push notifications and just simple HTTP calls to a REST API on the backend server.

**Comment by miladr0** [comment]
@maxwell10206 i found startForeground, because i'm using socket.io inside a service. but socket.io has many problem for example phone get heated or drain battery or connect and reconnect so many even on lasted version. i never ever suggest this library maybe uWebSockets is better for my next project. thanks anyway

**Comment by maxwell10206** [comment]
@miladr0 Sockets require a constant connection to a server and use pings to maintain that connection. Socket.io is useful for real time data such as a video game where data is constantly being sent between client and server. For most applications you don't need to have a socket connection. I recommend just  using simple HTTP requests and if you need push notifications use Firebase.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
