### ISSUE TITLE
sending emit with callback inside a thread

### ISSUE THREAD

**Issue by theDude30** [socketio/socket.io-client-java#232]
Hi,
i'm creating a new thread every 5 seconds, The thread tries to send an emit and wait for callback.
The problem is that the thread dies and it doesn't wait to get the callback.
Is there a way to have a synchronize emit? 
or any way to keep thread alive until the callback is fired?

**Comment by nkzawa** [comment]
You can use `LinkedBlockingQueue`, `CountDownLatch` or something like that.

**Comment by theDude30** [comment]
Thanks, adding the CountDownLatch to the thread did the trick.
Now i have a thread that does emit with a callback and when the callback is fire the countdown is called and the thread has ended.
The next issue that i'm having is that i want to create this thread every 5 seconds, when i'm doing while(true) and thread.sleep or wait , it skips the emit in the thread and the call back is not fired at all.

**Comment by nkzawa** [comment]
Sorry I don't get your problem, but it should not be the issue of the library. Please ask it on stackoverflow.
