### ISSUE TITLE
Map<String, List<String>> for header?

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client-java#237]
You had headers as Map<String, String> previously, which has been changed to Map<String, List<String>>. I assume this is so the Cookies header can better be handled, but IMHO this should be out of scope for the socket.io library and you should rollback the format to Map<String,String>. Not everyone is doing cookies, and the header value format should be generic for any application. If somebody needs to handle their cookies, they should use a cookie cutter library for this or do it manually. Having this is socket.io as a feature is confusing. Agree?

        Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
        // modify request headers
        headers.put("Cookie", Arrays.asList("foo=1;"));

**Comment by nkzawa** [comment]
From RFC 6265 http://tools.ietf.org/html/rfc6265#section-3

> An origin server can include multiple Set-Cookie header fields in a single response.

> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field. 

So we can't support Set-Cookie header if our response header was `Map<String, String>`.

I'm not sure what format is more generic, but `Map<String, List<String>>` format is supported in other modules like the followings.

- [URLConnection#getRequestProperties](http://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#getRequestProperties())
- [URLConnection#getHeaderFields](http://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#getHeaderFields())
- [com.squareup.okhttp.Headers#toMultimap](http://square.github.io/okhttp/2.x/okhttp/com/squareup/okhttp/Headers.html#toMultimap--)

**Comment by oliverhausler** [comment]
I agree that if you use headers for cookies, Map <String, List <String>> may be the best data format. But please remember headers are here for all kinds of things, and not everybody who uses headers in socket.io uses them for cookies. The libraries you mentioned below transport the headers folded and only provide local functionality to unfold if required by the client, e.g. toMultiMap() in okhttp.

But if you ask around you'll probably get a lot of different opinions on this subject, and nothing is either right or wrong.


-------- Original message --------
From: Naoyuki Kanezawa
Date:2015/11/01 21:22 (GMT-08:00)
To: "socketio/socket.io-client-java"
Cc: Oliver Hausler
Subject: Re: [socket.io-client-java] Map> for header? (#237)


From RFC 6265 http://tools.ietf.org/html/rfc6265#section-3

An origin server can include multiple Set-Cookie header fields in a single response.

Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field.

So we can't support Set-Cookie header if our response header was Map<String, String>.

I'm not sure what format is more generic, but Map<String, List<String>> format is supported in other modules like the followings.

  *   URLConnection#getRequestProperties<http://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#getRequestProperties()>
  *   URLConnection#getHeaderFields<http://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#getHeaderFields()>
  *   com.squareup.okhttp.Headers#toMultimap<http://square.github.io/okhttp/2.x/okhttp/com/squareup/okhttp/Headers.html#toMultimap-->

**Comment by nkzawa** [comment]
I understand that and I also prefer simple format, but anyway `Map<string, string>` doesn't satisfy our demand in this case. We have to support all kinds of http headers.
I'd like to know if you have any other ideas.

**Comment by oliverhausler** [comment]
No, I don't have any better idea either. If something comes to my mind I'd let you know.


-------- Original message --------
From: Naoyuki Kanezawa
Date:2015/11/02 06:15 (GMT-08:00)
To: "socketio/socket.io-client-java"
Cc: Oliver Hausler
Subject: Re: [socket.io-client-java] Map> for header? (#237)


I understand that and I also prefer simple format, but anyway Map<string, string> doesn't satisfy our demand in this case. We have to support all kinds of http headers.
I'd like to know if you have any other ideas.

-

**Comment by nkzawa** [comment]
Closed for now. Let's create a new issue if we have a good solution.
