### ISSUE TITLE
Add information about transports

### ISSUE THREAD

**Issue by Zo2m4bie** [socketio/socket.io-client-java#239]
Can you add some information about transports in doc. 
Because for work as websocket protocol I had to add 
            options.transports = new String[]{"websocket"};

but I figured it out via very long looking at server logs. If I don't set "websoket", connecting will be done as poling transports

**Comment by djlitvak** [comment]
Agreed - this took me a long time to figure out. I am also curious if I can set my preferred transport methods in a fallback order. If I have websocket set but it fails, will it fall back to polling?

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html
