### ISSUE TITLE
parameter in opts.query became null to server

### ISSUE THREAD

**Issue by alexleekkk** [socketio/socket.io-client-java#240]
I used it on android .
here is my code:

```
 String format = "api_key=%s&time=%s&sign=%s&platform=%s";
 String query = String.format(format, api_key, now, sign, platform);
 IO.Options opts = new IO.Options();
 opts.query = query;
Socket  mSocket = IO.socket(Constants.CHAT_SERVER_URL, opts);
```

The value of api_key became null sometimes.But I'm sure api_key was not null.I printed the log which showed api_key got a value.

I couldn't figure it out why it happened .how can I solve the problem?

**Comment by nkzawa** [comment]
Do you know how we can reproduce the issue?

**Comment by alexleekkk** [comment]
sorry,I didn't find a way,but i will try later.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
