### ISSUE TITLE
How can I see the socket IO logs Android

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [socketio/socket.io-client-java#242]
Hi is there an option like in swift where I can do 

   `public var socket = SocketIOClient(socketURL: hostUrl, options: ["log": true])`
    
   In android will be something like this
   `IO.Options options = new IO.Options();
            options.log = true;`

so I can see the logs but I want this for android, I'm using the library `compile 'io.socket:socket.io-client:0.6.2'`

**Comment by nkzawa** [comment]
This library uses `java.util.logging` package for logging. Please see http://stackoverflow.com/questions/4561345/how-to-configure-java-util-logging-on-android to enable it.

**Comment by deviant-studio** [comment]
this solution doesn't work at least on Android 7.1

**Comment by Zephyer7673** [comment]
i don't see option for log in IO.Options() - in .io-client:1.0.0

**Comment by gaohomway** [comment]
@nkzawa @darrachequesne Can you continue to answer this question?

**Comment by gaohomway** [comment]
@nkzawa @darrachequesne Can you continue to answer this question?

**Comment by chanjungkim** [comment]
no log in 2.1.0

**Comment by ricardopereira** [comment]
I'm also facing the same question. To be honest, this should be more straightforward.

**Comment by marctatham** [comment]
Faced the same issue, came up with an alternate approach to the ones that I've seen suggested here and our beloved StackOverflow that *works* (the suggestions above did not in fact work for me)

Shared my approach here: 
https://stackoverflow.com/a/79073847/2110216
