### ISSUE TITLE
Need to be able to listen to all "other" events 

### ISSUE THREAD

**Issue by chenjianjx** [socketio/socket.io-client-java#243]
After a series of "on event_a", "on event_b", I need to listen to other events that have not been defined by my code. 

This is very important for troubleshooting.   Sometimes I expect the server side to send me an event but it sends me another event which I haven't listened to.  I don't know what this event is because I can't listened to unexpected "other" events.

**Comment by nkzawa** [comment]
Unfortunately, there is no way to do that for now. Basically, you need to know what kind of events server sends.

**Comment by chenjianjx** [comment]
Yes, there is.  Other socket.io java clients can do that.  Can you seriously try it?

**Comment by nkzawa** [comment]
What I meant is this library doesn't support "oher" events. And I have no though to do so for now since JS client also doesn't.
Can you propose this on [socketio/socket.io-client] (https://github.com/socketio/socket.io-client-java/issues)  if you really think we should have the feature?

**Comment by Aksi0m** [comment]
I am also in need for a feature like that!

**Comment by Raduzz** [comment]
Yes. I need to listen all events as well.
There is a working solution for JavaScript [socket-io-client-respond-to-all-events-with-one-handler](https://stackoverflow.com/questions/10405070/socket-io-client-respond-to-all-events-with-one-handler) (second answer).
I see there is a **custom decoder** in **socket.io-client-java** from version **1.0.0**. Is this a way? There is included test in repository but I can not figure out how to use it.

**Comment by pauljackals** [comment]
Hi, JS client has .onAny() now, maybe you'll reconsider adding something like that? 🙂

**Comment by rezafaraji93** [comment]
I really this onAny too!

**Comment by darrachequesne** [comment]
Here we go:

```java
socket.onAnyIncoming(new Emitter.Listener() {
    @OverRide
    public void call(Object... args) {
        // ...
    }
});
```

Included in version `2.1.0`

**Comment by irshadir7** [comment]
is it possible to track all possible events by using 1x version? because the latest version is not able to connect to the server due to incompatibility .  can i achive onAnyIncoming in version 1.0.1

**Comment by darrachequesne** [comment]
@irshadir7 hi! I will backport the changes in the 1.x branch, let me check.

**Comment by irshadir7** [comment]
Hi ,

It would be very helpful.  I am waiting for the update
Thanks
