### ISSUE TITLE
Reconnect apparently not honored

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client-java#244]
As it looks to me (from the perspective of a user and without digging into code), xhr poll error/disconnect happens when there is actual packet loss and the underlying network socket times out (I did parallel pings and noticed poll errors when my trace also dropped out). I believe the reconnect attempts are not properly working, and the network error is passed up to the socket.io layer, instead of the library retrying according the reconnect settings. In other words: Even though the disconnect happens because of an underlying network issue, the library does not reconnect properly as it should.

To prove this, I ran 2 separate sockets against the same server:

```
    IO.Options ioOptions = new IO.Options();
    ioOptions.forceNew = false;
    ioOptions.reconnection = true;
    ioOptions.multiplex = false;
```

Even though the disconnects happened 30 seconds apart, both sockets were reconnected exactly at the same time, and minutes (!) later.

11-07 13:35:32.538 9935-21491/cc.closeup.android I/Socket1 <- disconnect
11-07 13:36:01.188 9935-21924/cc.closeup.android I/Socket2 <- disconnect
11-07 13:37:26.228 9935-23210/cc.closeup.android I/Socket2 <- connect
11-07 13:37:26.238 9935-23212/cc.closeup.android I/Socket1 <- connect

If I set `ioOptions.reconnectDelay` this option is not honored at all as it seems. It looks to me as if the library is confusing threads and therefore misses the reconnect, then passes the error up.

**Comment by oliverhausler** [comment]
I simulating network outages in regular intervals. It is hard to see a pattern, but

- I would see that disconnects are triggered by outages (makes sense)
- multiple sockets do not disconnect at the very same time (depends on how a disconnect is detected)
- if a socket disconnects immediately when the outage occurs, it typically reconnects pretty quickly. But if it takes a few seconds to detect the outage, it seems to miss the reconnect events and it takes ages for it to reconnect. (It eventually reconnects, though.)
- Both sockets don't always reconnect at the same time (as described above), but sometimes minutes apart.

**Comment by oliverhausler** [comment]
The fact that it worked better with the previous version of okhttp made me have a look at their changelog https://github.com/square/okhttp/blob/master/CHANGELOG.md. They apparently changed the default timeout from infinite to 10 secs. Maybe it conflicts with an internal timeout within socket.io

**Comment by oliverhausler** [comment]
@nkzawa How is a disconnect detected on the client? Can you point me to the code please. You made a commit one month ago "fix the case reconnection doesn't work". Does that mean reconnection will work in the next version? Does it make sense that I dig into this?

**Comment by nkzawa** [comment]
A disconnection is detected by timeout of heartbeat check. It's the same behavior with JS client. The code is the following.

https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/client/Socket.java#L545

`fix the case reconnection doesn't work` commit is already released. It will solve reconnection failure in some specific cases.
Please see https://github.com/socketio/socket.io-client-java/issues/223 too.

**Comment by oliverhausler** [comment]
#223 does not apply here, as I am not calling .connect() repeatedly.

**Comment by oliverhausler** [comment]
backoff is not working correctly as it seems. I have filed a new issue #245.

**Comment by oliverhausler** [comment]
see https://github.com/socketio/socket.io-client-java/issues/250

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
