### ISSUE TITLE
jitter not correctly calculated during backoff

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client-java#245]
backoff is not working correctly:

    public long duration() {
        long ms = this.ms * (long) Math.pow(this.factor, this.attempts++);
        if (jitter != 0.0) {
            double rand = Math.random();
            int deviation = (int) Math.floor(rand * this.jitter * ms);
            ms = (((int) Math.floor(rand * 10)) & 1) == 0 ? ms - deviation : ms + deviation;
        }
        if (ms < this.ms) {
            // overflow happened
            ms = Long.MAX_VALUE;
        }
        return Math.min(ms, this.max);
    }

On the first attempt (and dependent on `this.jitter`) `ms` may become smaller than `this.ms`, which ultimately leads to `this.max` being assigned to `ms`. In turn, the first reconnect attempt will not happen after the minimum backoff time as expected, but after the maximum time. This leads to a long period during which we are disconnected.

I would possibly scrap the overflow test 

        if (ms < this.ms) {
            // overflow happened
            ms = Long.MAX_VALUE;
        }
        return Math.min(ms, this.max);

and return `ms` as is:

        return ms;

This may lead to the first reconnect happening before `this.min`. If that is a problem [which - if I apply the idea of random jitter values logically correct - is not], I would add a possibly negative deviation instead of subtracting it, but **never** set `ms = Long.MAX_VALUE`.

BTW: Deviation is calculated from `ms`. I believe it should be calculated from `this.min`. Otherwise we may get quite large values, for example a maximum reconnection time of 15 secs may end up as 22.5 secs with a jitter setting of .5.

I didn't change the code as I am not deep enough into this as to know the implications of what I am doing, but I am quite sure we have a bug here.

**Comment by oliverhausler** [comment]
I made further changes:

- added min and max allowed values for jitter to ensure we don't get any wild deviations (jitter should typically be between 0 and .5, with a max of 1)
- kept the original min value, so we can keep ms within its bounds
- worked on deviation: new, simpler formula for deviation (used as mathematically defined), ensure ms always stays between min and max
- changed deviation to long to prevent unlikely but theoretically possible overflow, as all other time values are long, too

TODO:

- remove FIX comments
- test (NOTE: I edited this blindly as I had no facilities for testing, I ran the formulas in Excel, though)

**Comment by nkzawa** [comment]
Fixed in 0.6.3.
