### ISSUE TITLE
"xhr poll error" after "too many open files" on Android 4.2

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client-java#248]
After a long run, I receive "xhr poll error" consistently. The error happens in Polling.XHR, where xhr.getResponseCode() results in an IOException "java.net.SocketException: socket failed: EMFILE (Too many open files)".

http://stackoverflow.com/questions/20367647/android-httpurlconnection-is-not-closing-eventually-results-to-socketexceptio describes this problem as an issue with HttpUrlConnection in Android 4.1-4.3.

I had the device running all night on a connection with simulated packet loss, so I could see upgrades and downgrades between xhr and websockets.

**Comment by nkzawa** [comment]
Thanks for your report!  So adding Connection=Close to request headers would solve the issue according to stackoverflow.

**Comment by oliverhausler** [comment]
According to Stackoverflow yes. I haven't tried this, though. Let me know if you tested this.

I am currently playing with replacing HttpUrlConnection with okhttp-urlconnection and making the client static in the hope that it helps with connection pooling and with the "too many open files"" issue. I have some tests running for tonight and hope to see more by tomorrow. I'll let you know.

So far I believe the "xhr poll error" will not entirely go away, but using okhttp I could debug deeper and I noticed the timeout which supposedly causes this error is labeled as "NETWORK 400" Bad Request, whatever this means. It's late here but I'll do more tests tomorrow.


-------- Original message --------
From: Naoyuki Kanezawa
Date:2015/11/15 19:06 (GMT-08:00)
To: "socketio/socket.io-client-java"
Cc: Oliver Hausler
Subject: Re: [socket.io-client-java] "xhr poll error" after "too many open files" on Android 4.2 (#248)


Thanks for your report! So adding Connection=Close to request headers would solve the issue according to stackoverflow.

**Comment by oliverhausler** [comment]
"NETWORK 400" seems to be generated by okhttp to indicate a network error and/or timeout.

Somebody (I didn't keep the link) on Stackoverflow said this: "The response is definitely coming from across the network as evidenced by the OkHttp-Response-Source header and the fact that there's a body."

**Comment by oliverhausler** [comment]
I just discussed this with my colleague, and we both tend to not adding "Connection=Close", as this would force the server to close the socket after the request, so it would need to re-open a new socket for each call. Quite expensive.

My other approach of switching to okhttp and using a single static client seemed to have worked. I am not having the "too many open files" issue anymore with a constant "xhr poll error", but I am still seeing "xhr poll error" now and then due to another reason.

Combining above mentioned Stackoverflow article with the fact that exchanging HttpUrlConnection for okhttp-urlconnection did not make the error go away would point to the fact mentioned by @Mark Pazon of Android having a network issue for long-polling in SDK 16-18. Then I guess we can't do much.

I will now focus on limiting the error for xhr polling, and - as sad as that is - we may have to exclude upgrade to websockets for Android 4.2.

**Comment by oliverhausler** [comment]
I posted code for fixing this here: https://github.com/socketio/socket.io-client-java/issues/250#issuecomment-161339709

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
