### ISSUE TITLE
How to use options.query in android socket.io?

### ISSUE THREAD

**Issue by Sarankhuu** [socketio/socket.io-client-java#249]
IO.Options options = new IO.Options();
options.forceNew=true;
options.reconnection = false;
options.query = "loginId="+loginid;

Socket socket = IO.socket("https://myserver:8000/", options);

Then i check query is available in server. But haven't query error

**Comment by oliverhausler** [comment]
@Sarankhuu I'm not the maintainer, but this is an issue tracker and I think you will have more chances to have your question answered if you post on Stackoverflow.

**Comment by Sarankhuu** [comment]
@oliverhausler thank you

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html
