### ISSUE TITLE
on ack callback

### ISSUE THREAD

**Issue by Xeli** [socketio/socket.io-client-java#25]
The function com.github.nkzawa.emitter.Emitter.emit() has an ack parameter. So you can let the server issue a callback which gets executed client side.

Is there a similar way to it the other way around?, so on the client-side: 

socket.on("event-from-server", new Emitter.Listener() {
    public void call(Ack ack, Object... args) {
        ack.call();
    });
});

**Comment by yuzhijun** [comment]
I do like these： Ack ack = (Ack)args[args.length - 1];  ack.call(); but how can server receive ack？
