### ISSUE TITLE
Question: When there is no internet connection, try to reconnect immidiately

### ISSUE THREAD

**Issue by ctoto93** [socketio/socket.io-client-java#251]
It seems there is some delay when there is no internet connect to reconnect. I try to set timeout to -1 but the delay still persist.
Here is my scenario: I want to pop up dialog box, indicating reconnection process. When wifi is turned off when application firstly launch, it works. I listen to "EVENT_RECONNECTING". But when it is already connected and I turn off the wifi, it takes about 2 minutes to trigger the event.

**Comment by nkzawa** [comment]
There are `pingTimeout` and `pingInterval` settings on server side. These are values for detecting timeout. Please read https://github.com/socketio/engine.io.
There is also `reconnectionDelay` on client side, which is for how long it delays before reconnecting.

You can manually reconnect as well like following:
```java
// close the connection or stop auto-reconnection
socket.close();
// reconnect
socket.open();
```
