### ISSUE TITLE
frequently reconnect problem

### ISSUE THREAD

**Issue by RevanScript** [socketio/socket.io-client-java#253]
Every few minutes/seconds, user disconnects from the server. Does anyone know how to fix this issue?

Libraries:
> io.socket:socket.io-client:0.6.2
okhttp:2.5.0
> okio:1.6.0

Log:
> 11-26 16:54:55.397 9649-12396/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 16:54:56.857 9649-12435/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 16:55:57.030 9649-13318/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 16:55:58.232 9649-13341/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 16:56:58.364 9649-14201/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 16:57:03.543 9649-14287/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 16:58:03.706 9649-15228/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 16:58:05.168 9649-15259/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 16:59:05.337 9649-16131/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 16:59:10.579 9649-16214/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 17:00:10.783 9649-16711/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 17:00:15.967 9649-16733/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 17:01:16.213 9649-16823/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 17:01:17.857 9649-16834/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 17:02:18.069 9649-16943/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 17:02:19.737 9649-16956/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 17:03:19.921 9649-17018/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 17:03:25.094 9649-17035/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected
11-26 17:04:25.251 9649-17083/taxi.cloud.cloudtaxi D/LiveService: Socket.IO disconnected
11-26 17:04:26.867 9649-17090/taxi.cloud.cloudtaxi D/LiveService: Socket.IO connected

**Comment by oliverhausler** [comment]
@RevanScript What is your Android version and device?

**Comment by RevanScript** [comment]
@oliverhausler Android 5.1.1 / Xperia Z2 (D6502)

**Comment by oliverhausler** [comment]
I believe frequent disconnects on 5.1.1 are rather related to packet loss on your network than a problem in Android, as it can be seen in some older SDKs. The reason why you stay disconnected for so long is that the library is having a bug. See #245 #246.

**Comment by RevanScript** [comment]
Hm... you are right. I have the same problem in browser client. Thanks!
