### ISSUE TITLE
EngineIOException: server error

### ISSUE THREAD

**Issue by andershagebakken** [socketio/socket.io-client-java#260]
Hi. I am trying to connect to my node.js socket.io server (at 127.0.0.1:9000), but I keep getting the same error: 
"io.socket.engineio.client.EngineIOException: server error".
I am connecting to the same server from a website without any issues. All I have done is added all the dependencies from maven, and tried to add some demo code.

     IO.Options opts = new IO.Options();
     opts.forceNew = true;
     opts.query = "user=testUsername";
     opts.reconnection = true;
     mSocket = IO.socket("127.0.0.1:9000", opts);
     mSocket.connect();

This is the one that gets the error:
    mSocket.on(Socket.EVENT_CONNECT_ERROR, new Emitter.Listener()...

The server also prints all these lines:
GET /socket.io/?EIO=3&user= testUsername&transport=polling 200 1ms - 7.77kb
GET /socket.io/?EIO=3&user= testUsername&transport=polling 200 0ms - 7.77kb
GET /socket.io/?EIO=3&user= testUsername&transport=polling 200 1ms - 7.77kb
GET /socket.io/?EIO=3&user= testUsername&transport=polling 200 1ms - 7.77kb

What can I do to fix this? Thanks for your time and help.

**Comment by nkzawa** [comment]
Umm, need more information. Let me know the versions of server and client, and please post logs and code of server and client if possible.

**Comment by JosselinTD** [comment]
Same problem here !
For the server, I use the version of the yeoman angular fullstack generator :
    "socket.io": "^1.3.5",
    "socket.io-client": "^1.3.5",
    "socketio-jwt": "^4.2.0"
For the android client, I use :
    compile 'com.github.nkzawa:socket.io-client:0.3.0'

Here the log :
12-26 23:55:08.061 6354-6794/? W/System.err: com.github.nkzawa.engineio.client.EngineIOException: server error
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:478)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.Socket.access$800(Socket.java:29)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:285)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.transports.Polling.access$700(Polling.java:15)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.transports.Polling$2.call(Polling.java:122)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.parser.Parser.decodePayload(Parser.java:169)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.transports.Polling._onData(Polling.java:130)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.transports.Polling.onData(Polling.java:99)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
12-26 23:55:08.061 6354-6794/? W/System.err:     at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
12-26 23:55:08.061 6354-6794/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-26 23:55:08.061 6354-6794/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-26 23:55:08.061 6354-6794/? W/System.err:     at java.lang.Thread.run(Thread.java:818)

The connection url :
http://192.168.1.37:9000/socket.io-client

In the NodeJS console :
GET /socket.io/?EIO=3&transport=polling 200 1.514 ms - -
GET /socket.io/?EIO=3&transport=polling 200 0.932 ms - -
GET /socket.io/?EIO=3&transport=polling 200 3.689 ms - -
GET /socket.io/?EIO=3&transport=polling 200 0.816 ms - -
GET /socket.io/?EIO=3&transport=polling 200 3.215 ms - -
GET /socket.io/?EIO=3&transport=polling 200 1.807 ms - -

Do you need more information ? (if yes, how do I get them ?)
Thanks a lot !

**Comment by JosselinTD** [comment]
Ok, I fixed it in 2 operations :

* Changing compile 'com.github.nkzawa:socket.io-client:0.3.0' for compile 'io.socket:socket.io-client:0.6.3'
* In the yeoman angular fullstack generator, I change the two occurences of path: '/socket.io-client' to path: '/socket.io'.

Maybe, the first operation isn't necessary, I don't know

**Comment by andershagebakken** [comment]
I was able to fix it by adding the correct path (opts.path = "/socket.io-client") in the Java code instead of changing it in the angular-fullstack project.
