### ISSUE TITLE
Change Buffer Size

### ISSUE THREAD

**Issue by chelinho139** [socketio/socket.io-client-java#262]
Hello, is it posible to change the buffer size?

we are developing an MMO and we have noticed that when sending small messages the client takes longer to send. If we send the same message but with extra bytes it works perfectly. The only answer that we find is that there is something wrong with the buffer size (probably too big).

By the way, it only happens using Android clients.

Any ideas ? how can it be changed? if not, would it be added on future releases?

Thanks.

**Comment by sebaber** [comment]
i have the same issue, i send small messages in my api (about 7 bytes) and it save some messages in the buffer and send, instead sending without wait for another. That cause me some delay in the api. If i change the size adding extra bytes to the messages, then i assume that the buffer is full and have to send, and the delay stop. Is there some option to set socket for no wait to another messages to send? or something like that?

**Comment by nkzawa** [comment]
This sounds to be https://github.com/square/okhttp/issues/1925. Actually, socket.io (engine.io) doesn't buffer any messages when transport is websocket.

**Comment by chelinho139** [comment]
it seems like making the package size bigger is not "fixing" this problem anymore, it persists no matter the buffer size now. is anyone else also experiencing it?

**Comment by chelinho139** [comment]
farewell socket.io.
It was great, but this problem with the package size and the lack of solutions made us move to ws, in where it runs great.
so for you guys having the same problem try: WS [https://github.com/websockets/ws](https://github.com/websockets/ws)
MessageSize: 7 Bytes
Platform: Android Nexus5, Motorola X, Samsung S3
The average round trip time from android client to server with socket.io was: 90ms
With ws it went down to 30ms.

The problem was never on receiving from the server, the problem was that the android client did not send small packages right away, and therefore took this 60ms justo to send them.

Good luck!
