### ISSUE TITLE
Inner Emit is not working

### ISSUE THREAD

**Issue by JonCostaTaxiADV** [socketio/socket.io-client-java#266]
Hello, I'm having a slight problem with sending an emit from the Node server to an Android app connected to it. Basically, I have a PHP server that sends a socket.emit to the Node server, which should in response send another emit to an Android app. And it's not working quite right so far.
Although the Android app receives messages from normal emits sent from inside socket.on("connection"), it doesn't get any emit from an inner socket.on. In this case, I have a socket.on("event") inside  socket.on("connection"), and it sends an emit, which can't reach the Android app for some reason.

- This is the code in my the app.js file
```javascript
var express = require('express'),
	http = require('http');

var app = express(); 
var server = http.createServer(app); 
var io = require('socket.io').listen(server);

console.log('server started on port 8090'); 

app.get('/', function(req,res){ 
	res.sendFile(__dirname + '/index.html'); 
});

io.sockets.on('connection', function (socket) { 

	socket.emit('event', {content: 'sending message'});

	socket.on('feedback', function (data) { 
		console.log(data); 
	}); // endof socket.on feedback

	socket.on('fromAPI', function(data) {
		console.log('API enviou mensagem');
		console.log(data);
		socket.emit('event', {content: 'sending message again'});
	});

}); // endof socket.on connection

server.listen(8090);
```

And this is the piece of code of how I receive the events in the Android app:
```java
socket = IO.socket("http://10.0.2.2:8090");
            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    sendToast("Conectado ao server");
                    socket.emit("feedback", "Device logged in");
                }

            }).on("event", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.i("NODE", "event came through");
                    JSONObject obj = (JSONObject)args[0];
                    try {
                        Log.i("NODE", obj.getString("content"));
                    } catch (Exception e){
                        Log.e("ERROR", e.getMessage());
                    }
                    socket.emit("feedback", "from Android");
                }
```

Thank you very much for any help that can be offered!

**Comment by wedneyyuri** [comment]
Could you post your question in stackoverflow?

**Comment by JonCostaTaxiADV** [comment]
Okay, I managed to solve the problem by searching around a bit more.
The was a simple change inside socket.on("event")
```javascript
socket.on('fromAPI', function(data) {
   console.log('API enviou mensagem');
   console.log(data);
   //socket.emit('event', {content: 'sending message again'})
   io.sockets.emit('event', {content: 'sending message again'});
});
```
Using that different kind of emit made the message reach the Android app.
I'm very sorry for taking up the time of anyone. Thank you for the attention nonetheless and hope this can help other people out in the future!
