### ISSUE TITLE
Socket listeners not working but emit does.

### ISSUE THREAD

**Issue by kevz93** [socketio/socket.io-client-java#268]
The .on listener never seem to be fired! I've tried multiple versions of socket IO. This is a fantastic library Ive used on javascript. dont know why Java seem to have a problem :(
Ive tried extending the Service class. Weird thing is my emits work properly but my .on listeners don't seem to fire at all! Here is the code :

``` Java
import io.socket.client.IO;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;

public class SocketService extends Service {
    final String TAG="SocketService";
    JSONObject user_data;
    private Socket socket;

    private final IBinder mBinder = new MyBinder();
    public class MyBinder extends Binder {
        SocketService getService() {
            return SocketService.this;
        }
    }

    @Override
    public void onCreate(){
        super.onCreate();
        try {
            socket = IO.socket("http://serverIP:port/"); //this gets connected
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        Log.d(TAG, "onCreate");
        socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

            @Override
            public void call(Object... args) {
                Log.d(getClass().getCanonicalName(), "Connected to server");
            }

        }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

            @Override
            public void call(Object... arg0) {
                Log.d(getClass().getCanonicalName(), "Disconnected from server");
            }

        });
        socket.on("friendcall", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                JSONObject data = (JSONObject) args[0];
                Log.d(TAG, "Handling friendcall");
                try {
                    String callFrom = data.getString("from");
                    Log.d(TAG, "Call from : " + callFrom);
                } catch (JSONException e) {
                    Log.d(TAG, "friend call object cannot be parsed");
                }

            }
        });

        Log.d(TAG, "onStartCommand. Socket should be up");
        socket.connect();
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {

        Bundle extras = intent.getExtras();
        if(extras!=null){
            try {
                user_data = new JSONObject(extras.getString("USER_DATA"));
                socket.emit("giveMeID", user_data.getString("email"));
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }

        return Service.START_NOT_STICKY;
    }


    @Override
    public IBinder onBind(Intent intent) {
        //TODO for communication return IBinder implementation
        return null;
    }

    @Override
    public void onDestroy(){
        socket.disconnect();
        super.onDestroy();
        Log.d(TAG,"onDestroy");
    }

}
```

lib version tried ,

```
compile ('io.socket:socket.io-client:0.6.3') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }
```

Also tried the com.github.nkzawa:socket.io-client:0.3.0 package

**Comment by wedneyyuri** [comment]
Your `Socket.EVENT_CONNECT` event listener is being called?

**Comment by kevz93** [comment]
not at all =/

**Comment by wedneyyuri** [comment]
Any errors on console?

**Comment by kevz93** [comment]
Nopes

**Comment by kevz93** [comment]
I also have server as IP and as a domain name with SSL. In the code I use the IP directly to connect. Ive read on issues popping if you give in the domain name.

**Comment by wedneyyuri** [comment]
SSL? Are you using HTTPS?

**Comment by kevz93** [comment]
I was. I switched back and no difference.

**Comment by nkzawa** [comment]
@kevz93 is it still an issue?

**Comment by kevz93** [comment]
Yes it is. Im running it as an Service and it doesnt work. =/

**Comment by petrorington** [comment]
@kevz93 Did you get the chance to make your listeners work?

**Comment by kevz93** [comment]
Nopes. Had to move to an alternative.

**Comment by Larsouille** [comment]
I'm facing the exact same issue where everything works except listening on my events.

**Comment by arkangeluicentric** [comment]
I have a defined a callback like so
 private Emitter.Listener onLogin = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            JSONObject data = (JSONObject) args[0];
            Log.i("Logged in", data.toString());
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(MainActivity.this,
                            "Logged in : " + args.toString(), Toast.LENGTH_LONG).show();
                    Log.i("Logged in", args.toString());
                }
            });
        }
    };


and registered it like so

 mSocket.emit("command", loginPayload);

The callback called onLogin doesn't get fired, but Socket.EVENT_CONNECT does get called. Please advise

**Comment by kevz93** [comment]
Define '.on' event name

**Comment by true-gler** [comment]
same here, got advise?

SSL, EVENT_CONNECT works, emit too, but no socket.on("something".....

**Comment by arvi** [comment]
@true-gler I am facing the same issue, it event connects, and emits too, no SSL error too... but my custom events... it's not listening. Were you able to solve this issue?

**Comment by emelyan1987** [comment]
I have same issue.

Any solution?

**Comment by PreetiTeks** [comment]
Any Solution????
connect, emit working but on listener not working.

**Comment by jay007minz** [comment]
I am facing the issue of listeners not working after reconnecting. Connect listener is only working but other listeners unable to listen sometimes.
 I am using 'io.socket:socket.io-client:1.0.0' in my gradle.
Please provide a solution to this issue.

**Comment by araratm** [comment]
Do you have any solutions?
I am facing the same problem.
socket.on(... doesn't work

**Comment by alanweing** [comment]
I'm in the same boat here.
Manager.EVENT_TRANSPORT, Manager.ERROR, Socket.EVENT_CONNECT_ERROR and Socket.EVENT_ERROR are not being called and I don't know what else to do.
Using "io.socket:socket.io-client:1.0.0".

**Comment by muhrifqii** [comment]
I stopped here, same problem like you all..

SSL, EVENT_CONNECT works, emit works too. Except socket.on("my-event",.....

**Comment by chenguozhi** [comment]
I also encountered the same problem. The callback of my registered event was not executed. I used it like the emit emitted by him. Can anyone help me?

**Comment by chenguozhi** [comment]
我遇到同样的问题，你解决了吗
I have the same problem, have you solved it?

I have a defined a callback like so
private Emitter.Listener onLogin = new Emitter.Listener() {
@override
public void call(final Object... args) {
JSONObject data = (JSONObject) args[0];
Log.i("Logged in", data.toString());
runOnUiThread(new Runnable() {
@override
public void run() {
Toast.makeText(MainActivity.this,
"Logged in : " + args.toString(), Toast.LENGTH_LONG).show();
Log.i("Logged in", args.toString());
}
});
}
};

and registered it like so

mSocket.emit("command", loginPayload);

The callback called onLogin doesn't get fired, but Socket.EVENT_CONNECT does get called. Please advise

**Comment by erlangp** [comment]
not working too

**Comment by venkat125** [comment]
Does anybody got solution for this Emitter.Listener not getting triggered. Only the Socket.EVENT_CONNECT listener is triggering

**Comment by maf1a** [comment]
+1 this is terrible. Did anyone find a solution?

**Comment by kevz93** [comment]
Cant believe its still an issue. I had migrated to custom methods long
back. But if someone is down for guiding me. I would like to see this fixed
with a pull request. Anyone ?

**Comment by uzairamer** [comment]
Having the same problem.

**Comment by erlangp** [comment]
anyone try using https://github.com/socketio/engine.io-client-java ?
is that repo have same function as this repo?

**Comment by msedek** [comment]
same boat here.. it works sometimes and sometimes it does not.. very inconvenient as in this state this can not be implemented for production

**Comment by awsp** [comment]
+1
Got exactly the same problem. 
No error message is shown.

**Comment by nisiode** [comment]
+1
Same for me

**Comment by eugenedw** [comment]
+1
Still not working for me, however it worked in the past.

**Comment by terminatorvishal** [comment]
Try This if you are using https server

//Dependencies: 
 implementation('io.socket:socket.io-client:1.0.0') {
        exclude group: 'org.json', module: 'json'
    }
//Code: 
**try {

            String socketUrl = "Your URL";
            HostnameVerifier hostnameVerifier = new HostnameVerifier() {
                @Override
                public boolean verify(String hostname, SSLSession session) {
                    return true;
                }
            };
            TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
                @Override
                public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) {

                }

                @Override
                public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {

                }

                @Override
                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return new java.security.cert.X509Certificate[0];
                }
            }};
            X509TrustManager trustManager = (X509TrustManager) trustAllCerts[0];

            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, trustAllCerts, null);
            SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();

            OkHttpClient okHttpClient = new OkHttpClient.Builder()
                    .hostnameVerifier(hostnameVerifier)
                    .sslSocketFactory(sslSocketFactory, trustManager)
                    .build();

            IO.Options opts = new IO.Options();
            opts.callFactory = okHttpClient;
            opts.webSocketFactory = okHttpClient;
            mSocket = IO.socket(socketUrl, opts);
            mSocket.on(Socket.EVENT_CONNECT, onConnect);
            mSocket.on(Socket.EVENT_DISCONNECT, onDisconnect);
            mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
            mSocket.on(Socket.EVENT_CONNECT_TIMEOUT, onConnectError);
            mSocket.on("new message", onNewMessage);
            //Other Methods
            mSocket.connect();
        } catch (URISyntaxException | NoSuchAlgorithmException | KeyManagementException e) {
            throw new RuntimeException(e);
        }**

**Comment by eugenedw** [comment]
Thanks for the idea. Tried it and doesn't work. Further debugging shows that the connection is timing out. 

Exact underlying message: "xhr poll error"

One thing I'm investigating with my configuration pertains to redirects and proxies. My socket.io server sits behind an Apache load balancer using a reverse proxy configuration where the SSL certs for virtual hosts are centrally managed. When I'd tried enabling the port from the internal server to work directly over http (instead of https), the ping-pong occurs without issue.

**Comment by roundsmapp** [comment]
Also having the very same problem as everyone else. Emit works fine, but callback listener doesn't.

I've tried with both ```io.socket:socket.io-client:1.0.0``` and ```com.github.nkzawa:socket.io-client:0.5.2```.

More than 3 yrs since this issue was open and the problem still persists. Very frustrating!

**Comment by RunziiMo** [comment]
I just found my solution by debugging the library, I just found if my socket.io server endpoint is not set to addresss:port, like `http://www.xxx.com/xxx/socket.io`, and I passed the url into IO like this `IO.socket(serverUrl, opts)`, it would just give me and default namespace called xxx/socket.io, then shit happened!!!!!, just FYI

**Comment by elvus** [comment]
Any ideas?

**Comment by nhphung216** [comment]
10.21.2019 still problems. Any ideas?

**Comment by yachash1594** [comment]
still a problem:(

**Comment by clemsciences** [comment]
I think I know the issue. It's because of Android itself. it closes sockets when it enters doze mode: https://developer.android.com/training/monitoring-device-state/doze-standby.

**Comment by MonsieurPetion** [comment]
any alternative??

**Comment by clemsciences** [comment]
An alternative that might work is to have a foreground service which maintains a visible notification so that Android does not kill it.

**Comment by dnzmsc** [comment]
Same problem. Any solution?

**Comment by rmirabelle** [comment]
All support for socket.io on Android appears completely dead, which is quite frustrating. The Android socket.io client(s) are MANY years old and have no new activity.  After reading through this thread, it appears no one is listening here either.

I'm having the exact issue everyone else is:

* Android socket.io client (com.github.nkzawa:socket.io-client:0.6.0) connects to Node socket.io server
* socket server shows client connected
* client emits ANY event
* socket server hears nothing, no error, no output of any kind

The problem appears to be related to Node socket.io server on **Raspberry Pi**

The EXACT same socket server, running on Node on Windows, works perfectly.  Android is able to connect as a client and emit.  The server shows client connected AND hears the emit events from Android.

Summary:

* Socket server (Windows or Pi) can hear browser clients perfectly from anywhere
* Windows socket server can hear Android
* Raspberry Pi socket server cannot hear Android


Overlords of socket.io - please help

**Comment by awsp** [comment]
@MonsieurPetion
> any alternative??

I ended up using the `sockjs-client` (client) and SockJS w/ STOMP support (server) as Spring Boot's `spring-websocket` and `spring-messaging` libraries use them.

**Comment by rmirabelle** [comment]
Update: My problem was NOT, in fact, the Android `socket.io` client. 

Apparently, I was instantiating the `socket.io` client incorrectly in Android - PERFECTLY incorrectly, such that `emit`s would work when connecting to server on Windows, but fail when connecting to the identical server hosted on a Raspberry Pi.  Hows that for strange?  

Anyway, the problem arose from instantiating the socket connection in the wrong way/place.  My goal was to connect to the socket server on app startup only, and also make the socket available for use in various `ViewModel`s.  The interaction with `Application` lifecycle and `ViewModel` scope was causing the problem. 

If you're having problems with `emit`s not working, double check and try simplifying your instantiation logic.  Test your connection and `emit`s directly from within a single `Activity` for simplicity and testing purposes.  You may be able to fix things up.

My solution is evolving and has been quite challenging to get right, so I'll be sure to publish an article on my use of `socket.io` as soon as time permits.

**Comment by IlyaDiallo** [comment]
> My solution is evolving and has been quite challenging to get right, so I'll be sure to publish an article on my use of socket.io as soon as time permits.

That would be great. The current documentation is very sparse.

**Comment by venkat125** [comment]
> 
> 
> Does anybody got solution for this Emitter.Listener not getting triggered?
> For me, only the **Socket.EVENT_CONNECT** listener is triggering

Sorry, for late mentioning. It got resolved since there were issue in registering the connection. After which it got resolved. I u feel the same, please ensure your client got registered with the server where the socket producer is! Thanks all!

**Comment by hayuki** [comment]
Does anyone have any suggestion for this poor struggling developer who's trying to establish an SSL (HTTPS) connection and can't seem to get the **Socket.EVENT_CONNECT** event? I need to send a once-off message to the server once I connect, but `socket.isConnected()` always returns false :( 

The most frustrating thing is a colleague of mine is using the iOS version of the Socket.io library with the exact same server and it's connecting fine...

**Comment by venkat125** [comment]
> Does anybody got solution for this Emitter.Listener not getting triggered?
> For me, only the **Socket.EVENT_CONNECT** listener is triggering

It got resolved after registering with the key to join the room in server-side. Sorry for very late reply.

**Comment by sheinin** [comment]
I struggled with a similar problem for two days. It was solved by downgrading socket.io version on Node.js server to 2.3.0.

**Comment by Rajaotix** [comment]
Same problem with socket.io version 2.3.0 :(

**Comment by erversteeg** [comment]
There appears to be an inconsistency in the Android guide on Socket.io's website [https://socket.io/blog/native-socket-io-and-android/](url). It says to add a dependency to your Android project that's actually a fork of the socket.io java client.

`implementation 'com.github.nkzawa:socket.io-client:0.6.0'`

This was giving me several issues similar to what others are describing here because the code is out of date.

Make sure you are using the most up-to-date version of the **main** socket-io-client-java implementation in your build.gradle.

For me it fixed all the issues I was having when trying to connect to a webserver that's running an up-to-date version of python-socketio.

```
implementation ('io.socket:socket.io-client:2.0.0') {
    // excluding org.json which is provided by Android
    exclude group: 'org.json', module: 'json'
}
```

**Comment by darrachequesne** [comment]
I have updated the example here: https://socket.io/blog/native-socket-io-and-android/

This issue should be fixed now. Please reopen if that's not the case.

Documentation: https://socketio.github.io/socket.io-client-java/installation.html

**Comment by antonio-gob** [comment]
not working with https

**Comment by antonio-gob** [comment]
with io.socket:socket.io-client:2.0.0 is not working, but it works with io.socket:socket.io-client:0.8.3

**Comment by sovaz1997** [comment]
I have same problem with last NestJS (Socket io v2.*) + socket.io-client-java v1.0.1

**Comment by Augustin0** [comment]
Uso el la funcion on para escuchar cuando se cnecta al servidor  sinembargo no lo puedo utilizar para escuchar los eventos que emito desde el servidor

**Comment by bhavin-qfonapp** [comment]
I'm also facing same error

**Comment by talhakhange** [comment]
I am connecting the socket io successfully and also listener event triggered get the response on first emit but when i emit another object onNewMessage not triggered,at server side socket successfully responded but onNewMessage not triggered.

`class MainActivity : AppCompatActivity() { var mSocket: Socket? = null var url: String = "https://brainbehind.co:1000"

var button: Button? = null

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
    val opts = IO.Options()
    opts.transports = arrayOf(WebSocket.NAME)
    mSocket = IO.socket(url, opts)

   //listener event to get response from the server
    mSocket?.on("reply_from_bot", onNewMessage)


    mSocket?.connect()


    //First emit to connect with the server
    val obj = JSONObject()
    obj.put("room", System.currentTimeMillis())
    obj.put("chatfrom", "2")
    obj.put("message", "start")
    obj.put("clientid", 2)
    obj.put("botid", 2)

    mSocket?.emit("connect_client_to_bot", obj)


}

//This is the listener to collect the response, it is triggered and print the response first time but when i emit mSocket?.emit("send_msg_to_bot", obj) , it is not triggered, but when i see the server side socket response successfully triggered but i am not able to listen in this event, also tried to make another event but does not work for me also private val onNewMessage = Emitter.Listener { args -> runOnUiThread(Runnable {

        val data = args[1] as JSONObject
        Log.d("TAG", data.toString())

        // Emit another object 
        val obj = JSONObject()
        obj.put("room", System.currentTimeMillis())
        obj.put("chatfrom", "2")
        obj.put("message", "Get HealthAssist")
        obj.put("clientid", 2)
        obj.put("botid", 2)
        obj.put("step", "1")
        mSocket?.emit("send_msg_to_bot", obj)
    })
}

onNewMessage event triggered correctly after this mSocket?.emit("connect_client_to_bot", obj) but not triggered after this  mSocket?.emit("send_msg_to_bot", obj) even server gives response correctly.stuck in this from last weak, also created a new socket.on() event but this was also not worked.

**Comment by talhakhange** [comment]
I am connecting the socket io successfully and also listener event triggered get the response on first emit but when i emit another object onNewMessage not triggered,at server side socket successfully responded but onNewMessage not triggered.

`class MainActivity : AppCompatActivity() { var mSocket: Socket? = null var url: String = "https://xxxxx:1000"

var button: Button? = null

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
    val opts = IO.Options()
    opts.transports = arrayOf(WebSocket.NAME)
    mSocket = IO.socket(url, opts)

   //listener event to get response from the server
    mSocket?.on("reply_from_bot", onNewMessage)


    mSocket?.connect()


    //First emit to connect with the server
    val obj = JSONObject()
    obj.put("room", System.currentTimeMillis())
    obj.put("chatfrom", "2")
    obj.put("message", "start")
    obj.put("clientid", 2)
    obj.put("botid", 2)

    mSocket?.emit("connect_client_to_bot", obj)


}

//This is the listener to collect the response, it is triggered and print the response first time but when i emit mSocket?.emit("send_msg_to_bot", obj) , it is not triggered, but when i see the server side socket response successfully triggered but i am not able to listen in this event, also tried to make another event but does not work for me also private val onNewMessage = Emitter.Listener { args -> runOnUiThread(Runnable {

        val data = args[1] as JSONObject
        Log.d("TAG", data.toString())

        // Emit another object 
        val obj = JSONObject()
        obj.put("room", System.currentTimeMillis())
        obj.put("chatfrom", "2")
        obj.put("message", "Get HealthAssist")
        obj.put("clientid", 2)
        obj.put("botid", 2)
        obj.put("step", "1")
        mSocket?.emit("send_msg_to_bot", obj)
    })
}

onNewMessage event triggered correctly after this mSocket?.emit("connect_client_to_bot", obj) but not triggered after this  mSocket?.emit("send_msg_to_bot", obj) even server gives response correctly.stuck in this from last weak, also created a new socket.on() event but this was also not worked.

**Comment by rrsaikat** [comment]
> I'am having the same issue , getting true on socketConnect , emit is also working fine but listeners are not working

Mine was working before at v1.0.0, but after upgrading node.js not working with v2.0.1 :/
It's 2024! 
Developers are still facing this issue.
