### ISSUE TITLE
how to config this lib with https address

### ISSUE THREAD

**Issue by hoang89yenthe** [socketio/socket.io-client-java#273]
Please help : 
-> socket = IO.socket("https://localhost"); not work?
how to config this lib with https

**Comment by wedneyyuri** [comment]
Your server is listening at the port 80?

**Comment by hoang89yenthe** [comment]
443

**Comment by PierrePaul** [comment]
Do you have any more specific errors?

**Comment by vimosd** [comment]
https does not work for me as well.
Same server works well with javascript clients and ios clients.
http is on port 3010
https is on port 3011
I am using commercial certificate.

**Comment by nkzawa** [comment]
Did you set `sslContext` and `hostnameVerifier` options ?

```java
// default configutations for all sockets
IO.setDefaultSSLContext(mySSLContext);
IO.setDefaultHostnameVerifier(myHostnameVerifier);

// set as an option
opts = new IO.Options();
opts.sslContext = mySSLContext;
opts.hostnameVerifier = myHostnameVerifier;
socket = IO.socket("https://localhost", opts);
```

**Comment by darrachequesne** [comment]
For future readers:

I've added some examples in the documentation: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.
