### ISSUE TITLE
Why minSdkVersion is 15?

### ISSUE THREAD

**Issue by bulatgaleev** [socketio/socket.io-client-java#278]
Why not 14 or lower? What prevents to do it lower?

**Comment by nkzawa** [comment]
Why did you think it's 15?

This library doesn't have a min sdk version of Android. I'd like to support as many versions as possible.
But it depends on library dependencies though.

**Comment by liebeu96** [comment]
OkHttp supports Android 2.3 and above..

**Comment by localhostEU** [comment]
Yep, should be 10.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
