### ISSUE TITLE
Cant get it working

### ISSUE THREAD

**Issue by vekexasia** [socketio/socket.io-client-java#279]
I tried several IO.Options to try to connect to a [wscat](https://www.npmjs.com/package/wscat) server within the same network.

I also used tcpdump to check that some tcp packets were sent to the server and I can confirm something is going on. 

Btw I always get Socket.EVENT_CONNECT_ERROR. How can I debug this?

**Comment by nkzawa** [comment]
I think `wscat` is not a server? And basically, socket.io-client can't connect to a websocket server, since they are different protocols.

**Comment by vekexasia** [comment]
@nkzawa you're right. I misread "socket.io" server in the wscat documentation. It's a websocket server...
