### ISSUE TITLE
Ability to query socket status?

### ISSUE THREAD

**Issue by luzianscherrer** [socketio/socket.io-client-java#282]
It would be nice if there was a function that would allow me to query the socket status (connected, connecting, disconnected, etc.). I currently have to implement that on my own based on the events, right?

**Comment by jvtrigueros** [comment]
Save for `connecting`, you can check whether a socket is connected or not using `io.socket.client.Socket#connected`

**Comment by luzianscherrer** [comment]
Cool thanks!

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socketio.github.io/socket.io-client-java/socket_instance.html#Socket.23connected
