### ISSUE TITLE
Emit doesn't call the API route

### ISSUE THREAD

**Issue by anupsarode** [socketio/socket.io-client-java#284]
I have written some code on my server for a requesting socket connection to join a particular room. The problem is that I am not able to call the api from Android app to join the room.

Following is my code.

Android Code
------------------

```
   private Socket socketConnection;

   @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);

        initSockets();
    }

    private void initSockets()
    {
        IO.Options options = new IO.Options();
        options.forceNew = true;
        options.reconnection = false;

        try
        {
            socketConnection = IO.socket("https://myproject.api.com", options);
        }
        catch (URISyntaxException e)
        {
            throw new RuntimeException(e);
        }

        socketConnection.on("data", onDataReceived);
        socketConnection.connect();


        // Join a room
        JSONArray arr = new JSONArray();
        JSONObject obj = new JSONObject();

        String url = "https://myproject.api.com/myroom";
        try
        {
            obj.put("url", url);
            obj.put("method", "get");
        }
        catch (JSONException e)
        {
            Log.e(TAG, "Unexpected JSON exception", e);
        }

        arr.put(obj);
        socketConnection.emit("get", arr, new Ack()
        {
            @Override
            public void call(Object... args)
            {
                JSONObject data = (JSONObject) args[0];

                Log.d(TAG, "Received - " + data);
            }
        });
    }

    private Emitter.Listener onDataReceived = new Emitter.Listener()
    {
        @Override
        public void call(Object... args)
        {
            JSONObject data = (JSONObject) args[0];

            Log.d("Received Data", data);
        }
    };

```

Backend Code (Sails Js) - MyRoomController.js
----------------------------------------------------------------

```

// Here lies the problem. This method is never called through Android app emit call
myRoom: function(req, res) 
{
  
  console.log("URL Called");
  
  if (!req.isSocket) 
  {
    return res.badRequest();
  }

  var roomName = "myRoom";
  sails.sockets.join(req, roomName, function(err) 
  {
    if (err) 
    {
      return res.serverError(err);
    }

    return res.json(
    {
      message: 'Subscribed to myRoom!'
    });
  });
}


// If this method is called manually using Postman url route, the android app receives the json
blast: function(req, res) 
{
    sails.sockets.blast('data', {value:1});
}

```

The error I get in the Android console is as follows
Received Data - {"message":"Failed to parse incoming socket.io request.","code":"SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ","details":"No url provided in request: [object Object]","stack":"Error (SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ):: Failed to parse incoming socket.io request.\n    at new constructor (\/app\/node_modules\/sails-hook-sockets\/standalone\/create-error-constructor.js:38:16)\n    at Errorpack.factory [as PARSE_VIRTUAL_REQ] (\/app\/node_modules\/sails-hook-sockets\/standalone\/create-error-factory.js:34:12)\n    at respondWithParseError (\/app\/node_modules\/sails-hook-sockets\/lib\/receive-incoming-sails-io-msg.js:247:29)\n    at receiveIncomingSailsIOMsg (\/app\/node_modules\/sails-hook-sockets\/lib\/receive-incoming-sails-io-msg.js:41:14)\n    at Socket.<anonymous> (\/app\/node_modules\/sails-hook-sockets\/lib\/on-connect.js:86:9)\n    at emitTwo (events.js:87:13)\n    at Socket.emit (events.js:172:7)\n    at Socket.onevent (\/app\/node_modules\/socket.io\/lib\/socket.js:335:8)\n    at Socket.onpacket (\/app\/node_modules\/socket.io\/lib\/socket.js:295:12)\n    at Client.ondecoded (\/app\/node_modules\/socket.io\/lib\/client.js:193:14)\n    at Decoder.Emitter.emit (\/app\/node_modules\/component-emitter\/index.js:134:20)\n    at Decoder.add (\/app\/node_modules\/socket.io-parser\/index.js:247:12)\n    at Client.ondata (\/app\/node_modules\/socket.io\/lib\/client.js:175:18)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Socket.onPacket (\/app\/node_modules\/engine.io\/lib\/socket.js:101:14)","status":400,"name":"Error (SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ):"}

Any help is appreciated. Thanks!

**Comment by wedneyyuri** [comment]
I also had problems to implement this code, so I created a wrapper. Take a look at [my code here](https://gist.github.com/wedneyyuri/d30fc41310bf4e608f47)

Note: Try passing `obj` in `socketConnection.emit("get", arr, new Ack() {...}`

**Comment by anupsarode** [comment]
Added the following line to my existing code

```
IO.Options options = new IO.Options();
        options.forceNew = true;
        options.reconnection = false;
        options.query = "__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=android&__sails_io_sdk_language=java"; // Added this line
```

And passed in the obj instead of arr to emit
```
socketConnection.emit("get", obj, new Ack()
```

And voila, it works. Thanks @wedneyyuri  for that note and your wrapper code.

**Comment by nkzawa** [comment]
@wedneyyuri thanks!

This shouldn't be the problem of Java client? Can we close the issue?

**Comment by anupsarode** [comment]
Sure, closing it. Thanks!

**Comment by anupsarode** [comment]
@wedneyyuri @nkzawa 

Any idea how can I pass in some headers while I call the socketConnection.emit() function to call a url?

Thanks in advance!

**Comment by wedneyyuri** [comment]
@anupsarode No, Sorry. But you can ask here: https://gitter.im/balderdashy/sails

**Comment by anupsarode** [comment]
Ok, Thanks :)
