### ISSUE TITLE
socket is connected after closing android app?

### ISSUE THREAD

**Issue by sys-samk** [socketio/socket.io-client-java#285]
hello.
thanks for great library. i'm using it.

I logged EVENT_CONNECT_ERROR and after closing app i still receive this log.
is this means socket is in a background service?

**Comment by nkzawa** [comment]
I don't know the details but Closing sockets explicitly on app close should solve the problem.

**Comment by wedneyyuri** [comment]
@sys-samk How are you closing the app? Probably your problem is related to your application lifecycle.

**Comment by sys-samk** [comment]
@nkzawa @wedneyyuri 
thanks
