### ISSUE TITLE
Exception on server disconnect via disconnect(true)

### ISSUE THREAD

**Issue by tormozzg** [socketio/socket.io-client-java#287]
Hi.
When nodejs server  disconnect client via `socket.disconnect(true)` receive error:

```
java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.ws.RealWebSocket$1$2@b41c0738 rejected from java.util.concurrent.ThreadPoolExecutor@b3e86460[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1967)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:782)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1303)
    at okhttp3.internal.ws.RealWebSocket$1.onClose(RealWebSocket.java:82)
    at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:220)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
    at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
    at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
    at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
    at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
```

server version - **1.4.5**
client version - **0.7.0 / 0.6.0**

This error does not occur on 1.3.5 version of the server.

**Comment by PuKoren** [comment]
+1, not sure why this happen

**Comment by joshimohit** [comment]
+1 Getting this on android Lollipop (5.0)

**Comment by florianmorel** [comment]
+1, I also get this error on multiple Android devices.

**Comment by Jacky-Max** [comment]
i also get this error many time, have any solutions for this.

**Comment by regisdaniel** [comment]
I´m getting this error too. Any workaround or solution?!

**Comment by PuKoren** [comment]
We have now around 2k crashes / day. Any info on this?

@tormozzg do you disconnect manually or is it just the ping timeout that is reached?

**Comment by uNight** [comment]
Facing same issue. Android v.4.4.2

**Comment by PiotrWpl** [comment]
+1

**Comment by PiotrWpl** [comment]
There is issue for that in OkHTTP repository -> https://github.com/square/okhttp/issues/2455
Version 3.3.0 should fix this bug.

**Comment by xuduo** [comment]
using okhttp 3.4.1.
still have the problem

**Comment by dave-r12** [comment]
I think I was able to chase this down: there is a race condition in the client when tearing down a connection. 

> If you call disconnect(true) from the server, it will send a data frame, then a close frame. When the client processes the data frame, they appear to encode that the connection should be closed, and spawn an async task that turns around and calls WebSocket#close(). If that async task happens to execute just prior to processing the close frame, then this exception is thrown (because they close the socket, then try to write to it which shuts down the executor.)

There is a subtle issue in OkHttp WebSocket client whereby if an exception happens in the WebSocket writer, it shuts down the executor. The socket.io client library is triggering this because it's closing the socket prior to writing to it.

I opened this pull request, which fixes the issue for me locally: https://github.com/socketio/engine.io-client-java/pull/61

I think we'll also make a change to OkHttp so the writer doesn't close the executor upon an IOException.

I guess another question is, why not let OkHttp close the WebSocket for you? When the server sends a close frame, OkHttp WebSocket implementation will do the right thing, and respond with a close frame.

**Comment by heqingbao** [comment]
+1

**Comment by rajeefmk** [comment]
How does one get the attention of socket.io team and possibly get a milestone on this issue ?

**Comment by xuduo** [comment]
https://github.com/square/okhttp/issues/2455
This is a okhttp issue on milestone 3.6

**Comment by rajeefmk** [comment]
@xuduo But from the discussion at square/okhttp#2455, my understanding was its a socket.io issue ?

**Comment by PiotrWpl** [comment]
There is also engine-io pull request about this issue -> https://github.com/socketio/engine.io-client-java/pull/61

**Comment by rajeefmk** [comment]
@PiotrWpl No Milestone for that too :/

**Comment by hpustudent** [comment]
+1 the same problem

**Comment by thoqbk** [comment]
@nkzawa I can work on this. Do you think we still need to fix it?

**Comment by darrachequesne** [comment]
For future readers: this should be fixed now. Please reopen if needed.
