### ISSUE TITLE
Socket not re-connecting after connection break (Only when app is in background)

### ISSUE THREAD

**Issue by Ashutosh-Tripathy** [socketio/socket.io-client-java#288]
I have created an android application using socket-io (0.7.0) and node server.

Case 1: There is no problem when app is active (After connection break it automatically reconnect). Case 2: When app is in background it is working fine till there is connection break, If there is connection break it is not attempting to reconnect and hence not listening to server emitted event.

http://stackoverflow.com/questions/35688034/socket-io-not-re-connecting-after-connection-break-only-when-app-is-in-backgrou

**Comment by nkzawa** [comment]
I think it's the same issue with https://github.com/socketio/socket.io-client-java/issues/123.

Unfortunately, app developers have to control connections if it's in background.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
