### ISSUE TITLE
send and receive stream in android

### ISSUE THREAD

**Issue by sys-samk** [socketio/socket.io-client-java#29]
Hi
my client is android.and i want to send image to server and vice versa.
do i need to use socket.io-stream library in server side?

**Comment by addonajay** [comment]
Can i send any object? Lets say, if i want to pass any file then i just need to pass file object same as we are passing FileBody in MultiPartEntity in android.

```
File fileObj = new File(path);
socket.emit("file", fileObj);
```

```
socket.on("file", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    File recFile = (File) args[0];
  }
});
```

**Comment by bradley101** [comment]
Its a late comment but its still open!.
Get byte[] from the File object and try sending it over the socket?

**Comment by maelfosso** [comment]
@bradley101 is it possible to divide the large file in many part before sending one by one ?
