### ISSUE TITLE
Unable to connect socket.io using socket.io client, engine.io-client & Java-Websocket.

### ISSUE THREAD

**Issue by chitranshmathur01** [socketio/socket.io-client-java#290]
Hi,

@nkzawa & @aizhilong : I'm using the same way as you've already described. But still I'm not sure that my socket is connecting or not. How to check socket is connected ? I'm getting "OPENING" readyState in my debugging using your WebRTC API.

My code snippet:

```
MessageHandler messageHandler = new MessageHandler();
try {
            socket = IO.socket(host);
            socket.connect();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        socket.on("new-channel", messageHandler.newChannel);

// This is my MessageHandler class

private class MessageHandler {
private Emitter.Listener newChannel = new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.i("newChannel", "newChannel: " + args[0]);
            }
        };
}
```
Now I'm not getting socket status inside newChannel listner.

**Comment by nkzawa** [comment]
Please use `Socket.EVENT_CONNECT` event and `socket.connected()` method.

See also: http://socketio.github.io/socket.io-client-java/apidocs/

**Comment by chitranshmathur01** [comment]
@nkzawa : Thanks for your valuable feedback. I've got the socketio connection. :+1:
