### ISSUE TITLE
Chat History maintenance in app 

### ISSUE THREAD

**Issue by LokiRathod** [socketio/socket.io-client-java#292]
I am using this library to send media using socket.io with node.js in my android app chat module.
Can any one help me the flow for maintaining the Chat History in my app.

**Comment by hanspeter1** [comment]
Just use some of [this](http://developer.android.com/guide/topics/data/data-storage.html) Android build in databases or a Server side database for your application server

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
