### ISSUE TITLE
Room support (join & leave)

### ISSUE THREAD

**Issue by librorum** [socketio/socket.io-client-java#296]
This url describes room feature in javascript.

http://socket.io/docs/rooms-and-namespaces/

Do you have a plan to support these room features?

**Comment by nevi-me** [comment]
I thought the implementation detail is in the server. You can't join or leave a room from the client, instead you can emit an event to join or leave. In the case of joining you should perform some logic in the server to validate that a user can join a room (e.g. if it's a private room).

**Comment by nkzawa** [comment]
yep, that's how you join a room from client, thanks @nevi-me !

**Comment by mucyomiller** [comment]
@nkzawa  ok now i learned that not all features are available on client to join/leave you must implement you own logic on server but then why haven't told us in android client docs?
