### ISSUE TITLE
Send String[] array to the server

### ISSUE THREAD

**Issue by EpsilonOrionis** [socketio/socket.io-client-java#299]
I'm trying to send a String[] array to the server, but when I try to get an element from the data received by the client, I get a string. Let me show you:
Data received:  ["sadadasda", "fgdfdfg", "fsgfdgfdfd"]
var first_element = data[0]
I get: " not "sadadasda"

How can I resolve this problem? Thanks in advance

**Comment by hanspeter1** [comment]
For this job i'm using a "JSONArray"-Object

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
