### ISSUE TITLE
OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again

### ISSUE THREAD

**Issue by alexvimodev** [socketio/socket.io-client-java#300]
I am getting OutOfMemory error in:
Android: 4.4.2
Model: SM-N7505

Name: java.lang.OutOfMemoryError
Reason: pthread_create (stack size 16384 bytes) failed: Try again

Crashed Thread
0   java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
1   at java.lang.VMThread.create(Native Method)
2   at java.lang.Thread.start(Thread.java:1029)
3   at io.socket.engineio.client.transports.PollingXHR$Request.create(SourceFile:199)
4   at io.socket.engineio.client.transports.PollingXHR.doWrite(SourceFile:94)
5   at io.socket.engineio.client.transports.Polling$5.call(SourceFile:189)
6   at io.socket.engineio.client.transports.Polling$5.call(SourceFile:186)
7   at io.socket.engineio.parser.Parser.encodePayload(SourceFile:149)
8   at io.socket.engineio.client.transports.Polling.write(SourceFile:186)
9   at io.socket.engineio.client.transports.Polling$3.call(SourceFile:157)
10  at io.socket.engineio.client.transports.Polling.doClose(SourceFile:166)
11  at io.socket.engineio.client.Transport$2.run(SourceFile:87)
12  at io.socket.thread.EventThread.exec(SourceFile:50)
13  at io.socket.engineio.client.Transport.close(SourceFile:83)
14  at io.socket.engineio.client.Socket.onClose(SourceFile:793)
15  at io.socket.engineio.client.Socket.onError(SourceFile:766)
16  at io.socket.engineio.client.Socket.access$800(SourceFile:30)
17  at io.socket.engineio.client.Socket$4.call(SourceFile:304)
18  at io.socket.emitter.Emitter.emit(SourceFile:117)
19  at io.socket.engineio.client.Transport.onError(SourceFile:65)
20  at io.socket.engineio.client.transports.PollingXHR.access$100(SourceFile:18)
21  at io.socket.engineio.client.transports.PollingXHR$6$1.run(SourceFile:126)
22  at io.socket.thread.EventThread$2.run(SourceFile:75)
23  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
24  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
25  at java.lang.Thread.run(Thread.java:841)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
