### ISSUE TITLE
Socket.onevent event value on args always on index 1 [Bug]

### ISSUE THREAD

**Issue by raizal** [socketio/socket.io-client-java#303]
Whenever I got an event from server, the args length is 2, but  in Socket.onevent, it's always take the first index(index = 0). but index 0  is always null and the event value always on index 1.
I already fix it in my project by clonning it and rebuild it myself
Is there anyone who got the same error as mine?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
