### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by wpq2014** [socketio/socket.io-client-java#308]
How to post https? Could anyone give me a demo? Thank you!

**Comment by ZhaoYaFei1** [comment]
How to post https? Could anyone give me a demo? Thank you!

**Comment by wpq2014** [comment]
https://github.com/jonathanve/socket-io-android/blob/master/client-snippet.java

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
