### ISSUE TITLE
Integrating socket.io-client-java lib into another lib.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-java#310]
Hi,

We are trying to integrate socket.io-client-java lib into our existing library which will be used by other developers to integrate into their apps.

Is such a scenario considered when you develop socket.io-client-java lib? Is there anything special (compared to integrating into an app) we need to consider?

Thanks!

**Comment by darrachequesne** [comment]
For future readers:

There shouldn't be any issue when integrating the library in another lib :+1: 

Please reopen if needed.
