### ISSUE TITLE
Sending data through connection

### ISSUE THREAD

**Issue by keysim** [socketio/socket.io-client-java#314]
Hi,
I'm doing a project with socket.io, it's great ! I was wondering if we can send data through connection like javascript do : 
var socket = io('http://example.c9users.io:8080', {query: "login=foo"});
?
Is it possible to do it with Swift (Apple) too ?

Thank you !

**Comment by wedneyyuri** [comment]
@keysim This project is intended for Java / Android. See https://github.com/socketio/socket.io-client-swift instead.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
