### ISSUE TITLE
Transport error

### ISSUE THREAD

**Issue by mohsin1199** [socketio/socket.io-client-java#316]
I am connecting from android to socket.io https server but it is giving 'transport error'.The connection to the server from javascript is fine. here is my java code .can any one hep me thanks in advance
 SSLContext sc = SSLContext.getInstance("TLS");
           sc.init(null, trustAllCerts, new SecureRandom());
            IO.setDefaultSSLContext(sc);
            HttpsURLConnection.setDefaultHostnameVerifier(new RelaxedHostNameVerifier());

```
        IO.Options opts = new IO.Options();
        opts.forceNew = true;
        opts.reconnection = false;
        opts.secure = true;
        opts.sslContext = sc;

        mSocket = IO.socket('https://server.ip:port',opts);
```

 public TrustManager[] trustAllCerts = new TrustManager[] { new X509TrustManager() {
        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
            return new java.security.cert.X509Certificate[] {};
        }
        public void checkClientTrusted(X509Certificate[] chain,
                                       String authType) throws CertificateException {
        }

```
    public void checkServerTrusted(X509Certificate[] chain,
                                   String authType) throws CertificateException {
    }
} };

public static class RelaxedHostNameVerifier implements HostnameVerifier {
    public boolean verify(String hostname, SSLSession session) {
        return true;
    }
}
```

**Comment by mayank250004** [comment]
did you got any solution?

**Comment by CAMOBAP795** [comment]
I also noticed that this issue sometimes happens for me

**Comment by khaleeljageer** [comment]
`IO.Options opts = new IO.Options();`
`opts.forceNew = true;`
`opts.reconnection = false;`
`opts.secure = true;`
`opts.sslContext = sc;`

add this line with your options object
`options.transports = new String[]{WebSocket.NAME};`

This may fix the issue...

**Comment by darrachequesne** [comment]
For future readers:

I've added some example in the documentation: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.
