### ISSUE TITLE
How do I stop listening for an event

### ISSUE THREAD

**Issue by Mouradif** [socketio/socket.io-client-java#317]
Hi,

The README.md file says that

> This library supports all of the features the JS client does, including events, options and upgrading transport. Android is fully supported.

But I wasn't able to find the `removeListener()` method from the socket object. How can I remove a listener ?

**Comment by wedneyyuri** [comment]
@Mouradif You have the `off` method.

```
socket.on("YOUR_EVENT", new Emitter.Listener() {

  @Override
  public void call(Object... args) {
    socket.emit("foo", "hi");
    socket.disconnect();
  }

}).off("YOUR_EVENT");
```

**Comment by nkzawa** [comment]
Yep, thanks @wedneyyuri !
