### ISSUE TITLE
after  my  android  socket.io reconnect  ，can not  send message，why?

### ISSUE THREAD

**Issue by lisnstatic** [socketio/socket.io-client-java#319]
When my network is broken ,and then connect .  My  socket.io  will  reconnect  automatic，but  then  I  cant  send  message？

**Comment by wedneyyuri** [comment]
@lisnstatic Check the reconnection property of your socket options:

```
IO.Options opts = new IO.Options();
opts.reconnection = false;
socket = IO.socket("http://localhost", opts);
```

**Comment by lisnstatic** [comment]
@wedneyyuri  I  have  not  set  options . If  I  set  options  like  that， socket.io  will  not  do  reconnect  for  me， I  need  to  write  reconnect  bymyself？

**Comment by lisnstatic** [comment]
I have  tried  that  use socket.io's  reconnect ,  it  really  reconnected ,  but  not  the  original  socket  object  connected. I  do  not  know  if  socket.io   has  new  another  socket  object.

**Comment by wedneyyuri** [comment]
Are you calling `socket = IO.socket("http://localhost");` multiple times?

**Comment by lisnstatic** [comment]
no ， I  uesed  demo  of  socket.io  which  called  socket = IO.socket("http://localhost");  in  Application .

**Comment by charmeleon2** [comment]
@lisnstatic     Have you solved the problem? I have the same problem

**Comment by linuxbelletian** [comment]
the message will be send out ,but response message can't be emited to the listener ,it seem to be a bug of the library

**Comment by darrachequesne** [comment]
For future readers:

I wasn't able to reproduce:

```java
public class Fiddle {

    public static void main(String[] argz) throws Exception {
        IO.Options options = new IO.Options();

        Socket socket = IO.socket(URI.create("http://localhost:3000"), options);

        socket.on(Socket.EVENT_CONNECT, (__) -> {
            System.out.println("connect");

            socket.emit("ping");
        });

        socket.on(Socket.EVENT_CONNECT_ERROR, (args) -> {
            System.out.println("connect_error: " + args[0]);
        });

        socket.on(Socket.EVENT_DISCONNECT, (args) -> {
            System.out.println("disconnect due to: " + args[0]);
        });

        socket.on("pong", args -> {
            System.out.println("pong");
        });

        socket.connect();
    }
}
```

Output:

```
connect
pong
disconnect due to: transport error
connect
pong
disconnect due to: transport error
connect
pong
```

Please reopen if needed.
