### ISSUE TITLE
Not found ACK class in arguments of Emitter.Listener

### ISSUE THREAD

**Issue by sm-tester** [socketio/socket.io-client-java#323]
Hi, so I have a event like as:

`

```
    socket.on("private_message", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                if (args != null && args.length > 0) {
                    for (int i = 0; i < args.length; i++) {
                        HLog.i(TAG, "args class type : " + args[i].getClass().getName() + " pos : " + i);
                        if (args[i] instanceof Ack) {
                            Ack ack = (Ack) args[args.length - 1];
                            ack.call("OK");
                            HLog.i(TAG, "Sending OK to response >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
                            break;
                        } else if (args[i] instanceof JSONObject) {
                            JSONObject arglast = (JSONObject) args[i];
                            Log.i(TAG, "ARGS LAST JSON : " + arglast);
                        }
                    }
                }
                // doing my handle logic ....
            }
        });
```

`

but, I did not find Ack class to returning "OK" to the response of the server.

`

```
06-30 16:41:31.735 I/MySocketThread: args class type : java.lang.String pos : 0
06-30 16:41:31.736 I/MySocketThread: args class type : org.json.JSONObject pos : 1
```

`

and I printed last JSONObject argument and get following json:

`ARGS LAST JSON : {"resultClass":"java.lang.String","timeout":5}`

I don't understand why last argument not a Ack class ?
I want return answer to response by ACK by your example:

```
// ack from client to server
socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    Ack ack = (Ack) args[args.length - 1];
    ack.call();
  }
});
```

but your library works incorrect, anybody know how to fix it?

**Comment by nkzawa** [comment]
Hmm, can you post the code on server side too?

**Comment by JavaMachine** [comment]
Hello @nkzawa,

Server side is based on [Java Socket.IO Implementation](https://github.com/mrniko/netty-socketio)

and Here is the code:
`socketIOServer.addEventListener("foo", String.class, new DataListener<String>() {
            @Override
            public void onData(SocketIOClient socketIOClient, String s, AckRequest ackRequest) throws Exception {
                socketIOClient.sendEvent("foo", "someData", new AckCallback<String>(String.class, 5) {
                    @Override
                    public void onSuccess(String s) {
                        System.out.println("ACK received"+s);
                    }
                });
            }
        });`

**Comment by JavaMachine** [comment]
Ah, messed up...
Here is the code:

[pasted here](http://paste.ofcode.org/LHNsa8E8CcXaH8b3ZDLEKr)

**Comment by nkzawa** [comment]
Actually I have never tried Java server. The server code looks good to me, but I'm not sure if it's compatible with this library. The library is tested with node.js server. (https://github.com/socketio/socket.io-client-java/blob/master/src/test/java/io/socket/client/ConnectionTest.java#L83)

**Comment by JavaMachine** [comment]
IMHO this is more likely library issue. Because [Socket.io Swift Library](https://github.com/socketio/socket.io-client-swift) is compatible with [Java-Netty](https://github.com/mrniko/netty-socketio) based Socket.io server.

For now we have implemented workaround for this issue, simply by emitting "ack" to server. Server have another event for receiving client emit and every request is signed with unique identifier.

**Comment by arjun81815** [comment]
You are using old version of Socket.io jar file

**Comment by dassiorleando** [comment]
Hi @all,

Please ... something new regarding this?

**Comment by darrachequesne** [comment]
For future readers:

This appears to work fine:

```java
public class Fiddle {

    public static void main(String[] argz) throws Exception {
        IO.Options options = new IO.Options();

        Socket socket = IO.socket(URI.create("http://localhost:3000"), options);

        socket.on("test", (args) -> {
            System.out.println(args[0]); // prints 1
            System.out.println(args[1]); // prints 2
            System.out.println(args[2] instanceof Ack); // prints true

            Ack ack = (Ack) args[2];
            ack.call("3", 4);
        });

        socket.connect();
    }
}
```

JS server:

```js
io.on("connection", (socket) => {
  socket.emit("test", 1, "2", (...args) => {
    console.log(args); // prints [ '3', 4 ]
  })
});
```

Please reopen if needed.
