### ISSUE TITLE
Creating non Daemon threads

### ISSUE THREAD

**Issue by vach** [socketio/socket.io-client-java#324]
Socketio internal implementation creates a custom Thread which we cannot control if its daemon or non daemon. This is usually controlled in other libraries by providing option to user to provide their executor service... Current implementation does not provide an opportunity like that...

Either provide a way to control that, or extend deamonity from the thread that calls .connect()... like other normal threads do...

**Comment by vach** [comment]
I've added a pull request to fix this https://github.com/socketio/engine.io-client-java/pull/60

**Comment by nkzawa** [comment]
Closed via socketio/engine.io-client-java#60
