### ISSUE TITLE
Socket connect callback  socket.id() returns null

### ISSUE THREAD

**Issue by KoTius** [socketio/socket.io-client-java#325]
What do we have:

Static initialization in Application class:

> {
>         try {
>             mSocket = IO.socket(Configs.SERVER_URL);
>         } catch (URISyntaxException e) {
>             throw new RuntimeException(e);
>         }
>     }

Then, in activity we do:

> mSocket.on(Socket.EVENT_CONNECT, onConnected);
> mSocket.connect()

in onConnected listener we try to get id with mSocket.id as follows:

> ```
> private Emitter.Listener onConnected = new Emitter.Listener() {
>     @Override
>     public void call(Object... args) {
>         Log.d(BaseActivity.LOG_TAG, "onConnected ID = " + mSocket.id());
>     }
> ```

At first application launch we will get ID, everything looks fine.

Then we exit activity and call in onDestroy():

> mSocket.disconnect()

Then we exit app.
Then we open app again and we will get "onConnected ID = null".
onConnected will work properly, but id is bugged.

At the server side it looks like there is no action disconnection, and after we open app again - server got id, but app doesn't.

I suppose the problem comes from socket cache.

I can avoid this by initialize socket in Activity's onCreate, but it's hardly a good solution.

Any tips?

**Comment by armenmargaryan** [comment]
@KoTius hi i have exact same problem. Dis you solved the issue ?

**Comment by KoTius** [comment]
@armenmargaryan hi. Nah, we stopped use it at client side.

**Comment by armenmargaryan** [comment]
@KoTius Aha ok, and can you tell what was the your alternative choice ?

**Comment by tjouin** [comment]
@KoTius I'am looking for an other client too if u can share which one you use :)

**Comment by darrachequesne** [comment]
For future readers:

I wasn't able to reproduce the issue:

```java
public class Fiddle {

    public static void main(String[] argz) throws Exception {
        IO.Options options = new IO.Options();

        Socket socket = IO.socket(URI.create("http://localhost:3000"), options);

        socket.on(Socket.EVENT_CONNECT, (__) -> {
            System.out.println("connect " + socket.id());
        });

        socket.connect();

        for (int i = 0; i < 10; i++) {
            Thread.sleep(2000);
            socket.disconnect().connect();
        }
    }
}
```

Output:

```
connect Mm4fxNGPJt30D529AAAX
connect caU49idtMPCYLGd8AAAa
connect WZuxNDr0kaHvEz-5AAAd
connect -OVmvrNY-P_d3AFCAAAg
...
```

Please reopen if needed.
