### ISSUE TITLE
Leaving a namespace

### ISSUE THREAD

**Issue by triniwiz** [socketio/socket.io-client-java#329]
Is there a method to leave a namespace similar to the swift client `leaveNamespace()`

**Comment by nkzawa** [comment]
Is it different with disconnecting a socket of a namespace ?

**Comment by triniwiz** [comment]
well according to https://github.com/socketio/socket.io-client-swift#methods `leaveNamespace() - Causes the client to leave the nsp and go back to /`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
