### ISSUE TITLE
Web socket with port number not working

### ISSUE THREAD

**Issue by GunaseelanArumaikkannu** [socketio/socket.io-client-java#330]
```
 protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     setContentView(R.layout.activity_main);
     try {
         mSocket = IO.socket("http://chat.socket.io");
         mSocket2 = IO.socket("http://v2.cloudtimer.nl:3000");
     } catch (URISyntaxException e) {
         e.printStackTrace();
     }
     mSocket.connect();
     mSocket2.connect();

     CountDownTimer timer = new CountDownTimer(100000,1000) {
         @Override
         public void onTick(long l) {
             Log.v(MainActivity.class.getSimpleName(), "mSocket.connected() : " + mSocket.connected()+", mSocket2.connected() : " + mSocket2.connected());
         }

         @Override
         public void onFinish() {

         }
     };
     timer.start();
 }
```

And I am getting the following log message.
`mSocket.connected() : true, mSocket2.connected() : false`

Is there anyone to help me?

**Comment by samueldaviddelacruz** [comment]
im having the same issue, have a small node server running on port 3000 cant connect to it :( sad times.

**Comment by Fideas** [comment]
Have you tried to set the port in your options and then use the `connect(String, Options)` method?
Something like:

     IO.Options opts = new IO.Options();
     opts.port = 3000;
     socket = IO.socket("http://v2.cloudtimer.nl",opts);

**Comment by arjun81815** [comment]
change URL to its IP address. 

Like  http://v2.cloudtimer.nl  to  what its ip (44.25.111.23)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
