### ISSUE TITLE
Is the repo being mantained?

### ISSUE THREAD

**Issue by emanuelet** [socketio/socket.io-client-java#340]
Hi, 
I'm the Android Lead Developer at Amity, and I wanted to know if the repository is getting maintained as the last commit is from 3 months ago.

I'm relying pretty heavily on this library 

If necessary I'm happy to become a mantainer

**Comment by hifall** [comment]
Ditto.

**Comment by nkzawa** [comment]
Yep, released v0.8.0. PRs are always welcome.
