### ISSUE TITLE
how to send an ack from android to server

### ISSUE THREAD

**Issue by daicoolb** [socketio/socket.io-client-java#341]
I have see these code in your github:

**// ack from client to server
socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    Ack ack = (Ack) args[args.length - 1];
    ack.call();
  }
});**

but i want to send an ack with "OK" to server  ,how can i do it ?

**Comment by mohameddahroug** [comment]
in Android client:
ack.call("answer ok from client");

in Server:
socket.emit('action', 'message', function (answer) {console.log(tag,'answer '+answer);});

**Comment by darrachequesne** [comment]
For future readers:

```java
socket.on("hello", args -> {
    System.out.println(args[0]); // "please acknowledge"
    if (args.length > 1 && args[1] instanceof Ack) {
        ((Ack) args[1]).call("hi!");
    }
});
```

Reference: https://socketio.github.io/socket.io-client-java/emitting_events.html#From_server_to_client
