### ISSUE TITLE
whats the latest android release ?

### ISSUE THREAD

**Issue by meetmkjangid** [socketio/socket.io-client-java#347]
I tried 0.8.1 but it doesn't work. Please look into it

**Comment by IlyaDiallo** [comment]
@meetmkjangid what do you mean by "it doesn't work" ...?

**Comment by meetmkjangid** [comment]
Sorry for being unclear. It doesn't sync through gradle. Bintray repo doesn't have 0.8.1. Only 0.6. Should I work with that or is 0.8.1 is to going to be rolled out for gradle users soon enough.

**Comment by jgaut** [comment]
The name of depot change after 0.6.

Do you have this following conf ?

```
compile ('io.socket:socket.io-client:0.8.1') {
  // excluding org.json which is provided by Android
  exclude group: 'org.json', module: 'json'
}
```

**Comment by meetmkjangid** [comment]
Found it. Thanks.
