### ISSUE TITLE
io.Socket.id() return null

### ISSUE THREAD

**Issue by JunfeiW** [socketio/socket.io-client-java#351]
It is weird that sid of socket.io is null, while socket is connected, and can emit message and receive message.
How can I fetch socket id of current connection

**Comment by JunfeiW** [comment]
It has been a while, any comments?

**Comment by pmesa48** [comment]
try getting the id right after you connect your socket object
String id = socket.connect().id();
that worked for me

**Comment by JunfeiW** [comment]
Please have a look at this, I tried at two place, after connect is called, and on connect event, both will return null.

![image](https://cloud.githubusercontent.com/assets/5487724/19156369/42593254-8c14-11e6-86f8-95c702100e35.png)

![image](https://cloud.githubusercontent.com/assets/5487724/19156456/83e955b4-8c14-11e6-9643-49461b34e697.png)

**Comment by JunfeiW** [comment]
and I use 0.8.1

compile('io.socket:socket.io-client:0.8.1') {

**Comment by JunfeiW** [comment]
Hello？

**Comment by pmesa48** [comment]
Did it stop working when you updated?, i am currently using 0.8.0. Try calling mSocket.connect().id() when EVENT_CONNECT has been triggered (not just mSocket.id()).

**Comment by JunfeiW** [comment]
![image](https://cloud.githubusercontent.com/assets/5487724/19396882/bde735a6-9277-11e6-8fb4-134a3170f559.png)
still doesn't work, as you can see, tried it at Socket.EVENT_CONNECT
by call mSocket.connect().id();

**Comment by JunfeiW** [comment]
Searching "id =" in Socket.java, I can just find  this.id only be set to null on call onclose function.

**Comment by varunagarwal315** [comment]
Add a log saying Log.d(TAG, mSocket.toString()). mSocket data will be a
JSON object, once you print it as a string, then check where the id is
located. Afaik, id is wrapped in another json object within mSocket.

You can then retrieve the ID with basic JSON functions such as
getJSOnobject() followed by getString().

Let me know if this works.

**Comment by JunfeiW** [comment]
@varunagarwal315  , thanks for reply, mSocket is an instance of Emitter, which hasn't implemented  toString(), so when I tried to call  mSocket.toString(), the result is "io.socket.client.Socket@21f47178", I didn't find any JSON object.  I suppose this 21f47178 is not a id.

**Comment by varunagarwal315** [comment]
I will check it out from my end in a couple of hours, but just curious,
have you been able to manually change the socket ids? I want to make a chat
app and would like each user to have a fixed socket id whenever they
connect, this socket id will be related to their username.

In nodejs, when i change the socket id by `socket.id = "customID"` upon
connection , it gets changed but I doubt this change is being reflected on
the client side (android). As a result, I cannot send a message to a
specific id. Sending a message to specific id works if I use the default
one assigned which is random.

Has anyone been able to use custom socket id with success? I am using v
0.7.0 as of now.

**Comment by varunagarwal315** [comment]
Socket mSocket = new Socket()
in the event Socket.EVENT_CONNECT , mSocket.id() is working for me in
version 0.7.0 AND 0.8.0.
I cross checked the socket id by checking it against the socket instance in
my server ( node js)

You are probably called socket.id() on a different instance than the one
which triggered the ON_CONNECT event. I suggest you use initiate a socket
instance using the singleton pattern. This will solve all your problems.

Let me know how it goes!!

**Comment by JunfeiW** [comment]
As far as I know, this socket id is generated by server side, which is used to identify socket clients connected to socket.
I need this to generate auth info for client.

**Comment by varunagarwal315** [comment]
well socket.id() is DEFINITELY working. Make sure you use a singleton
pattern while implement socket in android. Once the socket.id is generated
on server side, it gets send to the client. But If i want to override the
socket.id on server side, how to trigger the client to update it as well.

You may either be
1) not connected to the server properly
2) calling id() on a different instance than the one .connect() was called
on -(avoided by using singleton pattern)
3) Select id() and click cntrl+B on keyboard. This should take you to the
socket superclass where you will get more info on how the id() works

If you use the id for auth info, won't it be better if you could provide
some custom socket id? I need to figure this out badly!

Regards,

**Comment by JunfeiW** [comment]
I will try to push a project, which can reproduce the problem.
Thanks for reply.

**Comment by JunfeiW** [comment]
Hi, again
I pushed a project here:
https://github.com/JunfeiW/DemoSocketioID

I test it on my cell phone, with no luck.
Any help would be appreciated!

**Comment by varunagarwal315** [comment]
The issue is with your basic code. Have made several changes with comments.
Let me know if problem is solved. I would like to be the one who closes the
issue :).

It seems you did not actually initialize the socket instance properly.
Sorry had to change the target SDK, did not have it installed, but it won't
affect the code I have added.

Added a pull request. Accept it.

**Comment by JunfeiW** [comment]
Yes, it works, surely, I made something wrong, thanks for all your helps!

**Comment by JunfeiW** [comment]
Now I know why, it because I use mSocket.off().
The reason why I use this off, is caused by somet

**Comment by ajay8086** [comment]
access the soket.id from the EVENT_CONNECT 

            socket = IO.socket("http://192.168.1.129:3000");
            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {

                    String socketID = socket.id();


                }
            });
            socket.connect();
