### ISSUE TITLE
Custom socket id from android side

### ISSUE THREAD

**Issue by varunagarwal315** [socketio/socket.io-client-java#354]
In the android library, socket.id() returns the id of the socket, however, there is no method (that I found in the jar file) that lets us set the socket id.

How can I set the socket id for my communication. In the nodejs sample, setting socket.id = "customName" works allowing us to decide our own name space for the sockets. Is there such an implementation in android?

I am developing a chat app wherein I want the socket.id() of the users to be their username itself. So irrespective of when they connect, instead of getting a random id, it is fixed to their username. I plan to set the id as soon as a connection is made.

In Nodejs my code is following -

```
io.on('connection', (socket)=>{
  console.log('new connection received');
  console.log(socket.id)
  socket.id = "username"
  console.log(socket.id)

  //other methods
}
```

This changes the socket id, but io.to(id).emit('new_message', data) does not work. If i use the random id generated, then this method is working just fine.

Please advise.

**Comment by roblav96** [comment]
@varunagarwal315 You could set a socketid in the query params

**Comment by armenmargaryan** [comment]
@roblav96 can you advice with short example how with query params ?

**Comment by Bashirkhalil** [comment]
nothing usefull

**Comment by darrachequesne** [comment]
For future readers:

If the username is unique, you can use rooms on the server side:

```js
io.on("connection", (socket) => {
  socket.join(<username>);

  io.to(<username>).emit(...);
});
```

Please do not try to overwrite the socket id, as it is used internally.

Reference: https://socket.io/docs/v4/rooms/
