### ISSUE TITLE
Emit doesn't send event to the server

### ISSUE THREAD

**Issue by sergicastellsague** [socketio/socket.io-client-java#356]
As a Java client, I can connect to the server, but when performing the following code:
`socket.emit("subscribe", "driver.4.notifications");`
It doesn't work. I've traced with WIreshark and no network operation is performed.

However, if I do run this same code with the JS library, I can see the network operation being sent and server adding the new callback listener.

Any clue?

**Comment by gregschlom** [comment]
I'm having a similar issue. socket.emit works if it's being called from the main thread, but does not do anything if called from another thread

**Comment by sergicastellsague** [comment]
My issue was that I was using the wrong Socket class file.

There are two in this library.
io.socket.client.Socket
and
io.socket.engineio.client.Socket;

Both with different implementations. 
The first one is the good one.
