### ISSUE TITLE
Connection connect , dissconnect Repeating

### ISSUE THREAD

**Issue by vksBhardwaj** [socketio/socket.io-client-java#357]
Hi,

I Just implement IO.Socket and when i call it on Service ( in Background ) the connection repeating connect, disconnect and reconnect and every time after every 10 seconds and here is my make connection code : **Any Help would be appreciate**

 synchronized void makeSocketConnection() throws URISyntaxException
    {
        System.out.println("SOCKET,,,,in Make Auth Method"+socket);
        IO.Options options = new IO.Options();
        options.reconnection =true;
         options.reconnectionDelay = 100000;
        options.timeout = 1000000;
        if (socket==null)
        {
            socket = IO.socket(constant.socketUrl,options);

```
        socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

            @Override
            public void call(Object... args) {
                System.out.println("SOCKET,,,,connect event");
                callSocketJoin();
            }
        });
        socket.on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                 System.out.println("Socket,,,,, Disconnect");
            }
        });socket.on(Socket.EVENT_RECONNECT, new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            System.out.println("Socket,,,,, Reconnect");
            socket.disconnect();
            try
            {
                makeSocketConnection();
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    });
        socket.on(Socket.EVENT_CONNECT_ERROR, new Emitter.Listener() {

            @Override
            public void call(Object... args) {
                System.out.println("SOCKET,,,,connect Error" +args[0].toString());

                callSocketJoin();
            }
        });
        socket.connect();
    }
    else if (socket.connected()==false)
    {
        socket.connect();
    }
}
```

**Comment by sergicastellsague** [comment]
can you post full code? What's #callSocketJoin doing?

**Comment by sach185** [comment]
Was this ever resolved? Im having similar problems ):

**Comment by sergicastellsague** [comment]
@sach185 try to use only websocket transport (setting it client-side)

**Comment by sach185** [comment]
@sergicastellsague can you please guide me with the same? im relatively new to this.

**Comment by sergicastellsague** [comment]
this is the Java code to set force use of websocket transport:
```        
IO.Options opts = new IO.Options();
opts.transports = new String[]{"websocket"};
```

**Comment by sach185** [comment]
Did not work for me. Im getting io.socket.engineio.client.EngineIOException: websocket error

**Comment by sergicastellsague** [comment]
I'm sorry then. This was causing issues to me, and fixed them all 😢

**Comment by sach185** [comment]
I disconnect and connect back every 10 seconds ):

**Comment by vksBhardwaj** [comment]
its fixed for me
