### ISSUE TITLE
Library making lots of peristent connections with the server

### ISSUE THREAD

**Issue by eckovation** [socketio/socket.io-client-java#358]
Recently, we are facing an issue in which the app is making lots of persistent connections with the server. Something like 100 connections. Does anyone have any idea why is this happening?

We are running and connecting the socket in a very normal mode with default configuration options.

**Comment by arjun81815** [comment]
Socket.IO connects with server generally using two techniques. 
1) Long pooling
2) Sockets.

In long pooling it makes request every 2-3 seconds to the server. When current request completes it makes another request to the server

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
