### ISSUE TITLE
ClassCastException: java.lang.Integer cannot be cast to io.socket.client.Ack

### ISSUE THREAD

**Issue by TigranSarkisian** [socketio/socket.io-client-java#367]
Trying to send Acknowledgement on server as mentioned in your guides https://github.com/socketio/socket.io-client-java

// ack from client to server
socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    Ack ack = (Ack) args[args.length - 1];
    ack.call();
  }
});

args[args.length - 1] returns 345 (does not matter, returns any integer )

but crashes with ClassCastException: java.lang.Integer cannot be cast to io.socket.client.Ack

**Comment by jituijiaqiezi** [comment]
ont the server side,if i use the below code:
server.on('foo',function(data,callback)){
callback('yes');
}
it also says the callback is not a function.
Doesn't the lib handle the ack method between java-client and node.js server?
Hope someone can help me,thanks.
