### ISSUE TITLE
run on server side but not run android side

### ISSUE THREAD

**Issue by hitesh849** [socketio/socket.io-client-java#368]
this is my server code : 

var socket  = require( 'socket.io' );
var http = require('https');
var fs = require('fs');
var Client = require('node-rest-client').Client; 
var client = new Client();
var express = require('express');
var app     = express(); 
var options = { key: fs.readFileSync('/home/courier/certs/www.someurl.com.key'),cert: fs.readFileSync('/home/courier/certs/212d2ffba57898b0.crt')}; 
var server  = require('https').createServer(options);
var io      = socket.listen( server );
var port    = process.env.PORT || 3000;
server.listen(port, function () {
  console.log('Server listening at port %d', port);
});
io.on('connection', function (socket) {
  socket.on('new_count_message', function( data ) {
    io.sockets.emit( 'new_count_message', { 
    	new_count_message: data.new_count_message
    });
  });
  socket.on('update_count_message', function( data ) {
    io.sockets.emit( 'update_count_message', {
    	update_count_message: data.update_count_message 
    });
  });
  socket.on('new_message', function( data ) {
	  console.log('New Message %d', data.id);
      io.sockets.emit( 'new_message',data);
  });
  socket.on('get_history', function( channelid )
  {   
	  io.sockets.emit( 'history',channelid); 
  });
});

and i am using mSocket = IO.socket("https://myurl.com/3000") in android side but it is not connect from socket please help me..

**Comment by hitesh849** [comment]
i am using mSocket = IO.socket("https://myurl.com:3000") in android side but it is not connect from socket please help me..

**Comment by rjoniuqa** [comment]
Are you using a self signed certificate?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
