### ISSUE TITLE
react native and socket.io-client 0.8.3

### ISSUE THREAD

**Issue by hamidjafari** [socketio/socket.io-client-java#377]
hi guys.
i'm using socket.io client in my react-native app.
i've using version 0.8.2 so far and it works well . but when i've switched to 0.8.3 , i've got these errors.

` com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/ws/RealWebSocket$1;`

`com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process command /usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2`

it seems some kind of conflict in dependencies goes here . i've switched back to 0.8.2 for now and everything works great again.

so . is there any solution for solving this error?
thanks in advance

**Comment by b95505017** [comment]
It seams that react-native still use `com.squareup.okhttp3:okhttp-ws:3.4.1`.
https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle#L300

`okhttp-ws` is deprecated by Square team, So you should file an issue to react-native team instead.
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-350
>The okhttp-ws submodule is no longer available
