### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'io.socket.emitter.Emitter io.socket.client.Socket.on(java.lang.String, io.socket.emitter.Emitter$Listener)' on a null object reference

### ISSUE THREAD

**Issue by SelfnessAid** [socketio/socket.io-client-java#379]
I got below error when call the socket.on function.
Now I am using io-client:0.8.3

**build.gradle**
```
    compile ('io.socket:socket.io-client:0.8.3') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }
```

**error message :**
> FATAL EXCEPTION: main
>                   Process: mmstart0312.com.webrtc_android, PID: 22802
>                   java.lang.NullPointerException: Attempt to invoke virtual method 'io.socket.emitter.Emitter io.socket.client.Socket.on(java.lang.String, io.socket.emitter.Emitter$Listener)' on a null object reference
>                       at mmstart0312.com.webrtc_android.ConnectCallActivity.sigConnect(ConnectCallActivity.java:321)
>                       at mmstart0312.com.webrtc_android.ConnectCallActivity.access$000(ConnectCallActivity.java:37)
>                       at mmstart0312.com.webrtc_android.ConnectCallActivity$1.onClick(ConnectCallActivity.java:118)
>                       at android.view.View.performClick(View.java:5184)
>                       at android.view.View$PerformClick.run(View.java:20893)
>                       at android.os.Handler.handleCallback(Handler.java:739)
>                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                       at android.os.Looper.loop(Looper.java:145)
>                       at android.app.ActivityThread.main(ActivityThread.java:5942)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at java.lang.reflect.Method.invoke(Method.java:372)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**ConnectCallActivity.java  : 321**
```
        socket.on("connect", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                System.out.print("WebSocket connection open to" + wsServerUrl);
                sigEnter();
            }
        });
```

**Comment by b95505017** [comment]
Hi, how did you initialize the socket object?

**Comment by SelfnessAid** [comment]
Sorry, I missed it.
Now I solved it by initialize the socket object.
