### ISSUE TITLE
socket listener off

### ISSUE THREAD

**Issue by emirmg** [socketio/socket.io-client-java#381]
I have this listener: 

`    private Emitter.Listener onNewMessage = new Emitter.Listener(){
        @Override
        public void call(final Object... args){
            view_chats.this.runOnUiThread(new Runnable(){
                @Override
                public void run(){
                    .... SOME CODES HERE ....
                }
            });
        }
    };`

And running it in OnCreate : 
`super.mSocket.on("status", onNewMessage);`

How ever i launched activity its running . and i', receiving a message multiple .

How can i remove listener and add it again ?
Or how can i prevent duplicate a listener ?

thanks .

**Comment by alejo8591** [comment]
I have the same error..!!!

**Comment by nkzawa** [comment]
Use `Socket#off` method. See https://github.com/nkzawa/socket.io-android-chat/blob/master/app/src/main/java/com/github/nkzawa/socketio/androidchat/MainFragment.java#L98 as example.

**Comment by alejo8591** [comment]
In my activity and still the listener continues to receive requests.

```Java
protected void onCreate(Bundle savedInstanceState) {
mSocket.on(Socket.EVENT_CONNECT, onConnect);
        mSocket.on(Socket.EVENT_DISCONNECT, onDisconnect);
        mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
        mSocket.on(Socket.EVENT_CONNECT_TIMEOUT, onConnectError);
        mSocket.emit(APIConstants.RIDE_CHANNEL_RESPONSE_DRIVER, mRideResponse);
        mSocket.on(APIConstants.RIDE_CHANNEL_REQUEST_CUSTOMER_STATUS, onRequestCustomerStatus);
        mSocket.on(APIConstants.RIDE_RESPONSE_CUSTOMER_CANCEL, onResponseDriverCancel);
        mSocket.on(APIConstants.RIDE_ON_CHAT_CUSTOMER, onChat);
        mSocket.connect();

}

@Override
    protected void onDestroy() {
        super.onDestroy();
        mSocket.off(Socket.EVENT_CONNECT,onConnect);
        mSocket.off(Socket.EVENT_DISCONNECT,onDisconnect);
        mSocket.off(Socket.EVENT_CONNECT_ERROR, onConnectError);
        mSocket.off(Socket.EVENT_CONNECT_TIMEOUT, onConnectError);
        mSocket.off(APIConstants.RIDE_CHANNEL_REQUEST_CUSTOMER_STATUS, onRequestCustomerStatus);
        mSocket.off(APIConstants.RIDE_RESPONSE_CUSTOMER_CANCEL, onResponseDriverCancel);
        mSocket.off(APIConstants.RIDE_ON_CHAT_CUSTOMER, onChat);
        mSocket.disconnect();
        unregisterManagers();
    }
```
