### ISSUE TITLE
I can't use “ws://localhost:8080”

### ISSUE THREAD

**Issue by iokane** [socketio/socket.io-client-java#384]
I can't use “ws://localhost:8080”

**Comment by wedneyyuri** [comment]
Hi @iokane,

it's a socket.io client protocol implementation. You need [a server](http://socket.io/docs/server-api/) to handle your request.

**Comment by LuanTrinh5989** [comment]
Hi @wedneyyuri I using "wss://", but I don't connect to server, Support me, please?

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io-client-java/commit/67fd5f34a31c63f7884f82ab39386ad343527590, included in version `2.0.1`.

Please reopen if needed.
