### ISSUE TITLE
Connection to the server successful but can not get an answer for emmit

### ISSUE THREAD

**Issue by KirilaMenski** [socketio/socket.io-client-java#386]
For iOs I can get answer from server but not for android.
I have the following server code:
`    socket.on('login', function(info) {
        users.login(info, socket);
        socket.emit('login', 'login');
    });`

and the client-side:

        mSocket = IO.socket("http://MyUrl:port");
        mSocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.i(TAG, "connect login");
                mSocket.emit("login", json);
            }
        }).on("login", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                JSONObject data = (JSONObject) args[0];
                String response = "";

                try {
                    response = data.getString("login").toString();
                } catch (JSONException e) {
                    e.printStackTrace();
                }
                Log.i(TAG, "Server response: " + response);
            }
        });
        mSocket.connect();

also in my android-manifest I have permission:
`<uses-permission android:name="android.permission.INTERNET" />`

In the log I see that there was a connection to the server but I can't get response in emit.
I know that a similar problem already faced, but I spent a lot of time in searching and answers did not help me.
I would really appreciate if you can help me. Regards!

**Comment by KirilaMenski** [comment]
After several days of agony, it turned out that the problem was at the server side. If it helps someone

**Comment by superhjw** [comment]
can you tell me how you it
