### ISSUE TITLE
Nodejs - Android - socket.emit not working

### ISSUE THREAD

**Issue by maelfosso** [socketio/socket.io-client-java#387]
Hi,

I have a problem when using ``` socket.emit``` from Nodejs because all the Android users are getting the message instead of the one that starts the conversation

Let me explain:
From android I have that code run by a user when he create a new post
```java
socket.emit('post.new', data);
```
At the Node.js  I have
```javascript
socket.on('post.new', function (data) {
    var post = new Post(data);
    post.save();

    socket.emit('post.new.ack', post);
    socket.broadcast.emit('post.create', post);
});
```
The snippet ```socket.emit('post.new.ack', post)``` is supposed to be received only by the Android user who send ```post.new``` event but all the android users get that even. Why ?

Is there something I'm doing wrong ?

**Comment by wedneyyuri** [comment]
Broadcast is used for sending messages to all connected sockets. Sorry, but
you should check socket.io documentations or ask in stackoverflow.

**Comment by maelfosso** [comment]
@wedneyyuri you're about broadcasting but ```socket.emit('post.new.ack', post)``` is not broadcasting.
Why do all connected sockets receive it ?

**Comment by darrachequesne** [comment]
For future readers:

I was not able to reproduce:

```java
public class Fiddle {

    public static void main(String[] argz) throws Exception {
        IO.Options options = new IO.Options();

        Socket socket = IO.socket(URI.create("http://localhost:3000"), options);

        socket.on(Socket.EVENT_CONNECT, (__) -> {
            System.out.println("connect");
            socket.emit("post");
        });

        socket.on(Socket.EVENT_CONNECT_ERROR, (args) -> {
            System.out.println("connect_error: " + args[0]);
        });

        socket.on(Socket.EVENT_DISCONNECT, (args) -> {
            System.out.println("disconnect due to: " + args[0]);
        });

        socket.on("post.ack", (args) -> {
            System.out.println("got post.ack");
        });

        socket.on("post.create", (args) -> {
            System.out.println("got post.create");
        });

        socket.connect();
    }
}
```

JS Server:

```js
io.on("connection", (socket) => {
  socket.on("post", () => {
    socket.emit("post.ack");
    socket.broadcast.emit("post.create");
  });
});
```

Output:

```
connect
got post.ack

Process finished with exit code 0
```

Please reopen if needed.
