### ISSUE TITLE
How change query parameter (token) in Socket before connect

### ISSUE THREAD

**Issue by DoktorBog** [socketio/socket.io-client-java#394]
I provide  Socket with dagger2

    @Provides
    @AppScope
    public Socket provideSocket() {
        Socket socket = null;
        IO.Options opts = new IO.Options();
        opts.query = "auth_token=" + MyApplication.getInstance().getUser().getToken();
        opts.forceNew = true;
        try {
            socket = IO.socket(Helper.BASE_URL);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        return socket;
    }

after user to logout, and a new user to login i want to change token

**Comment by pkuhonker** [comment]
@DoktorBog How do you deal with the problem?

**Comment by Azinnilchi** [comment]
I have the same problem, when I want to change the account by changing token, it still connects to the previous socket! how can I deal with it?!
