### ISSUE TITLE
Connection problem 

### ISSUE THREAD

**Issue by Bekakk** [socketio/socket.io-client-java#397]
I try to create sockect connection.This is server side source 
`  <script src="/socket.io/socket.io.js"></script>
   <script>
    var socket = io.connect('http://192.168.101.139:8080' );
	
	socket.emit('initialize', { 
		host: "************",
		entity: "*********"
	} ); 	
	
	socket.on('onconnect', function (data) {
		console.log(data);    
	});

	socket.on('onerror', function (data) {
		console.log(data);    
	});
  
	socket.on('device', function (data) {
		console.log(data);    
	});
  
    
</script>
Client Display!
and this is android source

                  `try {
                  SocketIO socket = new SocketIO("http://192.168.101.139:8080");
                  socket.connect(new IOCallback() {
                  @Override
                   public void on(String event, IOAcknowledge ack, Object... args) {
                    if ("echo back".equals(event) && args.length > 0) {
                        Log.d("SocketIO", "" + args[0]);
                    }
                }

                @Override
                public void onMessage(JSONObject json, IOAcknowledge ack) {
                }

                @Override
                public void onMessage(String data, IOAcknowledge ack) {
                }

                @Override
                public void onError(SocketIOException socketIOException) {
                    socketIOException.printStackTrace();
                }

                @Override
                public void onDisconnect() {
                    Log.e("onDisconnect","onDisconnect");

                }

                @Override
                public void onConnect() {
                    Log.e("onConnect","onConnect");
                }
            });
            socket.emit("echo", "hello");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
When i run my app i have `i have SocketIOException error
Error message:
 Caused by: java.io.FileNotFoundException: http://192.168.101.139:8080/socket.io/1/
how i can solve my problem?

`

**Comment by giriakshay** [comment]
I am getting same error. Can you please help.
