### ISSUE TITLE
Identify socket from Emitter.Listener callback

### ISSUE THREAD

**Issue by zahid-mt** [socketio/socket.io-client-java#401]
I have more than two socket connections, and all sockets have same event names. **How can I know which socket has provided me the callback on an event.**  I need to identify socket inside call() method.

```
private HashMap<Integer,Socket> sockets;
public static final String INIT_PACKET = "initPacket";

if(!sockets.get(userType).hasListeners(INIT_PACKET)){
      sockets.get(userType).on(INIT_PACKET, onInit);
}

private Emitter.Listener onInit = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            //which socket provided this callback ?
        }
 };
```

**Comment by darrachequesne** [comment]
For future readers:

There is currently no way to fetch the reference of the socket instance.

Please reopen if needed.
