### ISSUE TITLE
Unable to connect on Https 

### ISSUE THREAD

**Issue by mayank250004** [socketio/socket.io-client-java#402]
without https ( means on http) same thing working but when i switch to https , iam unable to connect to the socket , and its working fine on JavaScript side

URL : https://www.greatpros.com:59682

**Comment by InventivetalentDev** [comment]
I'm having the same issue.  
Connecting via the domain (which has a Cloudflare certificate) doesn't work, but using the direct IP address via HTTP works just fine.

**Comment by komorebi-san** [comment]
I am having the same issue as well.

**Comment by darrachequesne** [comment]
For future readers:

Please check the SSL examples here: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.
