### ISSUE TITLE
on emit socket disconnect with transport error

### ISSUE THREAD

**Issue by mayank250004** [socketio/socket.io-client-java#403]
on https connection socket connect perfectly but when i emit then socket disconnect with error : transport error

**Comment by rahmamajed** [comment]
same as here i look to all recent issues there are not any respond from the developer i am looking for new one 
i have been with this issue for almost a month

**Comment by AhmedX6** [comment]
Any solution..??? Has the same problem.

**Comment by spectre013** [comment]
Experiencing the same issue.

**Comment by AhmedX6** [comment]
Are you all experiencing this problem with socket io server in golang ? (https://github.com/googollee/go-socket.io)
If yes, the problem comes from the server. It's not maintained anymore and it has some problems.
I had to implement a socketIO server on JS to make it working properly.

**Comment by LeeBoonKong** [comment]
Same issue, With Socket IO Server 2.1.1 and Socket IO Client Java a 1.0.0
@nkzawa

**Comment by MichaelJokAr** [comment]
same error

**Comment by LeeBoonKong** [comment]
Dear all,
It seems like the problem would probably be the configuration of okHttp.

`           OkHttpClient okHttpClient = new OkHttpClient.Builder()
                    .hostnameVerifier(hostnameVerifier)
                    .sslSocketFactory((SSLSocketFactory) SSLSocketFactory.getDefault(), trustManager)
                    .connectTimeout(20, TimeUnit.SECONDS)
                    .writeTimeout(1, TimeUnit.MINUTES)
                    .readTimeout(1, TimeUnit.MINUTES)
                    .build();
            IO.setDefaultOkHttpCallFactory(okHttpClient);
            IO.setDefaultOkHttpWebSocketFactory(okHttpClient);`

By adding `connectTimeout`, and providing it a long `writeTimeout` and `readTimeout` seems to work for me.
Note: There is a heartbeat mechanism that you can specify on Socket.IO Server, which I think the value here should tally with your server's `pingTimeout` value.
Note2: The default values of these parameters in okHttp is 10000ms or 10 seconds.

**Comment by MichaelJokAr** [comment]
@LeeBoonKong but I'm using the v0.8.3 .not have okhttp

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
