### ISSUE TITLE
send message in handler "client error" ?

### ISSUE THREAD

**Issue by Awekbing** [socketio/socket.io-client-java#407]
Android 中
发现个问题    `mSocket.emit("new message", msg);`
发送消息不能放在 handler service timer中
否则发送会出现  client error

English:
There is a problem with `mSocket.emit ("new message", MSG);
Send message cannot be placed in handler service timer
Otherwise the send will appear ’client error‘  ， send fail

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
