### ISSUE TITLE
No options for Origin-Header

### ISSUE THREAD

**Issue by Bizarrus** [socketio/socket.io-client-java#408]
Please attach an method to set the Origin-Header!

For security-reasons, i'm checking the origin on server-side. I Dont want to disable it.

**Comment by b95505017** [comment]
Please checkout https://github.com/socketio/engine.io-client-java/pull/85 if the new mechanism works for you. Basically you could setup your own OkHttpClient via [Builder](http://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html) then inject into our library.

**Comment by darrachequesne** [comment]
For future readers:

```java
IO.Options options = IO.Options.builder()
        .setExtraHeaders(singletonMap("origin", singletonList("https://example.com")))
        .build();

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders
