### ISSUE TITLE
clear stack after connec to server

### ISSUE THREAD

**Issue by pishguy** [socketio/socket.io-client-java#411]
when my device is disconnected from server or device dont have interner connection, emit data cause of making stack and after connect to server (nodeJs) this library send all stacked data to server, how can i clear this stack before connection to Nodejs server?

**Comment by darrachequesne** [comment]
For future readers:

This is not currently possible. As a workaround, you can check the value of `socket.connected()` before sending the data:

```java
if (socket.connected()) {
  socket.emit(...);
}
```

If you send some data when the socket is disconnected, it will be buffered. Please reopen if needed.
