### ISSUE TITLE
v2.0 support?

### ISSUE THREAD

**Issue by yosuke-furukawa** [socketio/socket.io-client-java#421]
socket.io is now v2.0.
socket.io-client-java is already supported v2.0??

**Comment by nkzawa** [comment]
Unfortunately, It's not supported for now. We'd like to support it. PR welcome 😄

**Comment by rockwotj** [comment]
What would it take to support v2.x?

**Comment by srinisubramanian** [comment]
The iOS version already supports 2.0.  If someone can list out the adaptations we can also submit a PR

**Comment by JarnoVgr** [comment]
@nkzawa Have you stopped working on this Java implementation, seeing you're asking for a PR? (just genuinely wondering as you were/are the project maintainer)

socket.io 2.0 support would be greatly appreciated.

**Comment by ehog90** [comment]
There are several issues - mostly connection-related - with this package when using against a 2.0-based backend. An update to 2.0 would be great!

**Comment by nkzawa** [comment]
Just released 1.0.0 which supports socket.io v2.0.

@JarnoVgr  I'm still working on the Java implementation, but unfortunately it's not priority for now.

**Comment by MudassirAsghar22** [comment]
Hello @nkzawa , i need to confirm that have you developed socket.io to support v2.0 fully in java now? i need to implement it in android, thanks for your response in advance

**Comment by JarnoVgr** [comment]
I've been using socket.io-java 1.0 (Android) in production since release back in 2017 in conjunction with socket-io server 2.0.x. Works fine. However, it feels kind-of strange that there's no development anymore.

**Comment by IlyaDiallo** [comment]
@JarnoVgr same for me (a bit strange), but for that kind of component some stability is rather welcome IMO
