### ISSUE TITLE
I can't use Socket.setDefaultOkHttpWebSocketFactory(XXX)

### ISSUE THREAD

**Issue by jc7003** [socketio/socket.io-client-java#429]
your provider method **Socket.setDefaultOkHttpWebSocketFactory** and **Socket.setDefaultOkHttpCallFactory** in the  engine.io-client is document.

![2017-06-20 3 40 47](https://user-images.githubusercontent.com/1667774/27322102-5dbf5570-55cf-11e7-9fd1-a6e6dd11820b.png)

but i can't find this.

below is my build.gradle config
    compile ('io.socket:socket.io-client:0.8.3') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }

**Comment by nkzawa** [comment]
You can use it from 0.9.0, check it out.
