### ISSUE TITLE
Unicode decode error for Non-English characters

### ISSUE THREAD

**Issue by csoni111** [socketio/socket.io-client-java#430]
I am emitting some non English characters _(in Hindi language)_ in json format from my node.js socket.io server to an android client. It all works fine in case of `websocket` connection but in case of `polling` it **changes the Non-English characters to some garbage values**.
On diving deep in the code I found this happens because in both of them it calls [decodePacket() function](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/parser/Parser.java#L78). Now in case of `websocket` it passes the value of `boolean utf8decode` as False where as in case of `polling` it passes the value as True which ultimately calls [UTF8.decode(data)](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/parser/Parser.java#L88).

Now in UTF8.Java it first [makes](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/utf8/UTF8.java#L34) a new array of charPoints for all the characters in the message string.
Now for each charPoint in the array it evaluates [decodeSymbol()](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/utf8/UTF8.java#L39), which returns the converted codePoint value. Now in my case the code point values for non english character is greater than 255 (>2000 actually), so when this gets passed through the function, it should process it till the third byte (I am not sure what exactly this algo is doing). But this ends at [#L100](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/utf8/UTF8.java#L100) returning only the value of byte1.
This makes my characters change to garbage value.

If someone can help me understand why this utf8 decode then encode is exactly required or at least what this is doing?

**Comment by csoni111** [comment]
A sample example of the conversion that is being done:
Lets say my character is `अ`, its codePoint is 2309.
Now on processing it through [decodeSymbol()](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/utf8/UTF8.java#L81), on line [#96](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/utf8/UTF8.java#L96):
    `2309 & 0xFF` returns 5
then on [Line#99](https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/utf8/UTF8.java#L99):
    `5 & 0x80` returns 0
Hence the if condition becomes true and function ends here, returning 5 as the value. Hence corrupting the 
 original character.

**Comment by csoni111** [comment]
I think it is something related to [socketio/engine.io-parser#81](https://github.com/socketio/engine.io-parser/pull/81) and [socketio/engine.io/#315](https://github.com/socketio/engine.io/issues/315).

**Comment by nkzawa** [comment]
I wonder if you were using socket.io 2.0.x. In that case, upgrade socket.io-client-java to v1.0.0.

**Comment by nkzawa** [comment]
It seems that's the case.

**Comment by chanchurbansal** [comment]
thanks for the fix.  now the response is decoding to utf-16 unicoding

**Comment by PriyaSingh2311** [comment]
Hi..I am using 1.7.4 at server side and 0.8.3 version at client side in android but unable to connect with socket..Don't know why?
