### ISSUE TITLE
How to update options's query before socket reconnect?

### ISSUE THREAD

**Issue by pkuhonker** [socketio/socket.io-client-java#434]
I cann't found the property from the socket.

**Comment by nkzawa** [comment]
Unfortunately, there is no way since it automatically happens. Instead, usually you can `emit` values when reconnecting.

**Comment by romichandra** [comment]
One POOP hack for the socket.io JAVA client could be to use reflection and update the "query" variable in the Socket.java class.

Though the better solution is for @nkzawa to make the "query" public or maybe have the Manager class expose the query variable.

Until we have a clean way,
Here's a sample code snippet which works:

`Field field = Socket.class.getDeclaredField("query");
 field.setAccessible(true);
 String updatedQuery = // your updated query;
 field.set(mSocket, updatedQuery);`

**Comment by darrachequesne** [comment]
For future readers:

```java
socket.io().on(Manager.EVENT_RECONNECT_ATTEMPT, new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        options.query = "y=43";
    }
});
```

Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#query

**Comment by iagormoraes** [comment]
> For future readers:
> 
> ```java
> socket.io().on(Manager.EVENT_RECONNECT_ATTEMPT, new Emitter.Listener() {
>     @Override
>     public void call(Object... args) {
>         options.query = "y=43";
>     }
> });
> ```
> 
> Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#query

This approach worked like a charm, and to propagate the changes if an error event happens due to expired token or something, you can disconnect and connect socket so it can get the updated options.
