### ISSUE TITLE
Battery drain issue

### ISSUE THREAD

**Issue by arpitjoshi08** [socketio/socket.io-client-java#435]
i am using socketio for android and working properly. now getting issue is that battery drain quickly when app used. how can i resolved that issue.

**Comment by kahwooi** [comment]
@arpitjoshi08 Did you left the socket open all the time or you disconnect it after a process finish?

**Comment by arpitjoshi08** [comment]
according to my need i have to connect socket every time even after app is kill from background (using in chat app)

**Comment by jirevwe** [comment]
Actually, you should not do that. 

If this is a chat app, use [https://firebase.google.com/docs/cloud-messaging/](Firebase Cloud Messaging) to intercept messages when the app is on the background and open the appropriate activity/fragment with the chat UI.

If the app is open the the socket should only connect in the activity/fragment that has the chat interface or depending on your implementation, you can register the socket on the application instance.

**Comment by darrachequesne** [comment]
For future readers:

I've added a note in the documentation: https://socketio.github.io/socket.io-client-java/android.html#How_to_keep_a_Socket.IO_client_running_in_the_background.3F

Please reopen if needed.
