### ISSUE TITLE
Compatibility of socket.io-client-java with socket.io-client on server

### ISSUE THREAD

**Issue by alboy51** [socketio/socket.io-client-java#440]
I was using to pass data between phone and server using socket.io-client 1.6.0 on both sides. Recently I got a need to create a separate service to handle push notifications. So I created a Client class which was using this library to connect to server. 

When I try to connect, the EVENT_CONNECT event triggers, assuming that I connected to the server, however the server logs do not show any signs of me connecting. Same story when I try to emit, the server does not get it.

I am using 0.6.3 version of clients-java, while server uses 1.6.0 of socket.io-client. I cannot go higher in the client java because starting on next version I start getting the "already exists" error on the okhttp3 class. By my understanding it is because the okhttp-ws class that was merged into okhttp.

My question is - does your library have support for 1.6.0 of socket.io-client? Does it work with it? And are there any version restrictions?

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socketio.github.io/socket.io-client-java/installation.html
