### ISSUE TITLE
How to set header in event transport 

### ISSUE THREAD

**Issue by anonimeact** [socketio/socket.io-client-java#442]
How to set header in event transport (Transport.EVENT_REQUEST_HEADERS) when we use Kotlin?

**Comment by darrachequesne** [comment]
For future readers:

```java
IO.Options options = IO.Options.builder()
        .setExtraHeaders(singletonMap("authorization", singletonList("bearer 1234")))
        .build();

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders
