### ISSUE TITLE
How to send extraheaders as options parameter?

### ISSUE THREAD

**Issue by ckdvivedi** [socketio/socket.io-client-java#443]
How can we send extraheaders as options parameter in v.1.0.0

**Comment by darrachequesne** [comment]
For future readers:

```java
IO.Options options = IO.Options.builder()
        .setExtraHeaders(singletonMap("authorization", singletonList("bearer 1234")))
        .build();

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders

**Comment by digitalcleavage** [comment]
the builder() doesn't show up until client version 2.x. How to do this in version 1.x is driving me nuts...
