### ISSUE TITLE
Android Socket io multiple event

### ISSUE THREAD

**Issue by loidoantitan** [socketio/socket.io-client-java#455]
I run code after , two event login-response , event-response , broadcasting not working . I using cookie header connect. Help me
`try {
            mSocket = IO.socket("my url");
            mSocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    Log.v("connect 1", Arrays.toString(args));

                }

            }).on("login-response", new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    final JSONArray deviceArray = (JSONArray) args[0];
                    Log.v("login-response", "login-response");
                }
            }).on("event-response", new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    final JSONObject deviceObject = (JSONObject) args[0];
                    Log.v("event-response", "event-response");
                }
            }).on("broadcasting", new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    final JSONObject deviceObject = (JSONObject) args[0];
                    Log.v("broadcasting", "broadcasting");
                }
            }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

                @Override
                public void call(Object... args) {
                    Log.v("disconnect", Arrays.toString(args));
                }

            });
            mSocket.connect();
        } catch (URISyntaxException e) {e.printStackTrace();}`

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
