### ISSUE TITLE
Android 6.0 cannot connect to socket.io server, returning "xhl poll error"

### ISSUE THREAD

**Issue by sikrinick** [socketio/socket.io-client-java#458]
On Android 6.0 it is impossible to connect to socket.io server via HTTPS as it emits CONNECT_ERROR with message:
`xhl poll error`
and 
`javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`
On Android 6.0 with HTTP everything works fine.
On Android 7.0 both with HTTP and HTTPS everything works fine.

**Comment by ananth10** [comment]
Same issue here

**Comment by sivabe35** [comment]
Same issue here... Any update?

**Comment by ananth10** [comment]
Hello all.. please install ssl certificate and intermediate certificate in your chat server. then it will work like charm.

**Comment by pradipvadher** [comment]
can you please share any link for your solution, i already add certificate in android application? @ananth10

**Comment by ananth10** [comment]
@pradipvadher you can ask your backend developer to check all certificates have installed right way by [](https://www.sslshopper.com/ssl-checker.html)

**Comment by darrachequesne** [comment]
For future readers:
 
Please check the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.

**Comment by darrachequesne** [comment]
For future readers:
 
Please check the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.
