### ISSUE TITLE
Library seems not to allow simultanous connections of more than around 5

### ISSUE THREAD

**Issue by innaj** [socketio/socket.io-client-java#460]
I have severe issues when trying to use this library for a performance-test:
[https://stackoverflow.com/questions/46150548/socket-io-java-client-does-not-connect-when-used-threaded](https://stackoverflow.com/questions/46150548/socket-io-java-client-does-not-connect-when-used-threaded)

the problems do not occur when I do the tests with javascript using the socket.io client javascript library, so I'm suspecting there must be something strange in the library?

**Comment by petrhejna** [comment]
Also mentioned here: https://github.com/socketio/socket.io-client-java/issues/281#issuecomment-394052775

**Comment by petrhejna** [comment]
@innaj  This will solve the issue:
```scala
    val disatcher = new Dispatcher()
    disatcher.setMaxRequests(5000)
    disatcher.setMaxRequestsPerHost(5000)

    val okHttpClient = new OkHttpClient.Builder()
      .connectionPool(new ConnectionPool(5000, 5, TimeUnit.MINUTES))
      .dispatcher(disatcher)
      .build()

    IO.setDefaultOkHttpWebSocketFactory(okHttpClient)
    IO.setDefaultOkHttpCallFactory(okHttpClient)

    val socket = IO.socket(url, opts);
```

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socketio.github.io/socket.io-client-java/faq.html#How_to_create_a_lot_of_clients

Please reopen if needed.
