### ISSUE TITLE
Connecting to flask-socketio with authentication

### ISSUE THREAD

**Issue by Nixellion** [socketio/socket.io-client-java#462]
I'm writing an Android client for my Flask-SocketIO server. I managed to connect to it using chat app example, but I think  I have an issue with autentication. 

To receive some (most) socket events server requires client to be authenticated. In flask\js-html client it's done simply by sending a POST with login and password to domain.com/login. For my use-case it's enough.

But is there a way to authenticate android app client like that? I tried adding query options to / or /test namespaces, and since socket io retargets all to /socket.io I don't think it's supposed to work like that anyway...

How should I approach this?

**Comment by Nixellion** [comment]
Solved this part, should be enough to emit login data for server to accept it and log the user in. But there's another issue...

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
