### ISSUE TITLE
net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by KnottyCord** [socketio/socket.io-client-java#465]
Hi I have get this error all the time in the console of my website. 
Here is the error:
`socket.io-1.4.5.js:60 GET https://138.197.141.234:2096/socket.io/?EIO=3&transport=polling&t=LymCVmU net::ERR_INSECURE_RESPONSE`

Here is my app config for ssl:
```
var express = require('express');
var options = {
    key: fs.readFileSync('name.key'),
    cert: fs.readFileSync('name.crt'),
    requestCert: true
};
var app = express();
var server = require('https').createServer(options, app);
var io = require('socket.io').listen(server);
server.listen(2096, "0.0.0.0");

```

Thank you!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
