### ISSUE TITLE
Socket.io-client - Streaming from server.

### ISSUE THREAD

**Issue by farhansharifkhokhar** [socketio/socket.io-client-java#466]
Hi Guys!

Can anyone please help me? I am just trying to understand this library and tried a lot to receive response from a websocket.

url = 'https://ws-api.iextrading.com/1.0/tops'
socket = require('socket.io-client')(url)
socket.emit('subscribe', 'firehose')

I want to receive response from server using these conditions. I am able to do it in Node.JS.
I just want to have real time data stream. Can anyone please give me a sample code? So i can just run and start printing response on console at the moment?
Please Help!
Really in need of it now. Please?

**Comment by darrachequesne** [comment]
For future readers:

Please check the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.
