### ISSUE TITLE
Joining multiple namespaces on a single client instance.

### ISSUE THREAD

**Issue by alihen** [socketio/socket.io-client-java#472]
Our application communicates on multiple namespaces. I'm looking to join multiple namespaces and emit messages to the correct namespace using the same`Socket` instance (i.e not connecting another client to the server for each namespace)

I noticed that [Manager.java](https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Manager.java#L442) creates as `Socket` instance for each namespace. Is there support for a single socket instance to belong to multiple namespaces?

I would think this could possibly be implemented with some tweaks to the `Socket` instance and possibly the parser if it relies on namespace validation (I know `socket.io-client-swift` implementation has validation in the parser). 

What would be the best approach to join multiple namespaces using a single socket instance?

**Comment by rkachach** [comment]
@alihen did you manage to fix this issue somehow? I'm facing the same problem. It's very easy to connect to multiple namespaces using the same socket from python-socketio but it's not possible to do the same using this library.
