### ISSUE TITLE
Android Client doesnt receive broadcast.emit message from node server

### ISSUE THREAD

**Issue by Kenan13** [socketio/socket.io-client-java#486]
Android Code
`public class MainActivity extends AppCompatActivity {

    private Socket msocket;
    {

        try{
            msocket = IO.socket("http://10.0.2.2:3000");
        } catch (URISyntaxException e) {
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        WebView webb = (WebView) findViewById(R.id.web1);
        //webb.setWebViewClient(new WebViewClient());
        WebSettings webSettings = webb.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webb.loadUrl("file:///android_asset/webpage.html");
        webb.addJavascriptInterface(new WebAppInterface(this), "Android");
        msocket.on("broadcastOnDropdownChanged", broadcastMessage);
        msocket.emit("AndroidMessage", "I am now connected");
        msocket.connect();

        Log.i("SocketInfo","TRIED TO CONNECT TO SERVER");
    }
    private Emitter.Listener broadcastMessage = new Emitter.Listener() {

        @Override
        public void call(final Object... args) {
            Log.i("Status", "Entered the broadcast");
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    JSONObject data = (JSONObject) args[0];
                    int currentValue;
                    String currentText;
                    try{
                        currentValue = data.getInt("currentValue");
                        currentText = data.getString("currentText");
                    } catch(JSONException e){
                        return;
                    }

                    Log.i("CurrentValue", Integer.toString(currentValue));
                    Log.i("CurrentText", currentText);

                }
            });

        }
    };`

Server Code
`var app = require('express') ();
var http = require('http').Server(app);
var io = require('socket.io')(http);
var fs = require('fs');

app.get('/', function(req, res) {
  res.sendFile(__dirname + '/client/index.html');
});

io.on('connection', function(socket) {
  console.log('a user is connected');
  socket.on('disconnect', function(){
    console.log('user disconnected');
  }); 

  socket.on('broadcastOnDropdownChanged', function(data){
    //broadcast message to Android
    socket.broadcast.emit(data.emitName, {currentValue: data.currentValue, currentText: data.currentText});
  }); 
  socket.on('AndroidMessage', function(data){
    console.log(data);
  }); 
});

http.listen(3000, function() {
  console.log('listening on *:3000');
});`

I can successfully send message to the server from the Android but my Emulator does not receive the broadcast message from the web browser client via broadcast.emit. 
the Log.i("Status,....) won't even be reached...

Any Help will be appriciated

**Comment by gokkayasertac** [comment]
I have same issue but with the little difference. I tried on 3 physical device and 1 emulator. The last device that reaches socket's onConnect Emitter.Listener, did not receive message. It does not metter it is Emulator or physical device. If you solved this issue, I would glad to hear the solution.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
