### ISSUE TITLE
How to let the client send a callback after receiving a message from the server

### ISSUE THREAD

**Issue by Alex--Kang** [socketio/socket.io-client-java#49]
Hi, I was wondering how do I make a callback on the client side to acknowledge the server.
for example,
Assuming the server side has this:
io.sockets.emit('delete', {id: id}, function(data){
                    console.log('callback');
                });

And on the client side ( I'm using Android ), I have 

socket.on("delete", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    log.d(TAG,"Received server delete msg");
                }

My question is, is there a way to ack the server similar to the regular java script?
If it's In java script, I could do something like this
socket.on('delete', function(data, callback) {
        console.log("i received: "+ data);
        callback("This function on server will run");  
    });

Thank you.

**Comment by arslanaka** [comment]
hi, I'm using socket.io client on android and server on js, I want to know is there any way to emit multiple arguments with a callback function. 
I can emit multiple args in JS like this but no in JAVA.
***
`// with multiple arguments
socket.on('news', (arg1, arg2, arg3, arg4) => {
  // ...
});`
****
In JAVA I can emit only a single argument/Object, like this;

` mSocket.emit("create", authentication, new Ack()
{
                @Override
                public void call(Object... args) {
                    JSONObject ackData = (JSONObject) args[0];
                    Log.d(TAG, "call35: "+ackData);
                }
            });

`
