### ISSUE TITLE
Expected 'Connection' header value 'Upgrade' but was '"null"

### ISSUE THREAD

**Issue by jorge-costa-carbon** [socketio/socket.io-client-java#490]
Sometimes when I'm connected by 4g (full network) I can't connect to the websocket server the response are always: >`Expected 'Connection' header value 'Upgrade' but was '"null"'"`

Devices: Oneplus 5T (7.1.2) & Pixel (8.0.0)

Then when I turn on wifi starts working well. I try in others devices with the same network provider and works well.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
