### ISSUE TITLE
Kotlin Socket.io not connecting

### ISSUE THREAD

**Issue by RpeshB** [socketio/socket.io-client-java#494]
> I am trying to connect to socket with https  using kotlin v1.2.21 , my project contain dagger, RXjava, Retofit ,Okhttp like library which is the best way to implement using RXjava and  dagger ? I try lots of way but facing issue to connect socket.  So i made simple example to connect Socket but still unable to connect Please help me `package com.easymakers.myapplication

import android.os.Bundle
import android.support.design.widget.Snackbar
import android.support.v7.app.AppCompatActivity
import android.util.Log
import android.view.Menu
import android.view.MenuItem
import com.github.nkzawa.emitter.Emitter
import com.github.nkzawa.socketio.client.IO
import com.github.nkzawa.socketio.client.Socket

import kotlinx.android.synthetic.main.activity_main.*
import javax.net.ssl.SSLContext

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        setSupportActionBar(toolbar)

        fab.setOnClickListener { view ->
            Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                    .setAction("Action", null).show()
            //connect()
            connect1()
        }
    }

     private fun connect() {
        val socket = IO.socket("https://192.168.1.23:5000")
        socket.connect()
                .on(Socket.EVENT_CONNECT, {
                    println("connected")
                })
                .on(Socket.EVENT_DISCONNECT, { println("disconnected") })
    }

    private fun connect1(){
        val sc = SSLContext.getInstance("SSL")
        sc.init(null, null, null)
        val opts = IO.Options()
        opts.secure = true
        opts.forceNew = true
        opts.reconnection = true
        val  socket = IO.socket("https://192.168.1.23:5000",opts)
        socket.on("connection", Emitter.Listener {
            println("Connected")
            socket.emit("foo", "hi")
            socket.disconnect()
        }).on("event", Emitter.Listener { }).on(Socket.EVENT_DISCONNECT, Emitter.Listener { })
        socket.connect()
    }
}
` this is sample code using ` implementation 'com.github.nkzawa:socket.io-client:0.5.2'` this library 

>

**Comment by JahangirJadiKD** [comment]
After hours of struggle, this finally works. 

 val uri = URI.create("http://192.168.0.186:3000")
        val options = IO.Options.builder() 
            .build()

        socket = IO.socket(uri, options)
        socket.connect()
