### ISSUE TITLE
Battery saving practices

### ISSUE THREAD

**Issue by azizkayumov** [socketio/socket.io-client-java#496]
I am building a chat app which uses socket.io. Everything is working ok but the battery usage is very high since my app has a background service which receives messages from server 24/7. On high devices it might not be noticeable but one of my testers who uses low end phone complains about the battery usage and says that my app is using 17 % of battery while the screen is 16 % (which supposed to use the most!). So, my questions are the following:
1. The socket is listening about 15 channels in a background service, if I close some of them when app is going background, will the battery usage be better or remains the same?
2. If the first question won't solve my problem, can you offer other solutions? I don't want to use neither FCM or GCM to receive notifications and wake up the socket.
I think my question is not a duplicate of [those](https://github.com/socketio/socket.io-client-java/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+battery), since I am not satisfied from any of them and looking for more solutions.
Thanks in advance.

**Comment by efkan** [comment]
If we could stop to client checking by server and declaring by client I think the battery draining would be reduced into a really small percent.

Then our socket connection behaves just like a GCM (Push Messaging) system.

I don't know whether changing `pingInterval` parameter works or not. But at my first try the socket had been disconnected 11 times in 7 hours. I've been investigating...

**Comment by habilpekdemir** [comment]
did you find any solution ?

**Comment by darrachequesne** [comment]
For future readers, the Socket.IO library is not meant to be used in a background service, as it will keep an open TCP connection to the server, resulting in a high battery consumption.

For this use case, I think using a messaging platform like [FCM](https://firebase.google.com/docs/cloud-messaging) is the way to go...

That being said, maybe you could frequently connect/disconnect the Socket client, to check for new messages. But that seems a bit far fetched.
