### ISSUE TITLE
Error in Android applications

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [socketio/socket.io-client-java#5]
When I try to open connection to http socket.io server. An exception is thrown by Dalvik :

"Could not find class 'com.gitgub.nkzawa.engineio.client.transports.WebSocket$1" referenced from method com.github.nkzawa.engineio.client.transport.WebSocket.doOpen

From java application run correctly.

**Comment by saurabhsharma01** [comment]
Can you tell me steps to do WebSocket connection ....

**Comment by nitin105** [comment]
compile ('io.socket:engine.io-client:1.0.0') {
  // excluding org.json which is provided by Android
  exclude group: 'org.json', module: 'json'
}

its work for me
