### ISSUE TITLE
Can't work at socket.io 2.0 server???

### ISSUE THREAD

**Issue by 0xddy** [socketio/socket.io-client-java#500]
Client can't monitor the server's data

**Comment by s9443112** [comment]
In socket.io 1.3.5 & socket.io java 0.8.3 it's ok.
But in socket.io 2.0.4 & socket.io java 1.0.0 have a big problem say transport error,
client will be disconnect

**Comment by s9443112** [comment]
If your have to use socket.io swift ,your server have to be version 2.0.X.
if you use 1.X.X your ios language will be Garbled（Chinese）

**Comment by allMighto** [comment]
Did you solve this issue ?

**Comment by s9443112** [comment]
yes, I can work

**Comment by ngunhaSO** [comment]
@s9443112 : i am facing the issue regarding the node.js server version is 2.0.4 and the client is 1.0.0.
Do you have any workaround for this as i keep getting transport error on Android

**Comment by s9443112** [comment]
Yes ,in Android socket io 1.0.0 version ,It sometimes will transport error,
I don’t know why ,so I downgrade socket.io server version to 1.7.4 and
Android compile 'io.socket:socket.io-client:0.8.3'

Nhan Nguyen <notifications@github.com>於 2018年4月17日 週二，下午4:34寫道：

**Comment by ngunhaSO** [comment]
@s9443112 The thing I am using a hybrid app, downgrading the socket version on the server may cause the iOS version to stop working...

**Comment by NiebieskiMak** [comment]
Same here Android 'io.socket:socket.io-client:1.0.0' and server is 2.0.4. Getting transport error. Then reconnect and it works for a while then error again. Not a loop i would like to see.

**Comment by linxu** [comment]
'io.socket:socket.io-client:1.0.0' and 'socket.io 2.1.0' is ok

**Comment by NiebieskiMak** [comment]
Well it seems upgrading to 2.1.0 did not help.

**Comment by ljcljc** [comment]
Did anyone solve this problem?

**Comment by darrachequesne** [comment]
For future readers:

Please check the compatibility table here: https://socketio.github.io/socket.io-client-java/installation.html

Please reopen if needed.
