### ISSUE TITLE
Doze mode

### ISSUE THREAD

**Issue by anotherdev** [socketio/socket.io-client-java#501]
What is the current behavior of socket.io-client-java when entering Doze mode? All devices with Android 6.0+ have this power saving feature.

https://developer.android.com/training/monitoring-device-state/doze-standby.html

**Comment by efkan** [comment]
In my case; 
- After screen-off GarbageCollector already kills idle services.
- Doze mode stops network activities or defers them.

So, if a persistent socket connection is not necessary, a solution by using AlarmManager class can be implemented without any issue. An app that is created by using `socket.io-client-java` library should be worked successfully.

If a persistent socket connection is necessary, `socket.io-client-java` does not assure a solution for now.

I guess this issue can be closed.

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socketio.github.io/socket.io-client-java/android.html#How_to_keep_a_Socket.IO_client_running_in_the_background.3F

Please reopen if needed.
