### ISSUE TITLE
 not working with AWS sticky session

### ISSUE THREAD

**Issue by chaturanga836** [socketio/socket.io-client-java#503]
this is not work with AWS sticky session, but IOS socket IO has no issues. I monitor the headers. the load balancer will add value to cookie Like this AWSALB=AFcPEPJE1mqrqDKO7bFDFWv5jwUVnOQ41IBLCHZhNwNGN/HJYHDis4OqJANzd5hYRfjkXBwsKhrhhfzOt4XmfiS4kaRghEhq6RirOsBucK0F1mSd+x6JlqQTBK7F

but in this library, it's fail

**Comment by chaturanga836** [comment]
The IOS headers

{
     headers:    {
         'x-forwarded-for':  '112.134.146.152',
             'x-forwarded-proto':  'http',
             'x-forwarded-port':  '3232',
             host:  'dia-ride-dev-nodejs.layoutindex.net: 3232',
             'x-amzn-trace-id':  'Root=1-5a86a918-3bfc1206e5b215d01b2464b9',
             accept:  '*/*',
             cookie:  'AWSALB=AFcPEPJE1mqrqDKO7bFDFWv5jwUVnOQ41IBLCHZhNwNGN/HJYHDis4OqJANzd5hYRfjkXBwsKhrhhfzOt4XmfiS4kaRghEhq6RirOsBucK0F1mSd+x6JlqQTBK7F',
             'user-agent':  'DTaxi/1 CFNetwork/893.14.2 Darwin/17.3.0',
             'accept-language':  'en-us',
             'accept-encoding':  'gzip,
         deflate' 
    },
      time:  'Fri Feb 16 2018 15: 19: 12 GMT+0530 (+0530)',
      address:  ': : ffff: 172.18.0.135',
      xdomain:  false,
      secure:  false,
      issued:  1518774552871,
      url:  '/socket.io/?transport=polling&b64=1&type=passenger&id=26',
      query:  {
         transport:  'polling',
         b64:  '1',
         type:  'passenger',
         id:  '26' 
    } 
}

**Comment by chaturanga836** [comment]
okhttp3 header

{
     headers:    {
         'x-forwarded-for':  '175.157.93.4',
             'x-forwarded-proto':  'http',
             'x-forwarded-port':  '3232',
             host:  'dia-ride-dev-nodejs.layoutindex.net: 3232',
             'x-amzn-trace-id':  'Root=1-5a86a1b8-4fac8168c3ed2a58dd556d80',
             accept:  '*/*',
             cookie:  'io=5e84d6d9cad6cfc3',
             'accept-encoding':  'gzip',
             'user-agent':  'okhttp/3.8.1' 
    },
      time:  'Fri Feb 16 2018 14: 47: 44 GMT+0530 (+0530)',
      address:  ': : ffff: 172.18.0.109',
      xdomain:  false,
      secure:  false,
      issued:  1518772664725,
      url:  '/socket.io/?EIO=3&t=5e84d6d9cad6cfc3&type=passenger&id=26&transport=polling',
      query:    {
         EIO:  '3',
             t:  '5e84d6d9cad6cfc3',
             type:  'passenger',
             id:  '26',
             transport:  'polling' 
    } 
}

**Comment by TruckIT-Chan** [comment]
Hi chathuranga,
     I am encountering the same issue, were you able to find a solution for okhttp3 not working with AWS Sticky session?

**Comment by chaturanga836** [comment]
> Hi chathuranga,
> I am encountering the same issue, were you able to find a solution for okhttp3 not working with AWS Sticky session?

I guess.

I noted that AWS headers ignoring the okhttp3

**Comment by darrachequesne** [comment]
For future readers:

This was added in the documentation: https://socketio.github.io/socket.io-client-java/faq.html#How_to_use_with_AWS_Load_Balancing

Please reopen if needed.
