### ISSUE TITLE
Suggest me good practices for keep socket-io connected in Android oreo 

### ISSUE THREAD

**Issue by devidasm** [socketio/socket.io-client-java#504]
The background services are not supported any more in Android oreo (>26) . I want to socket keep connected in my chatting application even app is closed .
Please help me how can i implement new changes for android 26.

**Comment by JarnoVgr** [comment]
I ain't a pro dev. but keeping it connected in the background is bad practice. You could consider using push notifications and then loading the new messages once the app is opened again.

**Comment by darrachequesne** [comment]
For future readers:

I've added a note in the documentation: https://socketio.github.io/socket.io-client-java/android.html#How_to_keep_a_Socket.IO_client_running_in_the_background.3F

Please reopen if needed.
