### ISSUE TITLE
extraHeaders, forceWebsockets and connectParams in java client

### ISSUE THREAD

**Issue by robscovell** [socketio/socket.io-client-java#506]
Below is some working Swift code

            let socket = SocketIOClient.init(
                socketURL: URL(string: self.config.myBaseUrl)!,
                config: [.path("/my/path/listen"),
                         .extraHeaders(["authorization":"Bearer \(token)"]),
                         .forceWebsockets(true),
                         .connectParams(["requestId" : requestId, "siteId" : siteId]),
                         .log(true)])

How do I go about re-implementing this in Java on Android? extraHeaders, forceWebsockets and connectParams are all missing in the Java client.

**Comment by juniorfrogie** [comment]
Hi @robscovell , do you find solution to this one yet? I face the same issue.

**Comment by robscovell** [comment]
​Hi @Juniorfrogie,​

We changed things server-side to prevent this issue, so not really, sorry!

Rob

**Comment by juniorfrogie** [comment]
@robscovell I'm hoping for a better solution, since iOS already has this extraHeader and work fine. why don't they add to java too :(

**Comment by darrachequesne** [comment]
For future readers:

The `extraHeaders` option was added in version `2.0.0`: https://github.com/socketio/engine.io-client-java/commit/dfe65e3b3b5eab4c3fddb9dfbf53d684fe461043

Please reopen if needed.
