### ISSUE TITLE
Cannot Read data from the server

### ISSUE THREAD

**Issue by fedealessi96** [socketio/socket.io-client-java#507]
Hi everyone! I'm new in using socket.io and I'm trying to connect a Java client to a NodeJS server. 
Everything's fine when I send data Client to Server, but when I try to reply from the server I have some troubles. I have imported "io.socket.emitter.Emitter.Listener" library and I'm trying to handle the event "new message" (the message from the server) with a listener. What happens is that I cannot read data from the args parameter. I tried to look up for some examples but none of them worked on my code...
If you can help me it would be fine. Thank You.

Here's my Java Code, don't look at the form, just focus on the problem, if you can:

package com.github.nkzawa.socket.io_client;

import io.socket.emitter.*;
import io.socket.emitter.Emitter.Listener;

import java.net.MalformedURLException;
import java.net.URL;

import org.json.JSONArray;
import org.json.JSONObject;

import io.socket.client.IO;
import io.socket.client.Socket;

public class SocketService {
	private Socket msocket;
	private static final String ADDRESS = "localhost";
	private static final int PORT = 3001;
	
	private URL url;
	
	public SocketService(){
		try {
			this.url = new URL("http", ADDRESS, PORT, "");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		
	}
	
	public void connect(){
		try {
			msocket = IO.socket(url.toURI());
		}
		catch(Exception e){
			e.printStackTrace();
		}
		msocket.connect();
		msocket.on("new message", onNewMessage);
		msocket.on("disconnect", onDisconnect);
		
	
		
	}
	
	public void disconnect() {
        msocket.disconnect();
        msocket.close();
        msocket = null;
        
    }
	
	public void emit(String event, Object... args) {
        msocket.emit(event, args);
    }
	
	public void sendMessage(String s){
    	this.emit("message", s);
    }
	
	
	private Emitter.Listener onDisconnect = new Emitter.Listener() {
		
		 public void call(Object...args) {
	            System.out.println("Server disconnected");
	        }
	};
	
	**private Emitter.Listener onNewMessage = new Emitter.Listener() {
		
		public void call(Object...args) {
			JSONObject data = null;
			try{
				data = (JSONObject) args[0];
				String data1 = data.toString();
				System.out.println(data1);
			}catch(Exception e){
				System.out.println(e.getMessage());
			}
	}
};**
//---------
	
    public Socket getSocket(){
    	return this.msocket;
    }
   

	public String getUrl(){
		return this.url.toString();
	}
	
	
	
	
}

**Comment by venkat125** [comment]
Tried whole day with it. But Emitter.Listener never worked. Method not even getting triggered.

**Comment by yousafiqbal1994** [comment]
Any update on this issue please? I am facing the same problem :(

**Comment by venkat125** [comment]
Sorry, for late mentioning. It got resolved since there were issue in registering the connection. After which it got resolved. If u feel the same, please ensure your client got registered with the server where the socket producer is! Thanks all!

may be this [link ](https://github.com/socketio/socket.io-client-java/issues/268) might help.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
