### ISSUE TITLE
Socket java client disconnects and connects repeatedly

### ISSUE THREAD

**Issue by allMighto** [socketio/socket.io-client-java#509]
Hi, I've an issue where the sockets is repeatedly disconnecting and connecting to my nodeJs backend server every few seconds, upon connection

0|server   | DISCONNEDT
0|server   | connection establised with GwkLoFsdfdsf-ZAA3e
0|server   | DISCONNEDT
0|server   | connection establised with WN3CsdfpR_SZBAA3f
0|server   | DISCONNEDT

above is the log example ..

**Comment by PrasannaVenkadesh** [comment]
+1 I am also facing similar issue with Android client. I have my nodejs backend running with socket.io version 2.1.0 and java client 1.0.0. 

When I connect for the first time, I join user to their room, and as @allMighto mentioned it disconnects and reconnects frequently and because of which when it reconnects, the user is no more in that room which from the application's perspective is a bug.

**Comment by PrasannaVenkadesh** [comment]
Ok. Here is why it was happening so. **Socket.io** upgrades to websockets only when an upgrade from http is available. And I was serving my application via nginx as reverse proxy. I found out that I had to configure nginx to tell the client that the connection can be upgraded to websockets.

Earlier, I did not do that, so the client and server didn't negotiate on whether the connection was upgrade-able. Once I followed the configuration from nginx docs https://www.nginx.com/blog/websocket-nginx/ it works as expected without falling back to XHR polling method.

It was XHR polling why the connection was dropped and connected again.

**Comment by aman400** [comment]
+1

**Comment by darrachequesne** [comment]
For future readers:

I think this was due to the default readTimeout value of the OkHttp client (10 s). It must be increased:

```java
OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .readTimeout(1, TimeUnit.MINUTES) // important for HTTP long-polling
        .build();

IO.Options options = new IO.Options();
options.callFactory = okHttpClient;
options.webSocketFactory = okHttpClient;

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Please reopen if needed.
