### ISSUE TITLE
Cannot use HTTPS with websocket only transport

### ISSUE THREAD

**Issue by chitoadinugraha** [socketio/socket.io-client-java#516]
Socket IO keeps emmitting timeout when connecting to HTTPS server and using websocket transport.

**Comment by Yanivkl** [comment]
I encountered the same problem. Is there a solution for this issue

**Comment by PhonegapProjects** [comment]
Encountered Same problem any solution?

**Comment by rakave** [comment]
@qwe123wsx, @Yanivkl, @PhonegapProjects 

Try this : 

https://github.com/nkzawa/socket.io-android-chat/issues/19#issuecomment-419895684

**Comment by darrachequesne** [comment]
For future readers:

This was added in the documentation there: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.
