### ISSUE TITLE
Can't add extra headers like it is implemented on js or swift

### ISSUE THREAD

**Issue by Kolyall** [socketio/socket.io-client-java#520]
Add possibility to add `extraheaders` to start connection like it is implemented on js or swift

**Comment by muhammadnasr** [comment]
👍

**Comment by darrachequesne** [comment]
This was implemented in version `2.0.0`: https://github.com/socketio/engine.io-client-java/commit/dfe65e3b3b5eab4c3fddb9dfbf53d684fe461043

Reference: https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders
