### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress

### ISSUE THREAD

**Issue by Trainingnga** [socketio/socket.io-client-java#525]
Please help me guys to resolve this

**Comment by vokrut** [comment]
The same problem, i think it's needed to upgrade okhttp library inside socket.io from current version 3.8.1 to min 3.9.1.
https://github.com/square/okhttp/issues/3438

**Comment by darrachequesne** [comment]
This should be fixed since version `1.0.1`: https://github.com/socketio/engine.io-client-java/commit/8016a5d7462f9379b4ad0f5660188c8626319ca6

Please reopen if needed.
