### ISSUE TITLE
 onError: io.socket.engineio.client.EngineIOException: xhr post error

### ISSUE THREAD

**Issue by tugcekeser** [socketio/socket.io-client-java#526]
Hi,
I am getting "onError: io.socket.engineio.client.EngineIOException: xhr post error" error from Socket. I searched this error on the internet, but I could not find a solution to solve it. Could you please help me about this issue?

**Comment by tugcekeser** [comment]
Thanks for the comment @alemar11 . But, I am already using https.

**Comment by talsh87** [comment]
Suffer exactly from the same problem.
Seems like { transports: ["websocket"] } solves that, but not sure it's a good practice...

**Comment by tugcekeser** [comment]
Thanks for the comment @talsh87 . But, I am also already using { transports: ["websocket"] }

**Comment by tugcekeser** [comment]
Actually, I am getting this error only in production environment. Everything works fine in the development environment.

**Comment by chim0380** [comment]
I  had same problem. Problem was on server side in my case. 
Verify that you don't use **origin** on your server. 
For example 
`io.origins()  // remove this`

**Comment by Eleoglobal** [comment]
@tugcekeser pls can let me know how you solved this problem if you dont mind pls?
