### ISSUE TITLE
Connect is OK | Authentification is OK | But cookie seems to make fail create the room.

### ISSUE THREAD

**Issue by tjouin** [socketio/socket.io-client-java#528]
So here the thing i succed to connect, my server authentification is working, token is send and verify, but no listener seems to be attach. And connection broke.

`public class SocketIOManager {

    private static SocketIOManager instance;

    private Socket socket;

    private Context context;

    public static SocketIOManager get(Context context) {
        if (instance == null) {
            instance = getSync(context);
        }
        instance.context = context;
        return instance;
    }

    public static synchronized SocketIOManager getSync(Context context) {
        if (instance == null) {
            instance = new SocketIOManager(context);
        }
        return instance;
    }

    private SocketIOManager(Context context){
        this.context = context;
    }

    private void initServerSocket(Map<String, Emitter.Listener> handlers) {
        try {
            IO.Options mOptions = new IO.Options();
            mOptions.forceNew = true;
            mOptions.query = "__sails_io_sdk_version=0.12.13";
            socket = IO.socket(ServerConstants.ENDPOINT_DROP_LAST, mOptions);
            for (Map.Entry<String, Emitter.Listener> entry : handlers.entrySet()) {
                if (socket != null) {
                    socket.on(entry.getKey(), entry.getValue());
                }
            }
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }

    public void channel(final String emit, final Map<String, Object> options, final Handler confirmation, final String method, Map<String, Emitter.Listener> handlers) {
        initServerSocket(handlers);
        socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                try {
                    JSONObject jsonObject = new JSONObject();
                    jsonObject.put("url", emit);
                    JSONObject data = new JSONObject();
                    for (Map.Entry<String, Object> entry : options.entrySet()) {
                        data.put(entry.getKey(), entry.getValue());
                    }
                    jsonObject.put("data", data);
                    socket.emit(method, jsonObject);
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        });
        socket.on(Socket.EVENT_ERROR, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.d("SOCKET", "Error");
            }
        });
        socket.io().on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Transport transport = (Transport)args[0];

                transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                        @SuppressWarnings("unchecked")
                        Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
                        // modify request headers
                        headers.put("Authorization", Arrays.asList("**********"));
                        //headers.put("Cookie", Arrays.asList("__sails_io_sdk_version=0.12.13"));
                    }
                });

                transport.on(Transport.EVENT_RESPONSE_HEADERS, new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                        @SuppressWarnings("unchecked")
                        Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
                        // access response headers
                        String cookie = headers.get("Set-Cookie").get(0);
                    }
                });
            }
        });
        socket.connect();
    }

}
`

The error from server log : 

`Could not fetch session, since connecting socket has no cookie (is this a cross-origin socket?)
Generated a one-time-use cookie:sails.sid=s%3Avo387tzWW03pBLLlCfI5WGcZdnYnHMAJ.146NuxeaWw1YxBl2FW87kwLGNe8IdO7TSW3HCROEdFQand saved it on the socket handshake.
This will start this socket off with an empty session, i.e. (req.session === {})
That “anonymous” section will only last until the socket is disconnected unless you persist the session id in your database,
or by setting the set-cookie response header for an HTTP request that you *know* came from the same user (etc)
Alternatively, just make sure the socket sends a `cookie` header or query param when it initially connects.`

**Comment by zaiddabaeen** [comment]
Did you find a solution for this?

**Comment by tjouin** [comment]
No, backend try to upgrade Sails version to see if it work. But not working on this anymore, but still an issue !
