### ISSUE TITLE
Add the ability to set Options without recreating socket object

### ISSUE THREAD

**Issue by giperwlad** [socketio/socket.io-client-java#529]
Hello.

Now I can update connect options only through recreate Socket object:

      IO.socket("url", connectOptions)

So, all socket subscriptions disappear. 
In my case, I need update expired access token and reconnect to the socket without recreating socket object and subscriptions.

What about adding public method setOptions(Options opts) to Manager class. And then I do not have to recreate socket:

        public void setOptions(Options opts) {
        this.opts = opts;
        }

And after expiring access token on server, I will call this method:

        socket.disconnect();
        IO.Options connectOptions = new IO.Options();
        connectOptions.query = DataFields.AUTH_TOKEN + "=" + accessToken;
        connectOptions.path = "/test-socket";
        socket.io().setOptions(connectOptions);
        socket.connect();

Swift socket.io library allows you to do this. I want to see this in java =)

**Comment by romichandra** [comment]
#434

**Comment by darrachequesne** [comment]
For future readers:

This was added in the documentation there: https://socketio.github.io/socket.io-client-java/initialization.html#query

```java
socket.io().on(Manager.EVENT_RECONNECT_ATTEMPT, new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        options.query = "y=43";
    }
});
```

Please reopen if needed.
