### ISSUE TITLE
Copyright statement missing

### ISSUE THREAD

**Issue by etanhatch** [socketio/socket.io-client-java#531]
Could you please add a copyright statement and a link to the MIT license text you're using? Only stating "MIT" is not legally binding enough.

**Comment by etanhatch** [comment]
Seems to be in the LICENSE file but not in the README, could be added there too.

**Comment by darrachequesne** [comment]
For future readers:

The MIT license is listed both in the pom.xml file and in the README, so I think we are good.

Please reopen if needed.
