### ISSUE TITLE
Socket can not handle more than one transport type

### ISSUE THREAD

**Issue by omrital** [socketio/socket.io-client-java#533]
I am creating new socket instance with this definition:
**IO.Options.transports = new String[] {Polling.NAME, WebSocket.NAME}**

The socket always refer to the first option in the array, and in case that my connection is the second, in my case **WebSocket**, the socket failed to connect and I got an error:
**EngineIOException:  xhr poll error**

And the opposite:
In case that my connection is **Polling**, 
and my transporty options definition is:
**IO.Options.transports = new String[] { WebSocket.NAME, Polling.NAME}**
the socket failed to connect and I got an error:
**EngineIOException:  websocket error**

how can i define more then one transport type and the socket will connect to the correct option?

**Comment by CoolMind** [comment]
@omrital, you should write whole initialization on the socket (including IO.Options).

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
