### ISSUE TITLE
Is there any socket.io-java for server side?

### ISSUE THREAD

**Issue by bfang711** [socketio/socket.io-client-java#534]
In javascript, there are socket.io and socket.io-client, which I think the first is for server side. However in java, there is only this socket.io-client-java, no socket.io-java. Does it mean that there is no java version for the server side?

thanks

**Comment by JarnoVgr** [comment]
Not officially. You can use this server implementation for Java: https://github.com/mrniko/netty-socketio

**Comment by darrachequesne** [comment]
For future readers:

- https://github.com/mrniko/netty-socketio
- https://github.com/trinopoty/socket.io-server-java
-
