### ISSUE TITLE
connect socket.io android client through a reverse proxy server to socket server

### ISSUE THREAD

**Issue by baldraider** [socketio/socket.io-client-java#535]
I'm trying to connect to a socket.io server running behind a Nginx reverse proxy. I have Nginx proxy server running with https config `https://api.xxx.com`. The node js socket.io server is running on another server with http config `http://a.b.c.d:8081/app/v2`. 

In android side as a socket client, I'm using `implementation 'com.github.nkzawa: socket.io-client:0.3.0`.

Proxy is configured like this :
`proxy_pass http://a.b.c.d:8081/app/v2;`

While trying to connect the android app to socket like this 
`try {
            mSocket = IO.socket("https://api.xxx.com/app/v2/socketio/livefeed/");
        } catch (URISyntaxException e) {
            Log.d(TAG, String.valueOf(e));
        }
        mSocket.connect();`

The socket client is not connecting to the socket.io server.
How should I connect android socket client to socket server behind the proxy server?

**Comment by jorgepbarrera38** [comment]
Hola Lo pudiste solucionar?

**Comment by darrachequesne** [comment]
For future readers:

You need to use the `path` option:

```java
IO.Options options = IO.Options.builder()
        .setPath("/app/v2/socketio/livefeed/")
        .build();

Socket socket = IO.socket(URI.create("https://api.xxx.com"), options);
```

Reference: https://socketio.github.io/socket.io-client-java/initialization.html#path
