### ISSUE TITLE
Unable to use Transport Header

### ISSUE THREAD

**Issue by juniorfrogie** [socketio/socket.io-client-java#538]
I follow the document about adding extraHeader. Still cannot connect. My node server requires extraHeader in order to connect to socket. Does server side needs to add anything for android to work? Do you have any idea what is wrong? Here is my code:

try {
            mSocket = IO.socket("http://167.99.74.59:3000/message");
            mSocket.io().on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Transport transport = (Transport) args[0];
                    transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                        @Override
                        public void call(Object... args) {
                            @SuppressWarnings("unchecked")
                            Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
                            headers.put("x-user-id", Arrays.asList("5B59F68B7B7811E88C3E52964BF487E4;"));
                        }
                    });
                }
            });

        } catch (URISyntaxException e) {}

**Comment by darrachequesne** [comment]
For future readers:

You can now use the `extraHeaders` option:

```java
IO.Options options = IO.Options.builder()
        .setExtraHeaders(singletonMap("authorization", singletonList("bearer 1234")))
        .build();

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Reference: https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders

**Comment by faizannetsol** [comment]
> For future readers:
> 
> You can now use the `extraHeaders` option:
> 
> ```java
> IO.Options options = IO.Options.builder()
>         .setExtraHeaders(singletonMap("authorization", singletonList("bearer 1234")))
>         .build();
> 
> Socket socket = IO.socket(URI.create("https://example.com"), options);
> ```
> 
> Reference: https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders

What is the import type for builder()? Its not auto importing but asking from various Imports in Android studio. Also I am using 1.0.2 version as https://github.com/mrniko/netty-socketio only supports this version.
