### ISSUE TITLE
An error when i use the jar,please help me,thank you!

### ISSUE THREAD

**Issue by aizhilong** [socketio/socket.io-client-java#54]
## @nkzawa

I have added the socket.io-client-0.2.0.jar and engine.io-client-0.3.0.jar in my android application,when i run it,the server received a connection,but my application had some errors,then the application stoped.i have tried many times,but don't know why.Here is the errors:
1. "Could not find class 'com.github.nkzawa.engineio.client.transports.WebSocket$1', referenced from method com.github.nkzawa.engineio.client.transports.WebSocket.doOpen"
2. "FATAL EXCEPTION: EventThread"
3. "java.lang.NoClassDefFoundError:
   com.github.nkzawa.engineio.client.transports.WebSocket$1" and so on.
   ---
   
   Can you help me?Thank you very much.Here is my code:
   
   ```
   package com.example.cxv;
   import java.net.URISyntaxException;
   import android.app.Activity;
   import android.os.Bundle;
   import com.github.nkzawa.emitter.Emitter;
   import com.github.nkzawa.socketio.client.IO;
   import com.github.nkzawa.socketio.client.Socket;
   public class MainActivity extends Activity {
   private Socket socket;
   protected void onCreate(Bundle savedInstanceState) {
   super.onCreate(savedInstanceState);
   
   try {
       socket = IO.socket("http://10.110.138.103:8001");
   } catch (URISyntaxException e) {
       // TODO Auto-generated catch block
       e.printStackTrace();
   }
   socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
   
     @Override
     public void call(Object... args) {
       socket.emit("foo", "hi");
       socket.disconnect();
     }
   
   }).on("event", new Emitter.Listener() {
   
     @Override
     public void call(Object... args) {}
   
   }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
   
     @Override
     public void call(Object... args) {}
   
   });
   socket.connect();
   setContentView(R.layout.activity_main); 
           }
   ```

**Comment by matheszabi** [comment]
You need the Java-WebSocket-1.3.0.jar to be added to classpath
