### ISSUE TITLE
CloudFront blocks my socket io requests from Android app

### ISSUE THREAD

**Issue by lolipok** [socketio/socket.io-client-java#542]
If my cloudfront is enabled, i always have excepion : 
![image](https://user-images.githubusercontent.com/39791879/42930162-ee87e3b4-8b44-11e8-9e7c-4798d8698511.png)
How i can fix it?
(I must use CF to protect my server from DDOS)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
