### ISSUE TITLE
(HTTPLog)-Static: isSBSettingEnabled false Makes com.github.nkzawa.socketio.client.Socket Unable to Emit Successfully

### ISSUE THREAD

**Issue by jj-one** [socketio/socket.io-client-java#543]
I have faced a major setback in my Android project due to the inability of the wonderful Socket library, com.github.nkzawa.socketio.client.Socket, to successfully emit to Server whenever the following system info appears in the Logcat: 
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isShipBuild true
    (HTTPLog)-Thread-3690-989696862: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
    (HTTPLog)-Thread-3690-989696862: SMARTBONDING_FEATURE_ENABLED is false
    (HTTPLog)-Static: isSBSettingEnabled false
    KnoxVpnUidStorageknoxVpnSupported API value returned is false
    KnoxVpnUidStorageknoxVpnSupported API value returned is false
However, I have narrowed down the issue to be with Samsung devices only. Other devices work.
In my own situation, I am building on Android Studio 3.1, com.github.nkzawa.socketio.client.Socket 0.3.0 and NodeJS Server. The Emitting to Server and vice versa work perfectly on other devices. Also, it works perfectly on the same Samsung device if the logcat does not show the above info. However, once the above check is issued to the logcat by the devices, no server or client emitting is ever received. And once the problem has started, it continues even if the device is turned off and on again, even after uninstalling and reinstalling the app. 
The only way I managed to get it to work again without the above log is by doing Factory Reset on the device. After the Reset, it worked on the first install of the app but on subsequent tries, the same log came back and the issue started over again. 
I have tried every solution I could find on the Internet all to no avail.
Can somebody please, please, please, come for my rescue before I go crazy. It's really getting at me and has eaten so much into my time
Please, I seriously need help. Thanks.

I have tested on Samsung J3, Samsung J7 Prime and Infinix HOT 3.

**Comment by SaiedTrefiTester** [comment]
Are you trying to send data to local php server?

**Comment by Masouds97** [comment]
I want to do this and I have same problem.
what I must to do?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
