### ISSUE TITLE
Conflict with Retrofit

### ISSUE THREAD

**Issue by mecoFarid** [socketio/socket.io-client-java#546]
When I am establishing a socket connection to the server, all events are triggered properly. However, once I make a call to the server using Retrofit, no listener or emitter functions properly. At first, I thought Retrofit, somehow, terminates connections, but `socket.connected` returns true even after Retrofit finishes the job.

**Comment by MukFlex** [comment]
Add like this.
 implementation('io.socket:socket.io-client:1.0.0') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
