### ISSUE TITLE
Sockets get connect disconnect on every 10 seconds. 

### ISSUE THREAD

**Issue by gupta11** [socketio/socket.io-client-java#549]
> 08-09 20:35:54.630 13478-13478/ E/MYSOCKET: Emitted onDisconnect : 
> 08-09 20:35:56.339 13478-13478/ E/MYSOCKET: Emitted onConnect : 
> 08-09 20:36:06.347 13478-13478/ E/MYSOCKET: Emitted onDisconnect : 
> 08-09 20:36:07.313 13478-13478/ E/MYSOCKET: Emitted onConnect : 
> 08-09 20:36:17.327 13478-13478/ E/MYSOCKET: Emitted onDisconnect : 
> 08-09 20:36:19.076 13478-13478/ E/MYSOCKET: Emitted onConnect : 
> 

I am checking on Android O. Also I have used gradle version 1.0.0. 
If i downgrade the version to 0.8.3 then it just gets connected to server, but other opened channels data are not coming.

**Comment by yehudaSt** [comment]
Hi, I am having the same issue, Are there any updates on this bug?

**Comment by danielehrhardt** [comment]
Hi i am having the Same Issue

**Comment by darrachequesne** [comment]
For future readers:

I think this was due to the default readTimeout value of the OkHttp client (10 s). It must be increased:

```java
OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .readTimeout(1, TimeUnit.MINUTES) // important for HTTP long-polling
        .build();

IO.Options options = new IO.Options();
options.callFactory = okHttpClient;
options.webSocketFactory = okHttpClient;

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

See also: https://github.com/socketio/engine.io-client-java/commit/fb531fab30968a4b65a402c81f37e92dd5671f33

Please reopen if needed.
