### ISSUE TITLE
An error when i use the jar in android application,please help me,thank you!

### ISSUE THREAD

**Issue by aizhilong** [socketio/socket.io-client-java#55]
## @nkzawa

I have added the socket.io-client-0.2.0.jar and engine.io-client-0.3.0.jar in my android application,when i run it,the server received a connection,but my application had some errors,then the application stoped.i have tried many times,but don't know why.Here is the errors:
1. "Could not find class 'com.github.nkzawa.engineio.client.transports.WebSocket$1', referenced from method com.github.nkzawa.engineio.client.transports.WebSocket.doOpen"
2. "FATAL EXCEPTION: EventThread"
3. "java.lang.NoClassDefFoundError:
   com.github.nkzawa.engineio.client.transports.WebSocket$1" and so on.
   ---
   
   Can you help me?Thank you very much.Here is my code:
   
   ```
   package com.example.cxv;
   import java.net.URISyntaxException;
   import android.app.Activity;
   import android.os.Bundle;
   import com.github.nkzawa.emitter.Emitter;
   import com.github.nkzawa.socketio.client.IO;
   import com.github.nkzawa.socketio.client.Socket;
   public class MainActivity extends Activity {
   private Socket socket;
   protected void onCreate(Bundle savedInstanceState) {
   super.onCreate(savedInstanceState);
   
   try {
       socket = IO.socket("http://10.110.138.103:8001");
   } catch (URISyntaxException e) {
       // TODO Auto-generated catch block
       e.printStackTrace();
   }
   socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
   
     @Override
     public void call(Object... args) {
       socket.emit("foo", "hi");
       socket.disconnect();
     }
   
   }).on("event", new Emitter.Listener() {
   
     @Override
     public void call(Object... args) {}
   
   }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
   
     @Override
     public void call(Object... args) {}
   
   });
   socket.connect();
   setContentView(R.layout.activity_main); 
           }
   ```

**Comment by UmaYalanati** [comment]
I am also facing same problem.can you please explore the solution..........

**Comment by aizhilong** [comment]
I solved my problem using  socket.io-client-0.3.0, engine.io-client-0.3.1, Java-WebSocket-1.3.0，have you try this way?

**Comment by aizhilong** [comment]
@UmaYalanati , i solved my problem socket.io-client-0.3.0, engine.io-client-0.3.1, Java-WebSocket-1.3.0.Have you try this way?

**Comment by chitranshmathur01** [comment]
Hi,

@nkzawa & @aizhilong : I'm using the same way as you've already described. But still I'm not sure that my socket is connecting or not. How to check socket is connected ? I'm getting "OPENING" readyState in my debugging using your WebRTC API.

My code snippet:
```
MessageHandler messageHandler = new MessageHandler();
try {
            socket = IO.socket(host);
            socket.connect();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        **socket.on("new-channel", messageHandler.newChannel);**

// This is my MessageHandler class

private class MessageHandler {
private Emitter.Listener newChannel = new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.i("newChannel", "newChannel: " + args[0]);
            }
        };
}
```
Now I'm not getting socket status inside newChannel listner.

**Comment by ArbelaezCamila** [comment]
any solution?

**Comment by tomtomazs** [comment]
Hello, 

I have a problem whith my project, i have two error : - cannot find the class file for com.github.nkzawa.emitter.Emitter. Fix the build path then try to building this project.
- the type com.github.nkzawa.emitter.Emitter cannot be resolved. It is indirectly referenced from required .class file.

i'm using only this library : java-json.jar, socket.io-client-0.6.0.jar, engine.io-client-java-engine.io-client-0.6.0.jar
Can you help me pls ?
thanks.
