### ISSUE TITLE
Upload and download size are the same

### ISSUE THREAD

**Issue by abouroubi** [socketio/socket.io-client-java#550]
Hello,

I'm using Socket.io on an Android application to send blobs to server.
When I start the app on android studio and start profiling the network usage, I noticed that the upload and the download sizes are the same, multiple MB/s.
It's normal for the upload, I'm sending lot of data, but I don't understand why I have that much download, as I'm not supposed to receive anything.

Is it the normal behavior of socket.io ? Is there any config I can use to stop the download ?

Thanks.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
