### ISSUE TITLE
Not working on Android 8.0+ due to SELinux issues

### ISSUE THREAD

**Issue by RobertoBiundo** [socketio/socket.io-client-java#554]
I'm getting an error on the logs when using socketIO on Android 9.0 (or 8.0+)

    W/TcmReceiver: type=1400 audit(0.0:136495): avc: denied { write } for name="tcm" dev="tmpfs" ino=30445 scontext=u:r:untrusted_app:s0:c242,c256,c512,c768 tcontext=u:object_r:dpmtcm_socket:s0 tclass=sock_file permissive=0

Android Code:

    socket = IO.socket("http://192.168.0.101:3000");
    socket.connect();

After some research it seems to be related to access permission with the SELinux enforcement in Android. This causes the underlying socket in the SocketIO library to not be able to open or read.

As a note
I do have the Internet permissions enabled. So that does nos seem to be the problem

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

Any Solutions?

**Comment by RobertoBiundo** [comment]
Ok, so far the only solution that I have is to change the SELinux and rebuild the ROM. This is absolutely not useful since I was planing in making an App for the Google Play store. Any suggestions? If not ill drop the usage of Socket.IO and actually the whole sockets idea and go back to HTTP polling requests every second to get the data that I want (really not a nice option)

**Comment by RobertoBiundo** [comment]
Well it does not seem to be an Android issue. Actually opening a tcp socket directly works. Something like opening an MQTT connection seems to be an option.
I see that Socket.IO is using a library for web sockets. Could this be the think that Android is blocking?
I may end up doing a fork of the project

**Comment by aayushanand99** [comment]
How did you solve this issue @RobertoBiundo ?

**Comment by darrachequesne** [comment]
For future readers:

Please check the documentation here: https://socketio.github.io/socket.io-client-java/android.html#How_to_reach_an_HTTP_server.3F

Please reopen if needed.
