### ISSUE TITLE
Exception while connecting "java.net.MalformedURLException: unknown protocol: wss"

### ISSUE THREAD

**Issue by aalap03** [socketio/socket.io-client-java#555]
My Socket url is of form `"wss://socket-..."` and inside that I want to subscribe to the channel of form `"myChannel.website.com"`

I am using this code to connect to the channel but it gives `java.net.MalformedURLException: unknown protocol: wss` error.

    try {
            socket = IO.socket(SERVER_URL + cobaltStore.getToken());
            socket.connect();
            Log.d(TAG, "testSocket: connected? "+socket.connected());
            socket.on(channel, args -> {
                for (Object arg : args) {
                    Log.d(TAG, "testSocket: call: " + arg);
                }
            });

        } catch (Exception e) {
            e.printStackTrace();
            Log.d(TAG, "testSocket: "+e.getLocalizedMessage());
        }

Please let me know what I am doing wrong and guide me to the correct way to connect to the socket and channel.

**Comment by darrachequesne** [comment]
For future readers: this should be fixed by https://github.com/socketio/socket.io-client-java/commit/67fd5f34a31c63f7884f82ab39386ad343527590, included in version `2.0.1`.
