### ISSUE TITLE
new connection problem

### ISSUE THREAD

**Issue by HassanChiang** [socketio/socket.io-client-java#556]
https://github.com/socketio/socket.io-client-java/blob/964a66fc1c57042a37301ec426ffef266bfc0f56/src/main/java/io/socket/client/IO.java#L72

In this line , the last condition  " || sameNamespace"，Why is not this code "|| !sameNamespace" ？Is this a bug ?

**Comment by darrachequesne** [comment]
For future readers:

This is the expected behavior. Calling `IO.socket()` twice for the same namespace will create two socket instances and two managers.

Please reopen if needed.
