### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Rimander** [socketio/socket.io-client-java#557]
What is the version in Android and Nodejs to work?

**Comment by Harin-Kaklotar** [comment]
I have no idea about Nodejs but **io.socket:socket.io-client:1.0.0** work perfectly on android

**Comment by Rimander** [comment]
Android Version?
Me > 8.1

**Comment by JarnoVgr** [comment]
Socket.io works fine on newer Android devices. However, there are apparently problems with background jobs.

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socketio.github.io/socket.io-client-java/installation.html
