### ISSUE TITLE
Socket IO wont connect on Oreo, even when my background service is running

### ISSUE THREAD

**Issue by huzain07** [socketio/socket.io-client-java#560]
Socket IO wont connect to my server when i install my app on oreo device, but my background service is working properly.

**Comment by eddydn** [comment]
android:usesCleartextTraffic="true"
Hii ! Please add this line to your <application> tag in Android Manifest

From EDMTDev ^^

**Comment by Krypt0n** [comment]
--- issue should be closed

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socketio.github.io/socket.io-client-java/android.html#How_to_reach_an_HTTP_server.3F

Please reopen if needed.
