### ISSUE TITLE
Error: websocket error

### ISSUE THREAD

**Issue by jingfreeks** [socketio/socket.io-client-java#563]
hello guys,

I try to create a connection using sockets.io client. it work on the ios however in the android it has a message shows websocket error

here is my code
var socket = io('https://localhost:8888',{transports: ['websocket'],rejectUnauthorized:false,secure:true});

version

"socket.io": "^2.1.1",
"socket.io-client": "^2.1.0"
is there a configuration in the android where I can fix this error/

thak you

**Comment by Luomusha** [comment]
+1

**Comment by Krypt0n** [comment]
check issue guidlines e.g.: https://github.com/necolas/issue-guidelines
--- issue should be closed

**Comment by xingzjx** [comment]
+1

**Comment by darrachequesne** [comment]
For future readers:

Please check the example here: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.

**Comment by ABOBAKAR-IT** [comment]
on remote server config the nginx

server  

{ 
       server_name backend.me; 

       location /{ 
             #  proxy_set_header X-Real-IP $remote_addr; 
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
               proxy_set_header Host $host; 
             #  proxy_set_header X-NginX-Proxy true; 
                proxy_pass http://localhost:4000/; 
                         proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
             #  proxy_redirect http://localhost:5000/ https://$server_name/;       
       } 
}
