### ISSUE TITLE
java.io.IOException: 400

### ISSUE THREAD

**Issue by afeijackcool** [socketio/socket.io-client-java#564]
I want to use URI like this http://ip:port/{path} 
this {path} in javascript socket.io client is the options path
but it not work , i got an error : java.io.IOException: 400

**Comment by Krypt0n** [comment]
check issue guidlines e.g.: https://github.com/necolas/issue-guidelines
--- issue should be closed

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
