### ISSUE TITLE
Sending a String Ack which looks like a JSON is stringified

### ISSUE THREAD

**Issue by oliverhausler** [socketio/socket.io-client-java#567]
I receive an event and respond to the Ack:
```
socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    Ack ack = (Ack) args[args.length - 1];
    ack.call("answer");
  }
});
```

If `answer` is a String which looks like a JSON, like `{"data":[]}`, 
the library seems to change it to `{\"data\":[]}` and sends it to the server like this.

Why is an Object type String not treated like such? Is this a bug, or what do I need to do if I want to control serialization/deserialization in my app.

**Comment by symoN5** [comment]
You can do it like this: 

	socket.on("foo", new Emitter.Listener() {
		@Override
		public void call(Object... args) {
			Ack ack = (Ack) args[args.length - 1];

			JSONObject obj = new JSONObject();
			try {
				obj.put("data", "[]");
				ack.call(obj);
			} catch (JSONException e) {
				e.printStackTrace();
			}
		}
	});

If you escape it correct you can do it with String

	mSocket.on("foo", new Emitter.Listener() {
		@Override
		public void call(Object... args) {
			Ack ack = (Ack) args[args.length - 1];

			String s = "{\"data\":[]}";
			ack.call(s);
		}
	});

**Comment by oliverhausler** [comment]
@symoN5 Thanks. Yes, I realized it's possible to do that, but this makes no sense to me. The library behaves different for emitting an event and for Ack. In Ack, it modifies the String I send for no apparent reason. This leads to errors.

- If an input is invalid, a program should throw.
- If an input is valid, it should accept and transport it unmodified.

Trying to be smart is not appropriate here. It would be better to provide custom handlers for handling input and output formats.

**Comment by darrachequesne** [comment]
For future readers:

I wasn't able to reproduce the issue:

```java
public class Fiddle {

    public static void main(String[] argz) throws Exception {
        IO.Options options = new IO.Options();

        Socket socket = IO.socket(URI.create("http://localhost:3000"), options);

        socket.on(Socket.EVENT_CONNECT, (__) -> {
            System.out.println("connect");
        });

        socket.on(Socket.EVENT_CONNECT_ERROR, (args) -> {
            System.out.println("connect_error: " + args[0]);
        });

        socket.on(Socket.EVENT_DISCONNECT, (args) -> {
            System.out.println("disconnect due to: " + args[0]);
        });

        socket.on("foo", new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Ack ack = (Ack) args[args.length - 1];
                ack.call("{\"data\":[]}");
            }
        });

        socket.connect();
    }
}
```

JS server:

```js
io.on("connection", (socket) => {
  socket.emit("foo", (arg) => {
    console.log(arg);
  })
});
```

Output:

```
{"data":[]}
```

Please reopen if needed.
