### ISSUE TITLE
Add Window level ( change contrast / Brightness of view )effect on image (JPEG) in flutter development

### ISSUE THREAD

**Issue by vksBhardwaj** [socketio/socket.io-client-java#569]
We are creating a Healtcare product. in which we are usin DICOM images for **web**. But when we try to make Mobile Apps then we can use DICOM images due to high size. so we are using jpeg image here. and its very difficult to implement all effect on jpeg image like DICOM images. so can anyone suggest me proper solution to implemnt Window effect( increase or decrease contrast/Brightness) of image

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
