### ISSUE TITLE
Use websocket only on android

### ISSUE THREAD

**Issue by Upd4ting** [socketio/socket.io-client-java#572]
Hello, i'm using this code client side to connect on my clusterised socket io server

`socketio = SocketIO.connect('http://IP/app', { query: 'token=' + token, forceNew: true, secure: false, android: { transports: ['websocket', 'polling'], }, ios: { transports: ['websocket', 'polling'], forceWebsockets: true, } });`
But even with that my server receive connection trying to use polling and trigger a transport error because polling with clustering isn't compatible. How can I ensure that my client won't try polling at all?

I'm using nativescript socket io plugin that just link to this client for android

**Comment by HerculanoGripp** [comment]
@Upd4ting you need to pass an object with the connections options the same way as in the javascript client. Try to do that: 

`
IO.Options options = new IO.Options();
options.transports = new String[] { WebSocket.NAME, Polling.NAME};
Socket socket = IO.socket(http://url-server", options);
`

**Comment by Upd4ting** [comment]
That's what i'm already doing :/

**Comment by HerculanoGripp** [comment]
I'm using this and works for me. Maybe the problem is the clustering configuration, try test node multi core with pm2 in cluster mode.
Check this articles:

1. [Socket.io node multi cores](https://medium.com/@codeandcam/clustering-an-express-socket-io-server-with-pm2-789d11865f95)
2. [Socket.io node cluster](https://socket.io/docs/using-multiple-nodes/#Using-Node-JS-Cluster)

**Comment by csi-stasik** [comment]
I have the same problem. Even I force the client to use only websocket, on server I get always: `engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&token=x"` - polling

**Comment by darrachequesne** [comment]
For future readers:

Using the `transports` option should work:

```java
IO.Options options = IO.Options.builder()
        .setTransports(new String[] { WebSocket.NAME })
        .build();

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Reference: https://socketio.github.io/socket.io-client-java/initialization.html#transports

Please reopen if needed.
