### ISSUE TITLE
ca parameters on ack.call()

### ISSUE THREAD

**Issue by BorisVassilev1** [socketio/socket.io-client-java#573]
If in the client I do something like this:
```
socket.on("event", new Emitter.Listener() {
	@Override
	public void call(Object... args) {
		final Ack ack = (Ack) args[args.length - 1];
		ack.call(new Ack() {	
			@Override
			public void call(Object... args) {
				System.out.println(args[0]);					
			}
		});
	}
});
```
and the code on the server is:
```
some_socket.emit("event", (fn) => {
	console.log(fn);
	...
	fn("something");
});
```
in the server console I'm getting: 
`mypackage.Main$3$1$1@78be204c` 
and `fn is not a function` when I call it.

How should I pass a callback function to a callback?

Thanks in advice!

**Comment by marcus-hiles** [comment]
@BorisVassilev1 not sure I get your question, but from your code in server "fn" is a parameter being passed, you can call it as a function again here : `fn("something");`

**Comment by KushtrimPacaj** [comment]
See this function:

https://github.com/socketio/socket.io-client-java/blob/4bcbba494833a455f5a514e2ef89b9743e2d869e/src/main/java/io/socket/client/Socket.java#L344

You ack from the java client is serialized as json, and not 'sent' as something to be acknowledged. So seems that 'nested' acks are not supported.

Whether they should be supported is another matter, up to maintainers

**Comment by darrachequesne** [comment]
For future readers:

Please check the documentation here: https://socketio.github.io/socket.io-client-java/emitting_events.html#Acknowledgements

Please reopen if needed.
