### ISSUE TITLE
Issues with AWS Load balancing and sticky sessions

### ISSUE THREAD

**Issue by drofnnuD** [socketio/socket.io-client-java#574]
We are using an Application Load Balancer, this has session stickiness enabled, but for some reason it doesn't keep the android session stickiness, it places me in between two servers so I'm constantly disconnecting and reconnecting.

I know this has been raised beforehand but has anyone managed to solve the issue? Is there a fix for it anywhere?

**Comment by AndyGOBrien** [comment]
#524

**Comment by marcus-hiles** [comment]
Hi @AndyGOBrien , not sure if this solves the issue?

**Comment by darrachequesne** [comment]
For future readers:

This was added in the documentation: https://socketio.github.io/socket.io-client-java/faq.html#How_to_use_with_AWS_Load_Balancing

Please reopen if needed.
