### ISSUE TITLE
problem with com.github.nkzawa.emitter.Emitter

### ISSUE THREAD

**Issue by tomtomazs** [socketio/socket.io-client-java#578]
Hello,

I have a problem whith my project, i have two error : 

- cannot find the class file for com.github.nkzawa.emitter.Emitter. Fix the build path then try to building this project.

- the type com.github.nkzawa.emitter.Emitter cannot be resolved. It is indirectly referenced from required .class file.

i'm using only this library : java-json.jar, socket.io-client-0.6.0.jar, engine.io-client-java-engine.io-client-0.6.0.jar

Can you help me pls ?
thanks.

**Comment by tomtomazs** [comment]
It's Okay i resolved this problem

**Comment by yuyu88** [comment]
How are you resolve this problem ?

**Comment by darrachequesne** [comment]
That should be fixed in latest version, please reopen if needed.
