### ISSUE TITLE
How to add Headers  when connect Socket Server?

### ISSUE THREAD

**Issue by QiaoxgChina** [socketio/socket.io-client-java#581]
Like the title: How to add Headers  when connect Socket Server? My SocketIo version is 1.0.0 for android ,Somebody help me ,thanks!

**Comment by DiegoRicardoValdiviaArreola** [comment]
Look at the documentation here: [https://github.com/socketio/socket.io-client-java#transports-and-http-headers](url).

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders
