### ISSUE TITLE
all sockets of mine 's socket.id are the same one

### ISSUE THREAD

**Issue by m26597** [socketio/socket.io-client-java#583]
At first , everything works. But now , I don't know what happened that causes all the socket.id are the same. Could somebody help give me some clues? Thanks.

**Comment by m26597** [comment]
I'm thinking that this issue I accounted is so amazing  that maybe it's hard for  anybody  to achieve this goal.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
