### ISSUE TITLE
Confusing README.md

### ISSUE THREAD

**Issue by Amityville-DE** [socketio/socket.io-client-java#587]
Hi everyone, I think the README.md is a bit confusing at the moment.
Is socket.io 2.0 supported or not? The description says "1.x and later" the Readme "1.x".
Maybe there could be some clarification. Thanks :)

**Comment by micaelgallego** [comment]
Same confusion here!

**Comment by twofingerrightclick** [comment]
For posterity/ so you can close this issue -> I added a pull request about this documentation error. Hopefully one of the moderators will take. https://github.com/socketio/socket.io-client-java/pull/639

**Comment by darrachequesne** [comment]
For future readers, Socket.IO `2.0` and `3.0` are now supported. Please see the compatibility table here: https://socketio.github.io/socket.io-client-java/installation.html

**Comment by micaelgallego** [comment]
👏👏👏👏👏
