### ISSUE TITLE
Variable length of args.length 

### ISSUE THREAD

**Issue by crearo** [socketio/socket.io-client-java#589]
The length of args returned isn't predictable. At times, it includes both the "message" tag `(args[0])` and a json object `(args[1])` (the actual message from server). Sometimes, just the json object is received as the first arg with no "message" tag.

    on(Socket.EVENT_MESSAGE, args -> {
        Timber.d("Message from client received: " + args.length);
        for (int i = 0; i < args.length; i++) {
            Timber.d("Args: " + (i + 1) + " " + args[i] + " " + args[i].getClass().getName());
        }
    });

I've noticed the 2 args come for messages where the server sends a message in/right after the `CONNECT` event. For the rest, I just 1 arg.

Why does this happen? Is this a known/expected?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
