### ISSUE TITLE
Is this plugin still active?

### ISSUE THREAD

**Issue by jannomeister** [socketio/socket.io-client-java#591]
I see `socket.io-client-swift` updated last 4months. But for java it's only update for the last 2 years :(

**Comment by b95505017** [comment]
Maybe it's time for `socket.io-client-kotlin` 🤓

**Comment by kde99** [comment]
No update in the last year seems kinda dead to me. I would love to see a kotlin version too though. Even the C version gets more love.

**Comment by darrachequesne** [comment]
Starting from now, I should be more active on this repository.

Could you please ping me on issues that you would like to see fixed/worked on? Thanks!
