### ISSUE TITLE
set proxy 

### ISSUE THREAD

**Issue by arem94** [socketio/socket.io-client-java#597]
hi 
how can i set proxy for connection
in version 0.8.3 i set it like below

`  IO.Options opts = new IO.Options();
      opts.transports = new String[]{WebSocket.NAME};
      opts.forceNew = false;
      opts.reconnectionAttempts = 600;
      opts.reconnectionDelay = 1000;
      opts.reconnection = true;
      opts.proxy = Proxy.NO_PROXY;`

but in new version opts.proxy is  remove from IO.Options
how resolve it?

**Comment by IvenZ** [comment]
OkHttpClient client = new OkHttpClient.Builder().proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("10.128.9.30", 80))).build();

**Comment by IvenZ** [comment]
> OkHttpClient client = new OkHttpClient.Builder().proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("10.0.0.1", 80))).build();

**Comment by IvenZ** [comment]
OkHttpClient client = new OkHttpClient.Builder().proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("10.0.0.1", 80))).build();

**Comment by IvenZ** [comment]
OkHttpClient client = new OkHttpClient.Builder().proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("10.0.0.1", 80))).build();
IO.Options options = new IO.Options();
options.webSocketFactory = client;
options.callFactory = client;

socket = IO.socket("http://localhost", options);
