### ISSUE TITLE
maven support?

### ISSUE THREAD

**Issue by Amandine95** [socketio/socket.io-client-java#598]
how to use in a maven project?

**Comment by erlangp** [comment]
https://mvnrepository.com/artifact/io.socket/socket.io-client

```xml
<dependency>
    <groupId>io.socket</groupId>
    <artifactId>socket.io-client</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Comment by darrachequesne** [comment]
Documentation was added here: https://socketio.github.io/socket.io-client-java/installation.html
