### ISSUE TITLE
toString result from org.json is not reliable

### ISSUE THREAD

**Issue by leftstick** [socketio/socket.io-client-java#599]
I have the following code:

```java
Map<String, String> authData = new HashMap<String, String>();
authData.put("token", "asdfgh");

socket.emit("auth", authData, new Ack() {
    @Override
    public void call(Object... authCode) {
       System.out.println(authCode);
    }
});
```

Once running with a simulator, the callback `Ack` never get called. After a few minutes debugging, i found it is a server deserialization error whenever receiving the data from client-side.

See [encodeAsString](https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/parser/IOParser.java#L63), it's actually `obj.data.toString()`, and `obj.data` is type of `JSONArray`.

If you see the below test case:

```java
@Test
public void checkOrgJson() throws JSONException {

	Map<String, String> authData = new HashMap<String, String>();
	authData.put("token", "asdfgh");

	JSONArray arr = new JSONArray();
	arr.put("auth");
	arr.put(authData);

	Assert.assertEquals("[\"auth\",{\"token\":\"asdfgh\"}]", arr.toString());
	// in Android env: ["auth","{token=asdfgh}"]
}
```

The case will be failed in Android env.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
