### ISSUE TITLE
PingInterval / Heartbeat ?

### ISSUE THREAD

**Issue by Alex--Kang** [socketio/socket.io-client-java#60]
Hi,
I'm just wondering if there is a way to set the pingInterval/pingTimeout or heartbeat ?
The reason I asked is because I noticed that the socket disconnect/re-connect for every 55 seconds. 
( It reconnects successfully )

Big thanks,
Alex

**Comment by drakula84** [comment]
@nkzawa Why does it disconnect and reconnects continuously? I am running it at a background service and expect to have a permanent connection to the server but observing disconnect/reconnect every so often. Any solution to have a permanent connection?
