### ISSUE TITLE
Sub directory can not connect，help me

### ISSUE THREAD

**Issue by beibe218** [socketio/socket.io-client-java#603]
### socket.io can not connect
GET /swap/realTime/?EIO=3&transport=websocket HTTP/1.1
Origin: https://swap1.evewancpa.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: +WHFo9B6yNPPHo0CNDigUg==
Sec-WebSocket-Version: 13
Host: swap1.evewancpa.com
Accept-Encoding: gzip
User-Agent: okhttp/3.14.2
x-forwarded-for: 192.168.11.2

### websocket test tool Can connect
GET /swap/realTime HTTP/1.1
Host: swap1.evewancpa.com
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Linux; Android 9; HMA-AL00 Build/HUAWEIHMA-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.64 HuaweiBrowser/10.0.1.333 Mobile Safari/537.36
Upgrade: websocket
Origin: https://swap1.evewancpa.com
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,en-GB;q=0.9,ms-MY;q=0.8,zh-HK;q=0.7,fr-FR;q=0.6,en-US;q=0.5
Sec-WebSocket-Key: kl3FQBshQ/EoXB2esKfAXw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
x-forwarded-for: 192.168.11.2

**Comment by beibe218** [comment]
### This is web testing url
wss://swap1.evewancpa.com/swap/realTime

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
