### ISSUE TITLE
There is no "on" method in socket object

### ISSUE THREAD

**Issue by chaitanya1999** [socketio/socket.io-client-java#604]
The documentation is obsolete. There is no "on" method in the Socket object.

**Comment by KushtrimPacaj** [comment]
Socket extends Emitter, and there is on method in Emitter. See:

https://github.com/socketio/socket.io-client-java/blob/4bcbba494833a455f5a514e2ef89b9743e2d869e/src/main/java/io/socket/client/Socket.java#L24

https://github.com/socketio/engine.io-client-java/blob/559eb38de17a4a4045a56f1da6c642dfb7e53abe/src/main/java/io/socket/emitter/Emitter.java#L28

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
