### ISSUE TITLE
Cleartext HTTP traffic not permitted on android 9

### ISSUE THREAD

**Issue by hieuhtgc00378** [socketio/socket.io-client-java#606]
i'm using this library to develop a realtime messaging application for android, I've tested the app on android version 8.1,7.1 and the app running like charm, but for android 9.1 emulator I get this ERROR: Cleartext HTTP traffic to {my local machine ip address} not permitted

**Comment by rmasarovic** [comment]
add to your app manifest android:usesCleartextTraffic="true" or set android:networkSecurityConfig="@xml/network_security_config"

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socketio.github.io/socket.io-client-java/android.html#How_to_reach_an_HTTP_server.3F

Please reopen if needed.
