### ISSUE TITLE
Cannot connect to socket-io flask server from my Android Application

### ISSUE THREAD

**Issue by ionkarolos** [socketio/socket.io-client-java#615]
Hello everyone,

I am trying to establish socket-io connection between my Android App and a remote flask-socket-io server. My code is very simple and looks like this:

```
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import io.socket.client.IO;
import io.socket.client.Socket;
import java.net.URISyntaxException;

import android.view.View;
import android.widget.*;
import io.socket.emitter.Emitter;


public class MainActivity extends AppCompatActivity {

    private Socket mSocket;
    {
        try {
            mSocket = IO.socket("http://192.168.0.13:5000/");
        } catch (URISyntaxException e) {

        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mSocket.on(Socket.EVENT_CONNECT, onConnect);
        mSocket.connect();
    }

    private Emitter.Listener onConnect = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
          runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getApplicationContext(), mSocket.id(), Toast.LENGTH_SHORT).show();
                }
            });
        }
    };
}
```

But unfortunateely nothing happens.. No Socket.id returns... And also nothing happens on flask server command line... Could you please provide me some help; Thanking you in advance

**Comment by twofingerrightclick** [comment]
Your problem probably is because socket.io 3.0 server is not supported. Check which version of socket.io module you have for your flask app. I added a pull request about this. Hopefully one of the moderators will take. https://github.com/socketio/socket.io-client-java/pull/639

**Comment by darrachequesne** [comment]
For future readers:

Please check the compatibility table here: https://socketio.github.io/socket.io-client-java/installation.html

Please reopen if needed.
