### ISSUE TITLE
Disconnect problems when running more than 4 Java clients on same JVM

### ISSUE THREAD

**Issue by sameertj** [socketio/socket.io-client-java#618]
I am unable to keep more than 4 stable Socket.Io client connections in my test scenario. With more than 4 clients the clients keep disconnecting and trying to reconnect.

For more context the server and clients are Java based and are running on the same JVM

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socketio.github.io/socket.io-client-java/faq.html#How_to_create_a_lot_of_clients

Please reopen if needed.
