### ISSUE TITLE
Disconnect - transport error

### ISSUE THREAD

**Issue by shivaanshi** [socketio/socket.io-client-java#624]
I am getting a disconnect transport error every time if I use pooling, it is only working with WebSocket but not with default options.

**Comment by CoolMind** [comment]
I also had this error, but not sure it was because of pooling. See my comment in https://github.com/socketio/socket.io-client-java/issues/625 to initialize socket.

**Comment by darrachequesne** [comment]
For future readers:

I think this was due to the default readTimeout value of the OkHttp client (10 seconds). It must be increased:

```java
OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .readTimeout(1, TimeUnit.MINUTES) // important for HTTP long-polling
        .build();

IO.Options options = new IO.Options();
options.callFactory = okHttpClient;
options.webSocketFactory = okHttpClient;

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

See also: https://github.com/socketio/engine.io-client-java/commit/fb531fab30968a4b65a402c81f37e92dd5671f33

Please reopen if needed.
