### ISSUE TITLE
How to emit multiple arguments in a single emit?

### ISSUE THREAD

**Issue by arslanaka** [socketio/socket.io-client-java#631]
Hi, I've been trying to emit multiple arguments before the callback function in JAVA (Android) but unfortunately, I cannot emit more than one argument/Object. However, I can emit as many args as much I want in my server.js file. 

     ` socket.emit({"create","authentication",
      email : "shahvaiz@gmail.com",
      password: "123456",
      strategy: "jwt"
       });`

**Comment by letuananh035** [comment]
You must try emit Json

```
// Sending an object
JSONObject obj = new JSONObject();
obj.put("hello", "server");
obj.put("binary", new byte[42]);
socket.emit("foo", obj);

// Receiving an object
socket.on("foo", new Emitter.Listener() {
  @Override
  public void call(Object... args) {
    JSONObject obj = (JSONObject)args[0];
  }
});
```

**Comment by darrachequesne** [comment]
You should be able to send any number of arguments:

```java
JSONObject obj = new JSONObject();
obj.put("email", "shahvaiz@gmail.com");
obj.put("password", "123456");
obj.put("strategy", "jwt");

socket.emit("create", "authentication", obj);
```

Added to the documentation here: http://socketio.github.io/socket.io-client-java/emitting_events.html
