### ISSUE TITLE
If you use node js and this library, this may help you

### ISSUE THREAD

**Issue by humaidk2** [socketio/socket.io-client-java#633]
I had a couple of issues with setting up this library:

1. the latest node.js socket.io has moved to version 3.0, which is not compatible with this library.
Fix: move node.js socket.io to version 2.3.0

1. OKhttp3 error with android socket.io 0.6.0, caused by incompatibility with Firestore
Fix: changed to android socket.io 0.4.2 like so `implementation 'com.github.nkzawa:socket.io-client:0.4.2'`

1. The library was not working with Android 9.0+
Fix: Had to set up a https connection.

I think it would be nice to add the fact that it doesn't work with socket.io 3.0 in the documentation.

Edit: Fixed grammar and formatting

**Comment by twofingerrightclick** [comment]
I added a pull request about this. Hopefully one of the moderators will take. https://github.com/socketio/socket.io-client-java/pull/639

**Comment by darrachequesne** [comment]
Version [2.0.0](https://github.com/socketio/socket.io-client-java/releases/tag/socket.io-client-2.0.0) is out!

The migration guide can be found here: http://socketio.github.io/socket.io-client-java/migrating_from_1_x.html
