### ISSUE TITLE
Ping Timeout - socket.io-client-java no longer working with latest socket.IO

### ISSUE THREAD

**Issue by d4rky337** [socketio/socket.io-client-java#634]
Latest Socket.io:3.0.1 backend not working with latest socket.io-client-java:1.0.0

It's working fine up to socket-io:2.3.0.

is there any alternate solution as current socket.io-client-java is no longer compatible with latest socket.io

**Comment by darrachequesne** [comment]
Version [2.0.0](https://github.com/socketio/socket.io-client-java/releases/tag/socket.io-client-2.0.0) is out!

The migration guide can be found here: http://socketio.github.io/socket.io-client-java/migrating_from_1_x.html
