### ISSUE TITLE
Special characters in query

### ISSUE THREAD

**Issue by jcollognat** [socketio/socket.io-client-java#635]
Hello,

I have an issue related to query parameter.

I want to send an auth token to my server through a query parameter but it is sanitized by the client before it is send.
Sometimes, the token contains special caracters like "+" and necessarily end by "=". 
When these characters are cleaned by the client, my server refuse the connection because the token stored in db is not strictly equal to the other one.

I can manage the "=" because it is necessarily  at the end but I'm stuck with the others.
Does anyone got an idea to resolve my issue ?

Thanks !

**Comment by darrachequesne** [comment]
Hi!

For a `1.x` client, you should be able to use the `decodeURIComponent` method on the server side.

```js
io.on("connection", (socket) => {
  const token = decodeURIComponent(socket.handshake.query.token);
  // ...
});
```

For a `2.x` client, you can use the `auth` option, which should cover your use case:

```java
IO.Options options = IO.Options.builder()
        .setAuth(singletonMap("token", "abcd+++==="))
        .build();

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Documented here: https://socketio.github.io/socket.io-client-java/initialization.html#auth

**Comment by jcollognat** [comment]
Salut, 

j'ai testé ta 2ème solution et elle marche niquel merci beaucoup!

**Comment by WangZhiPeng0313** [comment]
My url param 'ticket' with '=' at the end. When i send it to server, the character '=' is sanitized and connect fail. I cannot upgrade code on server. How to fix it on client code. 
PS(Version: 1.0.1)
