### ISSUE TITLE
Connecting in Java to a Javascript server

### ISSUE THREAD

**Issue by chrissyast** [socketio/socket.io-client-java#637]
## My server.js

```javascript
'use strict';

let http = require('http');
let express = require('express')
let socketio = require('socket.io')
let port = process.env.PORT || 8080

let app = express()

let server = http.createServer(app)
let io = socketio(server)

io.on('connection', function(sock) {
	console.log('Connected')
	io.emit('msg','Someone just joined')
	sock.on('msg', (txt) => io.emit('msg', txt))
})
app.use(express.static(__dirname))

server.listen(port, () => console.log(`Server started on port ${port}`))
```

I already have a webpage which is hitting these methods ok when you load `localhost:8080`, and a client.js which is handling the browser-side behaviour for 'msg'.

## My Java code
```java
 Socket socket;
        try {
            socket = IO.socket("http://192.168.8.101:8080");
            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... objects) {
                    System.out.println("connected");
                }
            });
            socket.on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... objects) {
                    System.out.println("disconnected");
                }
            });
            socket.on("msg", new Emitter.Listener() {
                @Override
                public void call(Object... objects) {
                    System.out.println("message received");
                }
            });
            socket.connect();
        }
        catch (URISyntaxException e) {
            e.printStackTrace();
        }
```

But I get nothing - no logs on my java console, nor the server side upon `socket.connect()`, no java logs when I connect from the browser. I'm really not sure what I'm doing wrong.

**Comment by chrissyast** [comment]
This appears to be an issue when the javascript dependency is v3+ as I changed the package.json from
```
  "dependencies": {
    ...,
    "socket.io": "^3.0.1"
  }
```
to
```
  "dependencies": {
    ...
    "socket.io": "^2.3.0"
  }
```

everything instantly worked

**Comment by IlyaDiallo** [comment]
Yes, see #633

**Comment by chrissyast** [comment]
@IlyaDiallo Other than just using version <3.0, is there any workaround, or just need to wait for a fix?

**Comment by IlyaDiallo** [comment]
I'm afraid that there's no maintainer at the moment for the java client, so no hope of compatibility in the near future.

**Comment by chrissyast** [comment]
Ok, thanks

**Comment by twofingerrightclick** [comment]
> This appears to be an issue when the javascript dependency is v3+ as I changed the package.json from
> 
> ```
>   "dependencies": {
>     ...,
>     "socket.io": "^3.0.1"
>   }
> ```
> 
> to
> 
> ```
>   "dependencies": {
>     ...
>     "socket.io": "^2.3.0"
>   }
> ```
> 
> everything instantly worked

I just came to the same realization... I was so confused why my java client would work with my node server app, but it would work with a sample node server app. The sample one was using 2.3 ... Took me an hour to figure out,.. should have looked at the issues first.

**Comment by chrissyast** [comment]
@twofingerrightclick yes, I lost a lot of time before I noticed it too :(

**Comment by twofingerrightclick** [comment]
I added a pull request. Hopefully one of the moderators will take. https://github.com/socketio/socket.io-client-java/pull/639

**Comment by darrachequesne** [comment]
Version [2.0.0](https://github.com/socketio/socket.io-client-java/releases/tag/socket.io-client-2.0.0) is out!

The migration guide can be found here: http://socketio.github.io/socket.io-client-java/migrating_from_1_x.html
