### ISSUE TITLE
Support for socket.io 3.x

### ISSUE THREAD

**Issue by anooj1483** [socketio/socket.io-client-java#641]
There is no support for **socket.io - 3.x**.

**Comment by lukelu0520** [comment]
@anooj1483 
We got the same issue, can not connect to web server using socket.io 3.x.

**Comment by filipstojakovic** [comment]
Anyone know when can we expect support for socket.io - 3.x?

**Comment by darrachequesne** [comment]
I'm working on this. I think we should have something by the end of the week.

**Comment by fruitwingscmueller** [comment]
Is the new 1.0.1 now compatiable with socket v3? If not, is there any real eta I can work with?

**Comment by IlyaDiallo** [comment]
> Is the new 1.0.1 now compatiable with socket v3? If not, is there any real eta I can work with?

2.0.0

**Comment by IlyaDiallo** [comment]
> I'm working on this. I think we should have something by the end of the week.

That's great ! NB you should specify if the new version is also backward-compatible with a V2 server. If it's compatible, an upgrade path would be to first update clients, and when (say) 95% of clients have updated, update the server to V3 and 5% are left to die. If it's not compatible, upgrade is a lot more complicated (juggle with two different servers and so on).

**Comment by darrachequesne** [comment]
Version [2.0.0](https://github.com/socketio/socket.io-client-java/releases/tag/socket.io-client-2.0.0) is out!

The migration guide can be found here: http://socketio.github.io/socket.io-client-java/migrating_from_1_x.html

@IlyaDiallo unfortunately, the new version is not compatible with a v2 server. There is a discussion about that here: https://github.com/socketio/socket.io-protocol/issues/21

Another solution is indeed to have two different servers running in parallel, as suggested [here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html#How-to-upgrade-an-existing-production-deployment).

**Comment by IlyaDiallo** [comment]
> Version [2.0.0](https://github.com/socketio/socket.io-client-java/releases/tag/socket.io-client-2.0.0) is out!
> 
> The migration guide can be found here: http://socketio.github.io/socket.io-client-java/migrating_from_1_x.html
> 
> @IlyaDiallo unfortunately, the new version is not compatible with a v2 server. There is a discussion about that here: [socketio/socket.io-protocol#21](https://github.com/socketio/socket.io-protocol/issues/21)
> 
> Another solution is indeed to have two different servers running in parallel, as suggested [here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html#How-to-upgrade-an-existing-production-deployment).

Thanks for the the link, that's exactly was I was talking about - but the idea is not to have servers running in parallel if I understand correctly, it's to add protocol negotiation in the server and client code.

**Comment by darrachequesne** [comment]
Let's continue this discussion here: https://github.com/socketio/socket.io-protocol/issues/21
