### ISSUE TITLE
Constant "xhr poll error" when trying to establish a connection

### ISSUE THREAD

**Issue by ParadoxPixel** [socketio/socket.io-client-java#645]
**Describe the bug**
The problem I'm having is that the client is unable to connect to the socket.io server. I get a "xhr poll error" every time I try to connect but it used to work fine and then out of the blue it started having issues.

**To Reproduce**

Socket.IO server: [https://github.com/Mindgamesnl/socketio](https://github.com/Mindgamesnl/socketio)

*Server*

```golang
package main

import (
	"log"
	"net/http"
	"time"

	"github.com/Mindgamesnl/socketio"
)

func main() {
	server, _ := socketio.NewServer(time.Second*25, time.Second*5, socketio.DefaultParser)
	server.Namespace("/").
		OnConnect(func(so socketio.Socket) {
			log.Println("connected:", so.RemoteAddr(), so.Sid(), so.Namespace())
		}).
		OnDisconnect(func(so socketio.Socket) {
			log.Printf("%v %v %q disconnected", so.Sid(), so.RemoteAddr(), so.Namespace())
		}).
		OnError(func(so socketio.Socket, err ...interface{}) {
			log.Println("socket", so.Sid(), so.RemoteAddr(), so.Namespace(), "error:", err)
		}).
		OnEvent("message", func(so socketio.Socket, data string) {
			log.Println(data)
		})

	http.ListenAndServe(":4040", server)
}
```

Socket.IO java client version: `2.0.0`

*Client*

```java
public class MyApplication {
    public static void main(String[] args) throws URISyntaxException {
        IO.Options opts = new IO.Options();
        opts.callFactory = okHttpClient;
        opts.reconnection = false;
        opts.webSocketFactory = okHttpClient;

        // authentication headers
        opts.query = String.format(
                "type=server&private=%s&public=%s",
                keySet.getPrivateKey(),
                keySet.getPublicKey()
        );

        //Setup socket.io connection
        Socket socket;
        try {
            socket = IO.socket("http://localhost:4040", opts);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }

       socket.on(Socket.EVENT_CONNECT_ERROR, args -> {
            System.out.print(args[0].toString());
        });

        socket.open();
    }
}
```

**Expected behavior**
It should connect to the websocket and not directly drop the connection

**Platform:**
 - OS: Windows 10

**Additional context**
The Socket.IO server works fine for clients connecting from the browser hense why I deduced that it might be an issue with the java client.

I used the java client version `1.0.0` before this but it started instantly dropping the connection after it was just established out of the blue. A little later it stopped connecting altogether and only gave me a "transport error". An important note on this is that it worked fine before but suddenly gave me these issues.

**Edit:** I also tried [Netty-Socket.IO](https://github.com/mrniko/netty-socketio) and used Socket.IO java client version: `1.0.0` due to compatibility and this gave me the same error

**Comment by ParadoxPixel** [comment]
Nvm, after some more research and debugging turned out I forgot about some security measures I had in place.

**Comment by KillerQueen59** [comment]
can i see ur code after solved that?

**Comment by ParadoxPixel** [comment]
The error was caused by me closing the connection during the connect event
