### ISSUE TITLE
Client v.2.0.0 doesn't authorize on socket.io server v.2

### ISSUE THREAD

**Issue by CoolMind** [socketio/socket.io-client-java#646]
I tried to update the library in `build.gradle`:

    implementation('io.socket:socket.io-client:2.0.0') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }

But it stopped authorize on our server (socket.io v.2). I tried to to change queries as described in https://socketio.github.io/socket.io-client-java/migrating_from_1_x.html. Changed `query` to `auth`, tried to set `extraHeaders`, but it didn't help.

As far as I understood, the library 2.0.0 corresponds to socket.io v.3. That's why we don't need to update the library.

I add this topic here, maybe somebody will fall into the same situation.

**Comment by GingerAdonis** [comment]
According to the compatibility table in the `README.me` file in this repository the v2 Java client is **not** compatible with v2 server.

**Comment by CoolMind** [comment]
@GingerAdonis , I agree with you, also have looked there, thanks. That's a strange behaviour of a library to be not compatible with a server after upgrade.
