### ISSUE TITLE
Failed to connect - in android sample app

### ISSUE THREAD

**Issue by Salman-Samian** [socketio/socket.io-client-java#647]
hi everyone, I use both server-side and client-side to test Socket.io project just add few upgrades in android libraries just because Android studio always keep update and the version of libraries in source project was too old and back to 2015 so after making everything ready and work I faced a new error in my android application but my HTML web site works fine and make me happy, but every post or issue I read doesn't solve my problem

Toast in Login page keep showing -> Failed to connect 
![android-error-socketio](https://user-images.githubusercontent.com/4800349/104219448-5fba5d80-5453-11eb-84d1-1971942dffa1.jpeg)

**Comment by darrachequesne** [comment]
Hi! The classic questions:

- which version of the client are you using?
- which version of the Socket.IO server are you using? Are you using the Node.js implementation?
- could you please provide the code you are using to connect?

**Comment by Salman-Samian** [comment]
Hi, thanks for your quick replay :)) 


----------------------------------------------------------------
server [Node.js] : "socket.io": "^3.0.3"

client [Android Java] : "io.socket:socket.io-client:0.8.3"
----------------------------------------------------------------


( java android client  )
`
    public static final String CHAT_SERVER_URL = "http://192.168.1.150/";

`

( java android client  )
`
public class ChatApplication extends Application {

    private Socket mSocket;
    {
        try {
            mSocket = IO.socket(Constants.CHAT_SERVER_URL);
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }

    public Socket getSocket() {
        return mSocket;
    }
}
`

( java android client  Test emit from client )
` mSocket.emit("add user", username); `


----------------------------------------------------------------------------------------------------------


( node.js server )

`
// Setup basic express server
const express = require('express');
const app = express();
const path = require('path');
const server = require('http').createServer(app);
const io = require('socket.io')(server);
const port = process.env.PORT || 80;

server.listen(port, () => {
  console.log('Server listening at port %d', port);
});

// Routing
app.use(express.static(path.join(__dirname, 'public')));

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});

// Chatroom
let numUsers = 0;
io.on('connection', (socket) => {
  console.log("LOG 123");

  socket.on('add user', (username) => {
     console.log("LOG 456");
  });
});

`


if anything needed such as Server or Client app I will provide.

thanks.

**Comment by darrachequesne** [comment]
Did you check https://github.com/socketio/socket.io-client-java#compatibility ? It seems the version of your client is not compatible with the Socket.IO server.

**Comment by Salman-Samian** [comment]
My problem solved thank you.

I just sync my client and server version to :



android client : 
```
implementation ('io.socket:socket.io-client:2.0.0') {
        exclude group: 'org.json', module: 'json'
    }
```


node.js server :
```
    "socket.io": "^3.0.3"
```

thank you.

**Comment by darrachequesne** [comment]
Great news :tada: ! I'm closing the issue then.
