### ISSUE TITLE
Supporting Stream ?

### ISSUE THREAD

**Issue by danpe** [socketio/socket.io-client-java#65]
Hey,

Are you planning on supporting the stream feature you developed for socket.io: https://github.com/nkzawa/socket.io-stream ?

Thanks,
Dan

**Comment by alxpereira** [comment]
Hey, no news on this feature ? Could be awesome.

**Comment by adrianchifor** [comment]
+1

**Comment by mjansing** [comment]
Any updates on this?

**Comment by MrAlladeen** [comment]
please add stream functionality!!!!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
