### ISSUE TITLE
java.net.MalformedURLException: unknown protocol: wss

### ISSUE THREAD

**Issue by aminrz3** [socketio/socket.io-client-java#650]
According to the documentation, there is no problem in using the WSS protocol

**Socket socket = IO.socket("wss://example.com"); // OK, similar to the example above**

But when I use it, it gives the following error:
 **java.lang.RuntimeException: java.net.MalformedURLException: unknown protocol: wss**

Socket mSocket = IO.socket("wss://mydomain.com");

please help me

**Comment by Zkp275557625** [comment]
use https://mydomain.com instead of wss://mydomain.com

**Comment by darrachequesne** [comment]
For future readers: this should be fixed by https://github.com/socketio/socket.io-client-java/commit/67fd5f34a31c63f7884f82ab39386ad343527590, included in version `2.0.1`.
