### ISSUE TITLE
Recconnect event never fired

### ISSUE THREAD

**Issue by busslina** [socketio/socket.io-client-java#652]
Initialized on Foreground Service, with reconnect option set to true and force new to false. Connect and disconnect event fires correctly but never reconnect event. When reconnect occurs, only connect event is fired.

Thank you.

**Comment by darrachequesne** [comment]
Which version are you using? If it's the latest, that's expected:

- https://socketio.github.io/socket.io-client-java/socket_instance.html
- https://socketio.github.io/socket.io-client-java/migrating_from_1_x.html#The_Socket_instance_will_no_longer_forward_the_events_emitted_by_its_Manager

**Comment by busslina** [comment]
Thanks, @darrachequesne. I was using last version which is compatible with socket IO 3.x and it was expected behavior.
