### ISSUE TITLE
io.socket.engineio.client.EngineIOException: server error

### ISSUE THREAD

**Issue by ganatrac** [socketio/socket.io-client-java#657]
I am using 
server.io version ^2.0.4
express version ^4.16.3
server.io-client - 2.0.0

with client option:
SSL enabled
opts.secure = true;
opts.path = "/socket.io;

With. server option:
rememberTransport: false,
      pingInterval: 25000,
      pingTimeout: 60000,
      transports: ['polling', 'websocket'],
      secure: true,
      rejectUnauthorized: false

I am getting socket id on connect event on. server but then client errors out with "server error".

**Comment by faisalwaris** [comment]
Issue:
dependencies {    implementation ('io.socket:socket.io-client:2.0.0') {  exclude group: 'org.json', module: 'json'    }}

Description:
I am using this dependency according to the latest document of Socket.IO, this gave me the same error, I think its issue in the latest release. 

Solution: Please downgrade your release then your issue will be resolved.

**Comment by darrachequesne** [comment]
Hi! Please check the compatibility table [here](https://socketio.github.io/socket.io-client-java/installation.html).
