### ISSUE TITLE
Socket.IO server in v2.x with a v3.x client

### ISSUE THREAD

**Issue by FatmaMM** [socketio/socket.io-client-java#658]
io.socket.client.SocketIOException: It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, which is not possible

I always have this error when I am running app onto android device

**Comment by darrachequesne** [comment]
Yes, this is expected. Please see the compatibility table here: https://socketio.github.io/socket.io-client-java/installation.html

**Comment by girubhai** [comment]
Can you please share which 0.9.x version should use in this case ? Thanks

**Comment by miq0717** [comment]
@FatmaMM Did you get a solution for this? I've tried the compatible table but still getting this error :(

**Comment by superoidlau** [comment]
Server version is 3.x, this problem occurs when client using 2.1.1, but it doesn't exist in 1.0.2.  So strange. 

https://socketio.github.io/socket.io-client-java/installation.html

![Image](https://github.com/user-attachments/assets/3c09f510-4c13-4d31-83d7-9fc62039b9aa)

Is this document accurate?
