### ISSUE TITLE
Please help me, Socket not connecting to server

### ISSUE THREAD

**Issue by Joshuaap458** [socketio/socket.io-client-java#659]
@BindView(R.id.edittext_socket)
    EditText etSocket;
    @BindView(R2.id.button)
    Button button;

    public boolean isConnected;
    private com.github.nkzawa.socketio.client.Socket mSocket;
    {
        try{
            mSocket = IO.socket("https://080f0676fdfb.ngrok.io/");
        }catch(URISyntaxException e){
            throw new RuntimeException(e);
        }
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_socket2);
        ButterKnife.bind(this);
//        setHasOptionsMenu(true);
        mSocket.connect();
        mSocket.on("message", handleIncomingMessages);
        mSocket.on(Socket.EVENT_CONNECT, onConnect);
        mSocket.on(Socket.EVENT_DISCONNECT, onDisconnect);
        mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
        mSocket.on(Socket.EVENT_CONNECT_TIMEOUT, onConnectError);
        mSocket.on(Socket.EVENT_ERROR, onError);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        mSocket.disconnect();
        mSocket.off(Socket.EVENT_CONNECT, onConnect);
        mSocket.off(Socket.EVENT_DISCONNECT, onDisconnect);
        mSocket.off(Socket.EVENT_CONNECT_ERROR, onConnectError);
        mSocket.off(Socket.EVENT_CONNECT_TIMEOUT, onConnectError);
        mSocket.off(Socket.EVENT_ERROR, onError);
    }

    public void initLayout(){
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String message = etSocket.getText().toString();
                etSocket.setText(" ");
                mSocket.emit("message", message);
            }
        });
    }

    private Emitter.Listener handleIncomingMessages = new Emitter.Listener(){
        @Override
        public void call(final Object... args){
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    JSONObject data = (JSONObject) args[0];
                    String message;
                    try {
                        message = data.getString("message").toString();
                    } catch (JSONException e) {
                        return;
                    }
                    Log.i("asd", message);
                }
            });
        }
    };

    private Emitter.Listener onConnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            isConnected = true;

            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Connected...", Toast.LENGTH_LONG)
                            .show();
                    isConnected = true;
                }
            });
        }
    };
    private Emitter.Listener onDisconnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            isConnected = false;

            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Disconnected....", Toast.LENGTH_LONG)
                            .show();
                    isConnected = false;
                }
            });
        }
    };
    private Emitter.Listener onConnectError = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            isConnected = false;

            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Failed to connect...", Toast.LENGTH_LONG)
                            .show();
                    isConnected = false;
                }
            });
        }
    };
    private Emitter.Listener onError = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            Toast.makeText(getBaseContext(), "onError", Toast.LENGTH_LONG)
                    .show();
        }
    };

**Comment by darrachequesne** [comment]
Hi! In the bug report template, you're asked to provide the version of the server/client that you are using, in order to help us help you. Could you please add those details?

**Comment by Joshuaap458** [comment]
> Hi! In the bug report template, you're asked to provide the version of the server/client that you are using, in order to help us help you. Could you please add those details?

i'll send them to you tomorrow sir, please i really need help got stucked for a week with no progress

**Comment by darrachequesne** [comment]
`private com.github.nkzawa.socketio.client.Socket mSocket;` suggests you are using an old version of the client.

Please check the documentation here: https://socketio.github.io/socket.io-client-java/installation.html

**Comment by Joshuaap458** [comment]
> `private com.github.nkzawa.socketio.client.Socket mSocket;` suggests you are using an old version of the client.
> 
> Please check the documentation here: https://socketio.github.io/socket.io-client-java/installation.html

do i need to use IO.option ? for connecting the socket?

**Comment by Joshuaap458** [comment]
Hi @darrachequesne, do i need to use this "IO.Options options = IO.Options.builder()"?  i cant seem to use that it says cannot resolve method builder in option

**Comment by darrachequesne** [comment]
@Joshuaap458 are you using:

```xml
<dependency>
  <groupId>io.socket</groupId>
  <artifactId>socket.io-client</artifactId>
  <version>2.0.0</version>
</dependency>
```

In any case, the `options` argument is optional:

```java
Socket socket = IO.socket(uri);
```

**Comment by Joshuaap458** [comment]
> @Joshuaap458 are you using:
> 
> ```
> <dependency>
>   <groupId>io.socket</groupId>
>   <artifactId>socket.io-client</artifactId>
>   <version>2.0.0</version>
> </dependency>
> ```
> 
> In any case, the `options` argument is optional:
> 
> ```java
> Socket socket = IO.socket(uri);
> ```

so what i need just to connect to the url/uri is "Socket socket = IO.socket(uri)" right?

**Comment by darrachequesne** [comment]
Yes indeed :+1:

**Comment by Joshuaap458** [comment]
@BindView(R.id.edittext_socket)
    EditText etSocket;
    @BindView(R2.id.button)
    Button button;

    private boolean isConnected;
    private Socket mSocket;

    {
        try{
                mSocket = IO.socket("https://e3e0b0ab94b5.ngrok.io/");
        }catch(Exception e){
            throw new RuntimeException(e);
        }
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_socket2);
        ButterKnife.bind(this);
        mSocket.connect();
        mSocket.on("message", handleIncomingMessages);
        mSocket.on(Socket.EVENT_CONNECT, onConnect);
        mSocket.on(Socket.EVENT_DISCONNECT, onDisconnect);
        mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        mSocket.disconnect();
        mSocket.off(Socket.EVENT_CONNECT, onConnect);
        mSocket.off(Socket.EVENT_DISCONNECT, onDisconnect);
        mSocket.off(Socket.EVENT_CONNECT_ERROR, onConnectError);
        mSocket.off("message", handleIncomingMessages);
    }

    public void initLayout(){
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String message = etSocket.getText().toString();
                etSocket.setText(" ");
                mSocket.emit("message", message);
            }
        });
    }


    private Emitter.Listener handleIncomingMessages = new Emitter.Listener(){
        @Override
        public void call(final Object... args){
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    JSONObject data = (JSONObject) args[0];
                    String message;
                    try {
                        message = data.getString("message").toString();
                        Log.i("asd", message);
                    } catch (JSONException e) {
                        return;
                    }
                }
            });
        }
    };

    private Emitter.Listener onConnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            isConnected = true;

            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Connected...", Toast.LENGTH_LONG).show();
                    isConnected = true;
                }
            });
        }
    };
    private Emitter.Listener onDisconnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            isConnected = false;

            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Disconnected....", Toast.LENGTH_LONG).show();
                    isConnected = false;
                }
            });
        }
    };
    private Emitter.Listener onConnectError = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            isConnected = false;
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Failed to connect...", Toast.LENGTH_LONG).show();
                    mSocket.connect();

                }
            });
        }
    };

@darrachequesne , this is my latest code but its not working it keeps on toasting Failed to connect.. , what is wrong with my code ? please help

**Comment by darrachequesne** [comment]
Regarding your Socket.IO server:

- which implementation are you using? the official Node.js (from https://github.com/socketio/socket.io)?
- which version are you using? The compatibility table is [here](https://socketio.github.io/socket.io-client-java/installation.html).
- is your server actually reachable? What is the output of `curl "https://e3e0b0ab94b5.ngrok.io/socket.io/?EIO=4&transport=polling"`?

**Comment by Joshuaap458** [comment]
1. the one who codes the node js is my friend actually, and yes he implement it from that documentation

2. im using = implementation ('io.socket:socket.io-client:2.0.0') {
        exclude group: 'org.json', module: 'json'
    }
the server use 4.0.0

3. how can i test it this? the server is on now "https://25632575f537.ngrok.io/"

**Comment by Joshuaap458** [comment]
https://25632575f537.ngrok.io/socket.io/?EIO=4&transport=polling 

- copy paste this on my browser and i found this

The connection to https://25632575f537.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:9001.
Make sure that a web service is running on localhost:9001 and that it is a valid address.
The error encountered was: dial tcp [::1]:9001: connect: connection refused
@darrachequesne

**Comment by Joshuaap458** [comment]
got new updates regarding the curl

0{"sid":"ccQjbAOXK97SvopRAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000}

**Comment by Joshuaap458** [comment]
please help me im stuck @darrachequesne

**Comment by darrachequesne** [comment]
> The connection to https://25632575f537.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:9001.
Make sure that a web service is running on localhost:9001 and that it is a valid address.
The error encountered was: dial tcp [::1]:9001: connect: connection refused

It looks like the server is not listening to port 9001 on your machine. Which sounds weird, if you say that the curl command actually reaches the Socket.IO server.

Ngrok does support WebSocket (https://ngrok.com/docs#http-websockets), so that does not explain the issue.

What is the output of `curl "http://localhost:9001/socket.io/?EIO=4&transport=polling"` on your local machine? Same as the previous command?

**Comment by Joshuaap458** [comment]
@darrachequesne  the output is this 

0{"sid":"WKzu2HguykRGVZ4fAAAG","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000}

**Comment by Joshuaap458** [comment]
this is my latest code, not much different

@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_socket2);
        ButterKnife.bind(this);
        {
            try{
                mSocket = IO.socket("https://39a0c1094978.ngrok.io/");
                Log.i("asd ", "masuk try socket");
            }catch(Exception e){
                throw new RuntimeException(e);
            }
        }
        mSocket.connect();
        if (mSocket.connected()) {
            Toast.makeText(Socket2Activity.this, "Socket Connected!!", Toast.LENGTH_SHORT).show();
        }
        initLayout();
        mSocket.on("Mobile", handleIncomingMessages);
        mSocket.on("connection", onConnect);
        mSocket.on(Socket.EVENT_DISCONNECT, onDisconnect);
        mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
    }

    @Override
    protected void onPause() {
        super.onPause();
        mSocket.disconnect();
        mSocket.off();

    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        mSocket.disconnect();
        mSocket.off();
    }

    public void initLayout(){
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.i("asd", "masuk button");
                String message = etSocket.getText().toString();
                etSocket.setText(" ");
                mSocket.emit("message", message);
            }
        });
    }

    private Emitter.Listener handleIncomingMessages = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            System.out.println(args[0]);
            Log.i("asd ", "socket event message" + args[0]);
        }
    };


    private Emitter.Listener onConnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Log.i("asd ", "connect");
                    Toast.makeText(getBaseContext(), "Connected...", Toast.LENGTH_LONG).show();
                }
            });
        }
    };

    private Emitter.Listener onDisconnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Disconnected....", Toast.LENGTH_LONG).show();
                }
            });
        }
    };

    private Emitter.Listener onConnectError = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            isConnected = false;
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(getBaseContext(), "Failed to connect...", Toast.LENGTH_LONG).show();
                    mSocket.connect();
                }
            });
        }
    };

@darrachequesne

**Comment by Joshuaap458** [comment]
hello @darrachequesne, im having issues the connection is so hard to connect dont know why, do you know to make the connection stronger or any other socket option/setting that i have to add ? please help me thank you so much

**Comment by Joshuaap458** [comment]
@nkzawa hello can you pls help me, im having connection issues, its hard to connect to the server
