### ISSUE TITLE
How to customize the default URL(/socket.io/?EIO=...) in client and server?

### ISSUE THREAD

**Issue by Tracy0725** [socketio/socket.io-client-java#661]
I want to customize the default URL such as /MySocket/?EIO=...

**Comment by darrachequesne** [comment]
I think you are looking for the `path` option:

```java
IO.Options options = IO.Options.builder()
        .setPath("/MySocket/")
        .build();

Socket socket = IO.socket(URI.create("https://example.com"), options);
```

Documentation: https://socketio.github.io/socket.io-client-java/initialization.html#path

**Comment by Tracy0725** [comment]
> I think you are looking for the `path` option:
> 
> ```java
> IO.Options options = IO.Options.builder()
>         .setPath("/MySocket/")
>         .build();
> 
> Socket socket = IO.socket(URI.create("https://example.com"), options);
> ```
> 
> Documentation: https://socketio.github.io/socket.io-client-java/initialization.html#path

Yes, thanks! and Attach the method in server.
In client:
```
 IO.Options options = new IO.Options();
options.path = "/custom.socket.io";
```
In cerver:
```
com.corundumstudio.socketio.Configuration config = new com.corundumstudio.socketio.Configuration();
config.setContext("/custom.socket.io");
```
