### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by SudoDios** [socketio/socket.io-client-java#662]
Hi.
In version 1.0.1 I had no problem.
But when I updated, it will not connect to version 2.0.1 anymore

**Comment by darrachequesne** [comment]
Hi! Did you check the compatibility table here: https://socketio.github.io/socket.io-client-java/installation.html ?

**Comment by SudoDios** [comment]
I have no problem with dependence. 
The problem is that it does not connect to the server.

**Comment by SudoDios** [comment]
I will do a check myself and post the result here. 
I will not take your time.  
Thankful

**Comment by ErsinDemirbas** [comment]
> I will do a check myself and post the result here.
> I will not take your time.
> Thankful

same problem, did you find a solution, I couldnt connect.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
