### ISSUE TITLE
Having emit issues

### ISSUE THREAD

**Issue by Joshuaap458** [socketio/socket.io-client-java#663]
so this is the setting that i use 

IO.setDefaultOkHttpCallFactory(okHttpClient);
                IO.setDefaultOkHttpWebSocketFactory(okHttpClientSocket);
                IO.Options opts = new IO.Options();
                opts.transports = new String[]{WebSocket.NAME};
                opts.reconnection = true;
                opts.callFactory = okHttpClient;
                opts.webSocketFactory = okHttpClientSocket;
                mSocket = IO.socket("https://a6599436a457.ngrok.io/", opts);

after connection i succeeded in send message to the server and i receive one of the emit which is 

.on("Mobile", new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                        Log.i("test", "Mobile " + args[0]);
                    }

But i cant seem to receive from the other emit
from this 

.on("refreshPage", new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                        Log.i("test ", "refreshPage " + args[0]);
                    }

Please help me

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
