### ISSUE TITLE
Problem with importing jars

### ISSUE THREAD

**Issue by PratiquesAlgorithmiques** [socketio/socket.io-client-java#667]
I have a stupid question. I'm trying to use using socket.io-client-java with jars instead of maven and I can't get things set up...
In my build path I have 

Java-WebSocket-1.3.8.jar
engine.io-client-2.0.0.jar
json-20090211.jar
okhttp-3.12.12.jar
okio-1.15.0.jar
socket.io-client-2.0.1.jar

And in my script I've tried 

import io.socket.client.IO;
import io.socket.client.Socket;

But it can't find them. AM I missing something ?
Thanks for any help.

**Comment by PratiquesAlgorithmiques** [comment]
Anyone ?

**Comment by darrachequesne** [comment]
> with jars instead of maven

But... why would you do that? More seriously, could you please explain your use case?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
