### ISSUE TITLE
Can't receive emit from server

### ISSUE THREAD

**Issue by Joshuaap458** [socketio/socket.io-client-java#671]
So i've managed to connect to the server, and i have an event called "Mobile" and i successfully receive a message from it. However i send a string through an API call from postman the event is "updateData" and i cant seem to receive it on my android emulator. anyone had the issue like this?

server 

const socketid = await getRedis(`socket-${body.patientId}`);
 io.to(socketid).emit('updateData', 'Refresh1');
 io.emit('updateData', 'Refresh2');
 io.on('updateData', async (socket) => {
 socket.emit('updateData', 'Refresh3');
 });

client 
mSocket.on("updateData", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                            for (Object obj : args) {
                           Log.v("test", "updateData " + obj);
                     }
                  }
            });

Need help guys...

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
