### ISSUE TITLE
Calling the IO.Options.builder() kill the current thread

### ISSUE THREAD

**Issue by SkyDonald** [socketio/socket.io-client-java#674]
![image](https://user-images.githubusercontent.com/72652690/122684794-f7448900-d207-11eb-9323-880d144e6061.png)
When I put this into my code, the current Thread crash.
WHY

**Comment by darrachequesne** [comment]
Is there any exception thrown? Could `mc.thePlayer` be null?

**Comment by SkyDonald** [comment]
There is no error, mc.thePlayer can't be null
