### ISSUE TITLE
Socket.io Server Url For Testing

### ISSUE THREAD

**Issue by ErsinDemirbas** [socketio/socket.io-client-java#678]
In my Android app I have created a Socket.io client side(V2). My problem is that I couldnt any socket.io url which use v3 or higher.

For example these two url use socket.io under v3. ->

https://socketio-chat-h9jt.herokuapp.com/ or

https://socketio-whiteboard-zmx4.herokuapp.com/

Note: I dont know how to create server side. I am an new grad Android Developer. Thanks in advance.

**Comment by darrachequesne** [comment]
For future readers, you can use http://echo.socket.io
