### ISSUE TITLE
WebSocketClient: no such method

### ISSUE THREAD

**Issue by squirrelsRduck** [socketio/socket.io-client-java#69]
Hi, so i included all 4 dependencies (engine, socket, websocket, json), and yet i get this error when i try to invoke the socket.connect() method.  anybody familiar with this error?  Thanks.  Not sure if this is important, but my server is using:   "express": "3.4.8"   and   "socket.io": "^1.2.1"

12-10 11:09:09.979: D/dalvikvm(16661): DexOpt: unable to opt direct call 0x060b at 0x04 in Lcom/github/nkzawa/engineio/client/transports/WebSocket$1;.<init>
12-10 11:09:09.979: W/dalvikvm(16661): threadid=12: thread exiting with uncaught exception (group=0x40e93960)
12-10 11:09:09.989: E/AndroidRuntime(16661): FATAL EXCEPTION: EventThread
12-10 11:09:09.989: E/AndroidRuntime(16661): java.lang.NoSuchMethodError: Lorg/java_websocket/client/WebSocketClient;.<init>
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.transports.WebSocket$1.<init>(WebSocket.java:41)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.transports.WebSocket.doOpen(WebSocket.java:41)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Transport$1.run(Transport.java:73)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Transport.open(Transport.java:68)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Socket.probe(Socket.java:444)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Socket.onOpen(Socket.java:457)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Socket.onHandshake(Socket.java:497)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:471)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Socket.access$800(Socket.java:29)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:285)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.transports.Polling.access$700(Polling.java:15)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.transports.Polling$2.call(Polling.java:122)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.parser.Parser.decodePayload(Parser.java:251)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.transports.Polling._onData(Polling.java:132)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.transports.Polling.onData(Polling.java:104)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
12-10 11:09:09.989: E/AndroidRuntime(16661):    at java.lang.Thread.run(Thread.java:856)

**Comment by andrianinmagine** [comment]
where is the solution?

**Comment by squirrelsRduck** [comment]
i had forgotten to export the dependency JARs in the Build Path config

**Comment by andrianinmagine** [comment]
@squirrelsRduck what jar?sorry I'm a newbie?

**Comment by squirrelsRduck** [comment]
You can download them from Maven Centrals website.  Just search for them there

Sent from Yahoo Mail on Android
