### ISSUE TITLE
Events callbacks

### ISSUE THREAD

**Issue by piranna** [socketio/socket.io-client-java#693]
Javascript client events listeners support [the last argument to be a callback function](https://socket.io/docs/v4/client-api/#socketoneventname-callback), so it's possible to call it to send back a reply to an event emitted by the server. [This is also supported by the C++ library](https://github.com/socketio/socket.io-client-cpp#bind-with-lambda), but there's no reference to the same functionality when [listening events in the Java client](https://socketio.github.io/socket.io-client-java/listening_to_events.html). I've reviewed the actual Java library source code, but found no clue about it.

**Comment by darrachequesne** [comment]
Please check the documentation here: https://socketio.github.io/socket.io-client-java/emitting_events.html#Acknowledgements

**Comment by piranna** [comment]
I've already check the documentation before, and that's NOT what I'm asking about.

That link you've send me is about Java client emitting an event, and including an acknowledge callback to receive a response from the server. What I'm asking about is the other way, the server emitting an event with an acknowledge, and the Java client having a callback argument in its event listener to be able to send back the response to the server. That last functionality is missing in the Java client, but it's available at least for Javascript, C++ and iOS clients, as shown in the referenced links.

Please re-open this issue, it's not solved.

**Comment by darrachequesne** [comment]
@piranna you are absolutely right, sorry for dismissing the issue too quickly. I've added an example with a server to client ack: https://socketio.github.io/socket.io-client-java/emitting_events.html#From_server_to_client

*Server*

```js
io.on("connection", (socket) => {
  socket.emit("hello", "please acknowledge", (response) => {
    console.log(response); // prints "hi!"
  });
});
```

*Client*

```java
// Java 7
socket.on("hello", new Emitter.Listener() {
    @Override
    public void call(Object... args) {
        System.out.println(args[0]); // "please acknowledge"
        if (args.length > 1 && args[1] instanceof Ack) {
            ((Ack) args[1]).call("hi!");
        }
    }
});

// Java 8 and above
socket.on("hello", args -> {
    System.out.println(args[0]); // "please acknowledge"
    if (args.length > 1 && args[1] instanceof Ack) {
        ((Ack) args[1]).call("hi!");
    }
});
```



Documentation:

**Comment by piranna** [comment]
Ah, great, that was the info I was looking for, thank you for adding the example in the docs :-)
