### ISSUE TITLE
Unresponsive CDN

### ISSUE THREAD

**Issue by Azhro** [socketio/socket.io-client-java#699]
**Describe the bug**
It appears that this dependencies is trying to fetch data from some unresponsive CDN

**Additional context**
Everything leads to this: https://jcenter.bintray.com/

Here's the error log i get.
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':verifyReleaseResources'.
> Could not resolve all task dependencies for configuration ':releaseRuntimeClasspath'.
   > Could not resolve io.socket:socket.io-client:1.+.
     Required by:
         project :
      > Failed to list versions for io.socket:socket.io-client.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/io/socket/socket.io-client/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/io/socket/socket.io-client/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by darrachequesne** [comment]
Hi! I didn't find any reference to bintray in the repository, could you please check?

Related: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
