### ISSUE TITLE
Missing option in the IO.Options

### ISSUE THREAD

**Issue by champymarty** [socketio/socket.io-client-java#701]
I need the  rejectUnauthorized : false  . Without it, I cannot connect to my javascript server(I tried with the javascript version).

I dont find that option in the java version. What Can I do ?

**Comment by darrachequesne** [comment]
For future readers:

I've added it in the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#Trust_all_certificates

Please reopen if needed.
