### ISSUE TITLE
Eclipse & JAR import

### ISSUE THREAD

**Issue by MarkusPint** [socketio/socket.io-client-java#73]
I do not fully understand how to use the package in Eclipse.
1. I created a new project.
2. I added the socket.io-client.java JAR to Referenced libraries as well as the dependencies listed in pom.xml, manually.

Now my main .java file looks like this:

import com.github.nkzawa._;
import com.github.nkzawa.socketio._;
import com.github.nkzawa.socketio.client.Socket;
import com.github.nkzawa.hasbinary._;
import org.json._;
import org.java_websocket._;
import org.hamcrest._;
import org.skyscreamer.jsonassert._;
import org.junit._;

public class MySocket extends Socket {

}

When I hover over "Socket", the tooltip says:
"The type com.github.nkzawa.emitter.Emitter cannot be resolved. It is indirectly referenced from required .class files."

**Comment by isijara** [comment]
Did you find a solution?

**Comment by SoroOumar** [comment]
azertyuio
